### ISSUE TITLE
Cannot find read files in data/raw_fastq

### ISSUE THREAD

**Issue by SamLambrechtsUGent** [jtamames/SqueezeMeta#46] opened 2019-11-15 09:31 UTC
Hello,

When running

```
module load SqueezeMeta/0.4.3-foss-2018b-Python-2.7.15
cd /user/scratch/gent/gvo000/gvo00043/vsc42339
SqueezeMeta.pl -m coassembly -p squeezemeta_pilot_coassembly_megahit -s /user/scratch/gent/gvo000/gvo00043/vsc42339/pilot.samples -f /user/scratch/gent/gvo000/gvo00043/vsc42339/CLEAN_READS -t 36
```
I get the following error message:

```
Cannot find read files in /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/squeezemeta_pilot_coassembly_megahit/data/raw_fastq
Stopping in STEP1 -> 01.run_assembly.pl (megahit)

```
When I check `.../data/raw_fastq` however, the paired end read files were copied there by squeezemeta, but they were all 1 KB in size. Then there is a par2.fastq file that is 94 GB in size. I tried to solve this by copying the raw read files to  `.../data/raw_fastq` myself, and running the command again, but the problem seems to persist.

I wonder whether I did something wrong when creating my pilot.samples file? I attached it below. For example, I have two paired end read files for sample PA_4, and I labelled the forward reads as pair1 in the third column, and the reverse reads as pair2 in the third column. So, in total I have 6 samples, each represented by two fastq files, one for the forward reads, and one for the reverse reads. Is this the correct way of doing it?

```
PA_4	ERR_PA_4_2018_1.fastq	pair1
PA_4	ERR_PA_4_2018_2.fastq	pair2
PA_5	ERR_PA_5_2018_1.fastq	pair1
PA_5	ERR_PA_5_2018_2.fastq	pair2
PB_N_7	ERR_PB_N_7_2018_1.fastq	pair1
PB_N_7	ERR_PB_N_7_2018_2.fastq	pair2
PB_N_8	ERR_PB_N_8_2018_1.fastq	pair1
PB_N_8	ERR_PB_N_8_2018_2.fastq	pair2
PB_N_9	ERR_PB_N_9_2018_1.fastq	pair1
PB_N_9	ERR_PB_N_9_2018_2.fastq	pair2
PB_N_OTC_9_10_CON_B	ERR_PB_N_OTC9_10_2018_CON_B_1.fastq	pair1
PB_N_OTC_9_10_CON_B	ERR_PB_N_OTC9_10_2018_CON_B_2.fastq	pair2
```

Or could this be related to the version of SqueezeMeta and the included version of megahit I'm using? I requested the installation of the latest version of SqueezeMeta on the HPC cluster, but since that will take at least a few weeks, or even months, I would like to continue with the version of squeezemeta I currently have at my disposal (v0.4.3)

**Comment by fpusan** [comment] 2019-11-15 10:24
Hi,

First of all, did it run with the test example we provide?

The samples file seems to be right, but it would be better if you send it to me attached. There might be weird issues with tabs and spaces that v0.4.3 is unable to detect.

SqueezeMeta should have generated a par1.fastq and a par2.fastq, each of those containing the concatenated fastq files from pair1 and pair2, respectively. Those are the files that megahit needs to run. It seems that somehow you only got the pair2.

So there are different alternatives here,

1) Generate the par1.fastq and the par2.fastq manually, put them in the `/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/squeezemeta_pilot_coassembly_megahit/data/raw_fastq` and run the `01.run_assembly.pl`script. If it works, you can then continue from step 2.

2) Run SqueezeMeta using the merged mode, which should yield comparable results and would not run into that particular run.

3) Use a newer version of SqueezeMeta. Note that you don't need administrator privileges to install a new version of SqueezeMeta, only to install the system libraries (which should be already present). So if you just unzip the v1.0.0 folder in your home directory (or wherever) and link it against the databases (using the configure_nodb.pl script, see section 3 of the readme for details) then it should be good to go.

Let me know what works best for you,

Fernando

**Comment by jtamames** [comment] 2019-11-15 10:31
Hello
If you choose the first option, just do "cat *1.fastq > data/raw_fastq/par1.fastq; cat *2.fastq > data/raw_fastq/par2.fastq" and then restart SqueezeMeta from step 1. That should do it.

Best,
J

**Comment by SamLambrechtsUGent** [comment] 2019-11-20 10:00
Hello,

Thank you for the suggested solutions. I tried running squeezemeta in merged mode instead but got the following error message:

```
187.0Gb memory in total.
Using: 168.516Gb.
megahit: Cannot find file --k-list
Error running command:    megahit  -r  --k-list 29,39,59,79,99,119,141 -t 36 -o /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/squeezemeta_pilot_merged/data/megahit at /data/gent/423/vsc42339/Squeezemeta/software/SqueezeMeta/0.4.3-foss-2018b-Python-2.7.15/scripts/../scripts/01.run_assembly_merged.pl line 101.
Stopping in STEP1 -> 01.run_assembly_merged.pl (megahit). File /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/squeezemeta_pilot_merged/results/01.squeezemeta_pilot_merged.fasta is empty!
```

Do you perhaps have any idea what the problem might be in this case?

Best,

Sam

**Comment by fpusan** [comment] 2019-11-20 10:19
Hi,

I would like to ask you again whether SqueezeMeta worked with the test files we provide. 

Also, it would be great if you could send me the samples file you are using for your project. I know that you pasted it in one of your previous posts, but I would still prefer to actually have the file so I can check whether there is any problem with formatting (e.g. inconsistent use of tabs and spaces, or Windows-like line terminators).

Best,

Fernando

**Comment by SamLambrechtsUGent** [comment] 2019-11-21 12:51
Hello,

Sorry I forgot the test case. When running the test example, the first steps including megahit seem to work fine. I will try to use that information to fix my own run. I will construct a new samples file starting from test.samples, write the SqueezeMeta.pl command exactly in the same way as was done for the test case, and report back. If that doesn't work I will sent you my samples file. 

However, further in the pipeline, squeezemeta failed when running barrnap on the test example. I received the following error message:

```
Error running command:    barrnap --quiet --threads 36 --kingdom bac --reject 0.1 /kyukon/data/gent/vo/000/gvo00043/vsc42339/SqueezeMeta_data/test/Hadza/results/02.Hadza.maskedrna.fasta --dbdir /vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00043/vsc42339/SqueezeMeta_data/db > /kyukon/data/gent/vo/000/gvo00043/vsc42339/SqueezeMeta_data/test/Hadza/temp/bac.gff at /data/gent/423/vsc42339/Squeezemeta/software/SqueezeMeta/0.4.3-foss-2018b-Python-2.7.15/scripts/../scripts/02.run_barrnap.pl line 43.
Stopping in STEP2 -> 02.run_barrnap.pl
```

Thank you for your help,

Sam

**Comment by fpusan** [comment] 2019-11-22 10:42
Hi,

Could you send me the `/kyukon/data/gent/vo/000/gvo00043/vsc42339/SqueezeMeta_data/test/Hadza/SqueezeMeta_conf.pl` file?

Best,

Fernando

**Comment by SamLambrechtsUGent** [comment] 2019-11-25 17:53
Hello,

In attachment the requested SqueezeMeta_conf.pl file:

[SqueezeMeta_conf.pl.gz](https://github.com/jtamames/SqueezeMeta/files/3887940/SqueezeMeta_conf.pl.gz)

Thank you for looking into this

**Comment by fpusan** [comment] 2019-11-26 10:37
I think I see the problem now.
Adding `/data/gent/423/vsc42339/Squeezemeta/software/SqueezeMeta/0.4.3-foss-2018b-Python-2.7.15/bin` (and all the subfolders within) to your PATH environmental variable might solve it.

Alternatively, you might try using a newer version, since v0.4.3 is rather old and you might find further issues. Can you use conda? We're (experimentally) giving support to it, it should allow you to get SQM running without administrator privileges, maybe that would work for you?

**Comment by SamLambrechtsUGent** [comment] 2019-11-27 12:49
Hi,

Thank you for the suggested solutions. I tried using SqueezeMeta 1.0.0, but it also failed when running barrnap. 

I checked `/data/gent/423/vsc42339/Squeezemeta/software/SqueezeMeta/0.4.3-foss-2018b-Python-2.7.15/bin` (and also the bin folder for SQM v1.0.0), but these folders are empty. I'm assuming they shouldn't be... So I addressed the problem with the administrators of the HPC cluster first, to see if something went wrong with the installation or not.

**Comment by fpusan** [comment] 2019-11-27 13:20
Did you configure the new SqueezeMeta version with the configure_nodb.pl script?

Also you would need to start a new run, it won't work by restarting (unless you manually change the $installpath variable in the project's SqueezeMeta_conf.pl file so that it points to the new SqueezeMeta installation)

**Comment by fpusan** [comment] 2019-11-27 13:29
Also if it's possible to use conda in your cluster you can get a experimental version of SQM with

`conda install -c fpusan -c bioconda squeezemeta`

This is a developement build that might have several bugs, but might be an alternative to easily get the program up and running.

**Comment by SamLambrechtsUGent** [comment] 2019-11-27 13:34
Yes, I configured the new SqueezeMeta version with the configure_nodb.pl script, so it knows the location of the databases I downloaded using the previous (0.4.3) installation. And I did indeed also start a new run.

I'm not 100% sure, but on the HPC of our university I don't think it's possible to use conda. I have to file an installation request whenever I want to use some kind of program, and they use the EasyBuild installation tool for this.

**Comment by jtamames** [comment] 2019-11-27 13:45
Anyway, if the bin directory is empty, it is sure that your installation is not complete. Talk to your admin people and let them know this.
Best,

**Comment by boegel** [comment] 2019-11-27 18:48
Admin here who helped @SamLambrechtsUGent install `SqueezeMeta`...

The reason the `bin` directory is empty is that I purposely removed all the binaries that are shipped with `SqueezeMeta`, because they are all provided outside of the `SqueezeMeta` installation.

We do this for a number of reasons, the primary one being that many of the tools `SqueezeMeta` requires are already available on our system, properly optimized for the Intel processors we used.

I've installed SqueezeMeta 0.4.3 via EasyBuild, see [here](https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/s/SqueezeMeta/SqueezeMeta-0.4.3-foss-2018b-Python-2.7.15.eb) for an overview of the dependencies I've used there.

For SqueezeMeta 1.0.0 the installation was done in the same way, except that `Short-Pair`, `SAMtools` and `CompareM` were added as dependencies as well (which were not needed yet for v0.4.3).

So, the problem is *not* that `barrnap` is missing, it's actually there (available via `$PATH`):

```
 barrnap --help
Synopsis:
  barrnap 0.9 - rapid ribosomal RNA prediction
Author:
  Torsten Seemann
Usage:
  barrnap [options] chr.fa
  barrnap [options] < chr.fa
  barrnap [options] - < chr.fa
Options:
  --help            This help
  --version         Print version and exit
  --citation        Print citation for referencing barrnap
  --kingdom [X]     Kingdom: euk mito arc bac (default 'bac')
  --quiet           No screen output (default OFF)
  --threads [N]     Number of threads/cores/CPUs to use (default '1')
  --lencutoff [n.n] Proportional length threshold to label as partial (default '0.8')
  --reject [n.n]    Proportional length threshold to reject prediction (default '0.25')
  --evalue [n.n]    Similarity e-value cut-off (default '1e-06')
  --incseq          Include FASTA _input_ sequences in GFF3 output (default OFF)
  --outseq [X]      Save rRNA hit seqs to this FASTA file (default '')
```

Is there an easy way to let SqueezeMeta show the output produced by the tools (like `barrnap`) it calls, incl. possible error messages?

**Comment by boegel** [comment] 2019-11-27 19:38
OK, the problem becomes pretty obvious by just running the `barrnap` command manually:

```
$ barrnap --quiet --threads 36 --kingdom bac --reject 0.1 /path/to/SqueezeMeta_data/test/Hadza/results/02.Hadza.maskedrna.fasta --dbdir /path/to/SqueezeMeta_data/db
Unknown option: dbdir
...
```

It would have been nice if that error message was mentioned along with `Error running command:  barrnap ...`.

So, the `barrnap` script that is included with `SqueezeMeta` was changed to accept an additional `dbdir` argument, which the original `barrnap` (available at https://github.com/tseemann/barrnap) does not support.

Is there an overview of changes that have been made to tools that are vendored with `SqueezeMeta`?
Is `barrnap` an exception, or is it utterly hopeless to try and provide the various tools that `SqueezeMeta` through the "official" versions?

**Comment by fpusan** [comment] 2019-11-27 19:39
SqueezeMeta explicitly calls the executables in the `.../SqueezeMeta/bin` directory, and thus will _not_ work without them even if said executables are actually available.

There are several reasons for this, the chief being that many of the redistributed programs carry minor modifications to ensure compatibility with the full pipeline.

This behaviour can be easily modified. The `.../SqueezeMeta/scripts/SqueezeMeta_conf.pl` contains the execution strings for the different dependencies of SqueezeMeta.

e.g. `$barrnap_soft       = "$installpath/bin/barrnap";`

can be sustituted for
`$barrnap_soft       = "barrnap";`

so that SqueezeMeta uses the barrnap binary from `$PATH`.

I understand that you'd prefer to use a common set of binaries for all your users. I can send you a list with the software we actually modified, so that you can keep the SqueezeMeta version of those programs and discard the rest. For what I can tell, that _should_ work. However do understand that this is not the intended way to use SqueezeMeta, so giving support to bugs appearing under this condition will not be a priority to us.

**Comment by boegel** [comment] 2019-11-27 19:42
@fpusan Thanks for the reply.

I'm aware that `SqueezeMeta_conf.pl` needs to be changed along with removing the vendored scripts/binaries in `bin/`, that's exactly what I did (see [patch file here](https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/s/SqueezeMeta/SqueezeMeta-0.4.3_fix-hardcoding.patch)).

An overview of which tools were changed (and if possible, how), would be very useful. Maybe this should even be included in the README?

**Comment by fpusan** [comment] 2019-11-27 19:49
Changes should be already documented in the different scripts, but I agree that it would be a good idea to compile everything in a single file, both for our own reference and that of other developers. Will get to it tomorrow.

Regarding your other request, we are currently changing how we log errors in SqueezeMeta. For the upcoming v1.1.0 the error messages produced by the different subprocesses will get recorded into an error log.

**Comment by fpusan** [comment] 2019-11-28 12:19
Please check https://github.com/jtamames/SqueezeMeta/blob/master/VENDORED-TOOLS.md, which should contain the required info

**Comment by boegel** [comment] 2019-11-28 13:26
@fpusan That is very helpful, thank you very much for providing this overview! :+1:

**Comment by fpusan** [comment] 2019-11-28 17:58
Closing this issue, since the discussion has become unrelated to the original topic. Feel free to open a new one if you need further assistance.

**Closed by fpusan** 2019-11-28 17:58 UTC
