### ISSUE TITLE
MaxBin is very slow

### ISSUE THREAD

**Issue by nebfield** [jtamames/SqueezeMeta#69] opened 2020-02-25 18:18 UTC
Hi,

I'm running SqueezeMeta in co-assembly mode and MaxBin has been using 100% of 1 CPU for about a week, despite `-threads` being set to 24.

My data are quite large: around 15 samples and 175GB compressed of non-human reads (high sequencing depth). Co-assembly and mapping took around a week to complete.

There may be nothing I can do but wait, but I was wondering is there anything I can do to speed up the process or see how far binning has gotten. Also, is this a common problem with big metagenomic datasets? 

Thanks

**Comment by jtamames** [comment] 2020-02-26 07:51
Hello Benjamin

Yes, unfortunately Maxbin is very slow for big datasets as yours, and yes, it is a common problem. We call it using the number of threads set by the user but I don´t know how it works internally. Upcoming versions of SqueezeMeta will include the capablility of adding new binning methods, so that you could select the most appropriate ones. I am sorry for not being more helpful this time.
Best,
Javier

**Comment by nebfold** [comment] 2020-02-26 11:08
Hi Javier,

Thanks for your help, I was just concerned that something was wrong. I'll try to be more patient 😄 

Cheers
Ben

**Comment by yjiakang** [comment] 2020-04-15 01:19
@fpusan hello, is there a method to speed up this step `maxbin`? If not, how much time would it use to complete this step with 6 samples that are ~36GB compressed in total?

**Comment by jtamames** [comment] 2020-04-15 09:11
Hello!
I do not know of any way to speed maxbin further than what we are already doing. Whay you can do is to skip maxbin using the --nomaxbin flag, but in that way you will get just the Metabat2 bins. As I mentioned before, the upcoming 1.2 version of SqueezeMeta will allow you to include custom binning methods. We hope to release that one soon.
Best,
Javier

**Comment by bresyd** [comment] 2020-07-06 11:47
@jtamames is there any update on including custom binning methods now that the 1.2 version is available? I am asking because similar to what @nebfield reported, maxbin is taking a long time on my large dataset (11 days running now). So if there were alternative tools available (or maybe if I could import the results from using a different tool outside of SQM) I would love to give that a try.
Thanks in advance for your help

**Comment by jtamames** [comment] 2020-07-06 12:59
Hello
Yes, maxbin is slow. Sorry about that.
The custom binning methods will be released in the next 1.3 version, but we cannot assure when it will be released. The thing is that we changed the full binning part and that includes changes in the pipeline that could break compatibility with previous results. So we want to test this extensively. 
This said, it is pretty easy to cheat current version of SqueezeMeta to use a different binner instead of maxbin. I have a script running concoct. If you feel like trying it, I can pass it to you, given that you install concoct in your system. You would also need to do some changes to SqueezeMeta.pl. I will instruct you on doing this.
Best,
Javier

**Comment by bresyd** [comment] 2020-07-06 13:07
Hi Javier,

thanks for your reply. Yes, I would be happy to give concoct a try if you are willing to guide me through. Would it be possible that I use the output of my current SQM run and then continue at step 14 but using concoct instead of maxbin? But maybe it is best to first give this a try on the SQM test dataset (Hadza). I will install concoct now.

**Comment by jtamames** [comment] 2020-07-06 14:24
Ok, let's see if it works for you. Here I am sending to you the file `bin_concoct.pl`. The idea is to replace `14.bin_maxbin.pl` with this one. Since `SqueezeMeta.pl` will look for that file, perhaps the easier way is to rename this one (`bin_concoct.pl`) to `14.bin_maxbin.pl` (rename first the original `14.bin_maxbin.pl` to `14.bin_maxbin.pl.original` to avoid overwritting it). So we cheat SqueezeMeta to behave like it's running maxbin when it's running concoct instead. You can also change the value of the hash `%bindirs` in the `SqueezeMeta_conf.pl` file in your project dir, changing it from:
`%bindirs     = ("maxbin","$resultpath/maxbin","metabat2","$resultpath/metabat2");`
to
`%bindirs     = ("maxbin","$resultpath/concoct","metabat2","$resultpath/metabat2");`

This is just for clarity's sake, but if you keep it as it is, it will work fine. Simply remember that the results in the maxbin directory are these of concoct. And do not change the 'maxbin' key, since SqueezeMeta still does not know about concoct.

In the `bin_concoct.pl` file, the only thing you must change is line 28, variable `$concoctdir`, that you must set to your concoct installation directory. Also, get sure that `samtools` is accesible.

Then, run or restart from step 14, and we will see! Let me know the result, please

Best,
Javier

[bin_concoct.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4879464/bin_concoct.pl.gz)

**Comment by bresyd** [comment] 2020-07-06 15:37
Thanks a lot Javier. I followed your instructions and started a new test run now. If everything works on the test dataset, I would like to try it on my own data. There is one thing I was wondering: because my SQM run with maxbin is still running, is there a possibility to keep the original script running (maybe maxbin finishes some time in the near future), but at the same time do a restart from step 14 using the concoct script? Could I maybe first make a copy of the output directory and then do the restart using concoct in the copy of the output dir?

**Comment by jtamames** [comment] 2020-07-06 16:09
Hello
I you want to keep maxbin running, then don´t do restart. Just run the bin_concoct script changing the bindirs hash to concoct, as said above. In that way you would have maxbin, metabat and concoct directories, and we will run dastool with the three of them. Tell me when you have the three results.

best,

**Comment by bresyd** [comment] 2020-07-07 10:17
Hi Javier,
I think I got the concoct script running (had to make some minor changes to the samtool lines). However, I noticed that once the script gets to the actual concoct step, it uses much more threads than specified. In my example,  `$numthreads         = 20;` in the SqueezeMeta_conf.pl file, but concoct at times used >100 cpus. Here is an example screenshot of the cpu usage
<img width="366" alt="concoct_issue" src="https://user-images.githubusercontent.com/58945730/86766878-6e126180-c04b-11ea-8fcd-4de5ca1ce2b3.PNG">

I ended up killing the script so that I don't interfere with other jobs running on the same cluster. Have you observed a similar behaviour when you run the script?

cheers

**Comment by jtamames** [comment] 2020-07-07 10:28
Hello
No, I didn´t notice. Also concoct is being run with the --threads option that should restrict cpu usage:
`$command="$concoctdir/bin/concoct --composition_file $choppedcontigs --coverage_file $bindir/coverage_table.tsv --threads $numthreads  -b $bindir/concoct_int/ > /dev/null 2>&1";`

Could you try replacing `--threads` in the line above (line 74 in the script) by `-t` and try again? Also, can you send me the syslogfile to inspect the actual command line?

Best,
Javier

**Comment by bresyd** [comment] 2020-07-07 12:50
Hi Javier,

I tried using `-t` instead of `--threads` but the issue remained.
In the syslog file everything is looking fine at least from what I can tell, here is the file (please only consider the last few lines for running concoct, I have been doing a few tests and the new lines always got appended to the syslog)
[syslog.concoct.txt](https://github.com/jtamames/SqueezeMeta/files/4884868/syslog.concoct.txt)

I was wondering if it could have something to do with the way I installed conconct. Because I don't have all the root privileges for a manual installation, I installed concoct via conda in the same environment I previously installed SqueezeMeta_1.2, which caused some packages to be removed/updated/downgraded, here are the details:

```
conda create -n SQM1.2_concoct -c bioconda -c fpusan squeezemeta
conda activate SqueezeMeta1.2_concoct
conda install -c defaults -c conda-forge -c bioconda concoct
The following NEW packages will be INSTALLED:

  biopython          pkgs/main/linux-64::biopython-1.77-py36h7b6447c_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  clang_variant      conda-forge/linux-64::clang_variant-1.0-default
  clangdev           conda-forge/linux-64::clangdev-5.0.0-h03006fd_1007
  concoct            bioconda/linux-64::concoct-1.1.0-py36hd17fb83_1
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.1-217
  joblib             pkgs/main/noarch::joblib-0.15.1-py_0
  mkl                pkgs/main/linux-64::mkl-2020.1-217
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py36he904b0f_0
  nose               pkgs/main/linux-64::nose-1.3.7-py36_2
  openmp             conda-forge/linux-64::openmp-5.0.0-0
  samtools           bioconda/linux-64::samtools-1.9-h8571acd_11
  scikit-learn       pkgs/main/linux-64::scikit-learn-0.23.1-py36h423224d_0
  threadpoolctl      pkgs/main/noarch::threadpoolctl-2.1.0-pyh5ca1d4c_0

The following packages will be REMOVED:

  libopenblas-0.3.10-h5ec1e0e_0
  llvm-openmp-10.0.0-hc9558a2_0

The following packages will be UPDATED:

  _openmp_mutex                                  4.5-1_llvm --> 4.5-0_gnu
  ca-certificates    conda-forge::ca-certificates-2020.6.2~ --> pkgs/main::ca-certificates-2020.6.24-0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            conda-forge::certifi-2020.6.20-py36h9~ --> pkgs/main::certifi-2020.6.20-py36_0
  openssl            conda-forge::openssl-1.1.1g-h516909a_0 --> pkgs/main::openssl-1.1.1g-h7b6447c_0

The following packages will be DOWNGRADED:

  libblas                                 3.8.0-17_openblas --> 3.8.0-16_mkl
  libcblas                                3.8.0-17_openblas --> 3.8.0-16_mkl
  liblapack                               3.8.0-17_openblas --> 3.8.0-16_mkl

```
Following this installation, I ran SqueezeMeta on the test dataset and everything finished without error.

Also, here is the 14.bin_maxbin.pl script using concoct, including some minor changes I had to make (path for concoct scripts and samtools commands)

[14.bin_maxbin_edited.pl.gz](https://github.com/jtamames/SqueezeMeta/files/4884919/14.bin_maxbin_edited.pl.gz)

Thanks again for your help

**Comment by fpusan** [comment] 2020-07-07 13:42
Hi!

Concoct uses numpy, which disregards python multiprocessing behaviour when calling external libraries for heavyweight calculations (i found a similar problem when running SparCC, for example).

Try setting up some environmental variables as described in:

https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy

And let me know if it solves the problem.

**Comment by bresyd** [comment] 2020-07-07 15:07
Hi,
thanks for this advice.

I included the following lines in my .bash_profile
```
export OMP_NUM_THREADS=20
export OPENBLAS_NUM_THREADS=20 
export MKL_NUM_THREADS=20
export VECLIB_MAXIMUM_THREADS=20
export NUMEXPR_NUM_THREADS=20
```
activated the changes with `source .bash_profile`
confirmed with
```
echo $OPENBLAS_NUM_THREADS
20
```
and ran the script again with `14.bin_maxbin.pl Hadza_1.2` but unfortunately concoct still uses more than the specified 20 threads.

Any other ideas?

Thanks again

**Comment by fpusan** [comment] 2020-07-07 16:11
Nevermind, it's actually not related to numpy, as they have custom C code to run their stuff

https://github.com/BinPro/CONCOCT/blob/develop/c-concoct/c_vbgmm_fit.c

Btw you said that you wanted to use only 20 threads, but from the `syslog.concoct.txt` file you sent us before it seems like everything is using 50 threads 

```

Run started Mon Jul  6 10:10:21 2020 in coassembly mode
Command: /home/btschits/miniconda3/envs/SqueezeMeta1.2/bin/SqueezeMeta.pl -m coassembly -p Hadza_1.2 -s test.samples -f raw --D --euk -t 50
Project: Hadza_1.2
Map file: test.samples
Fastq directory: /scratch/btschits/squeezemeta/test/raw
Options: threads=50; contiglen=200; assembler=megahit; mapper=bowtie; evalue=; miniden=; COGS; KEGG; PFAM; EXT_DB: /scratch/btschits/squeezemeta/test; EUKNOFILTER; DOUBLEPASS;
```

Is this fine?

**Comment by fpusan** [comment] 2020-07-07 16:17
Can you post the output of this command?

```
/home/btschits/miniconda3/envs/SQM1.2_concoct/bin/concoct --composition_file /scratch/btschits/squeezemeta/test/Hadza_1.2/temp/Hadza_1.2.choppedcontigs.fasta --coverage_file /scratch/btschits/squeezemeta/test/Hadza_1.2/results/concoct/coverage_table.tsv -t 20  -b /scratch/btschits/squeezemeta/test/Hadza_1.2/results/concoct/concoct_int/ 
```

As per https://github.com/BinPro/CONCOCT/blob/823dcd670bc42f6ea4622881c2484cda6c253a76/c-concoct/c_vbgmm_fit.c#L75, the C code should print how many threads it thinks it's using. If the number is 20 but you still get a higher thread usage in practice, then I'd say that the problem is related to the OMP library.

**Comment by bresyd** [comment] 2020-07-07 16:32
Thanks again for your help

```
/home/btschits/miniconda3/envs/SQM1.2_concoct/bin/concoct --composition_file /scratch/btschits/squeezemeta/test/Hadza_1.2/temp/Hadza_1.2.choppedcontigs.fasta --coverage_file /scratch/btschits/squeezemeta/test/Hadza_1.2/results/concoct/coverage_table.tsv -t 20  -b /scratch/btschits/squeezemeta/test/Hadza_1.2/results/concoct/concoct_int/ 
Up and running. Check /scratch/btschits/squeezemeta/test/Hadza_1.2/results/concoct/concoct_int/log.txt for progress
43389 1356 20
Setting 20 OMP threads
Generate input data
0,-2383049.642894,66716.151994
1,-2327288.088685,55761.554209
2,-2276723.643031,50564.445654
3,-2234389.667206,42333.975824
4,-2191821.699222,42567.967984
```
but using top I saw that it was still using many more threads 
<img width="367" alt="concoct_issue_2" src="https://user-images.githubusercontent.com/58945730/86813040-fca0d600-c07f-11ea-8f1e-e867d5a712e4.PNG">

so I killed the job after a few seconds.

**Comment by fpusan** [comment] 2020-07-07 16:44
So the issue seems to be related to the OMP library...

I'm not that familiar with it and at this point it might be a better idea to report the issue to the Concoct guys.

Maybe you can also try with the `OMP_THREAD_LIMIT` environmental variable (the other link mentioned `OMP_NUM_THREADS`, but now I found this one at https://stackoverflow.com/questions/37391492/openmp-creates-too-many-threads).

Maybe you could also manually limit CPU usage wiht `cpulimit` (http://manpages.ubuntu.com/manpages/xenial/man1/cpulimit.1.html) but ofc ideally you'd like the process to control its CPU usage by itself.

**Comment by fpusan** [comment] 2020-07-07 17:08
Will look into it!

**Comment by bresyd** [comment] 2020-07-08 13:08
Setting `OMP_THREAD_LIMIT` worked! I set `export OMP_THREAD_LIMIT=20` before running the concoct version of `14.bin_maxbin.pl Hadza_1.2` and concoct never used more than 15 threads. So it did not make use of the 20 possible cpus, but at least it also did not use more than that. Thank you again @fpusan for your help with this.

@jtamames the concoct version of `14.bin_maxbin.pl` ran successfully on the test dataset. I am currently trying to combine the concoct and the metabat bins using `restart.pl Hadza_1.2 -step 16` with the bin directories in `SqueezeMeta_conf.pl` set to `%bindirs     = ("maxbin","$resultpath/concoct","metabat2","$resultpath/metabat2");  #-- Directories for bins` so that it is working on the concoct and the metabat2 output. So far it is looking good, at the moment it is at step 18 (checkM). 
You mentioned that we could now also combine the output of all three binning tools (maxbin, concoct and metabat). How would I do that.

For the SQM run with my own data, which is still running maxbin, I would now like to also do the binning using concoct, while maxbin keeps running. You mentioned earlier that I just need to change the %bindirs to concoct and then run the concoct version of 14.bin_maxbin.pl; what I was wondering is if I might run into a problem with the current maxbin binning when I change the %bindirs to `%bindirs     = ("maxbin","$resultpath/concoct","metabat2","$resultpath/metabat2")`? Or will changing the bindirs not affect the already running maxbin binning?

**Comment by jtamames** [comment] 2020-07-08 13:25
Hello
So nice to hear that! 
For your run, the running maxbin will be unaffected by the change in `%bindirs`. But DAS_Tool in step 16 will. So if you want to merge maxbin and metabat when the first is finished, you should revert `%bindirs` to its original value

For merging the three binning results with DAS_TOOL, you simply should change`%bindirs` to:
`%bindirs = ("maxbin","$resultpath/maxbin","metabat2","$resultpath/metabat2","concoct","$resultpath/concoct")`
That should be enough. Then, restart in step 16.

Best,
Javier

**Comment by fpusan** [comment] 2020-07-08 13:57
Glad to hear CPU usage is under control again! I'll let the concoct devs know about the issue and the workaround.

**Comment by bresyd** [comment] 2020-07-13 10:39
@jtamames I managed to run concoct instead of maxbin on my own large dataset, and then finish the pipeline (including metabat and DAStool); regarding runtime, concoct finished within a few hours whereas the initial binning with maxbin is still running after more than 2 weeks runtime; so in regard to runtime concoct is a great improvement. The number of bins created by concoct is only 387 compared to a staggering 2082 bins created by metabat; after DAStool the number of bins was further reduced to 354. I need to look into these results in more detail to figure out why the number of bins was reduced by such a large extend with DAS tool. 

I am still curious to find out how many bins I will get with maxbin should the run ever finish. I wanted to ask if there is a way to make the currently running SqueezeMeta.pl script stop automatically once it finishes maxbin? This is because I already ran metabat and also already have a DAS result directory. So I will need to rename some of my current result files and the DAS directory (and also some files in the intermediate directory) before I restart the scrip at step 16, combining the maxbin, concoct and metabat binnings. 

Cheers

**Comment by jtamames** [comment] 2020-07-13 11:14
Hello
Very nice to hear that! Metabat is usually producing lots of bins because it takes care of having the less contaminated bins as possible, therefore it doesn't merge bins unless it is very sure of it. As a result, parts of the same genome are scattered in different bins.
Notice that DAS Tool does not merge bins, it just carves out parts of the existing ones attempting to reduce contamination represented by duplicated gene markers. Therefore, the number of bins should not be inferior to the lower of the initial binning results. In your case it is because we set a threshold excluding small bins (rather, those with completeness<0.25). You can adjust this behaviour changing the `$score_tres16` variable in the file `parameters.txt`.

Also, rename your current files and directories as you say, because the running SqueezeMeta process will overwrite them. What you can do for making the process to stop without going any further if to edit the file 15.bin_metabat2.pl, which will be next after finishing maxbin, and place a `die` statement at the very beginning of the script. In that way it will die before creating any mess. Don't forget to remove it later for your next run.

Best,
Javier

**Comment by bresyd** [comment] 2020-07-21 09:22
Hi Javier,
apologize for my late reply to your last comment. But here is an update about what has happend.

- I changed the `$score_tres16` variable and as you suggested, I am now getting significantly more bins out of DAS tool. So that is great.
- the maxbin step finished successfully after 24 days!!! So patience is key with maxbin on large datasets. I now have the binning output of maxbin, metabat and concoct for my dataset and merged all three of them with DAS tool. To give you an idea: I got 1554 bins with maxbin, 2096 with metabat2 and 387 with concoct. When I previously combined the metabat and concoct bins with DAS tool, I ended up with 1616 bins. Now combining all three binning outputs, I get 2402 bins. Only from these numbers, I think it was well worth waiting for maxbin to finish. 

Since I also managed to sort out my SQMtool issues with the help of Fernando ( #128) I can finally start exploring my data!

Thanks again for your help,

cheers

benni

**Comment by jtamames** [comment] 2020-07-21 19:58
Hello
That is great to hear! Now you have bins to curate for the rest of your life lol
Best,
Javier

**Comment by biobrad** [comment] 2020-07-31 22:36
> 
> 
> Hi,
> 
> I'm running SqueezeMeta in co-assembly mode and MaxBin has been using 100% of 1 CPU for about a week, despite `-threads` being set to 24.
> 
> My data are quite large: around 15 samples and 175GB compressed of non-human reads (high sequencing depth). Co-assembly and mapping took around a week to complete.
> 
> There may be nothing I can do but wait, but I was wondering is there anything I can do to speed up the process or see how far binning has gotten. Also, is this a common problem with big metagenomic datasets?
> 
> Thanks

ha, i was about to come here and mention the same thing. 

    PID USER              PR  NI    VIRT    RES    SHR    S   %CPU  %MEM     TIME+ COMMAND
1736756 harbj019  20   0 4137312   3.7g   3468 S 145.5   5.9   1481:16 MaxBin <<<<<<<<< HURRY UP MAXBIN YOU IDIOT

#-- Options
$numthreads         = 24;
$mincontiglen       = 200;
$assembler          = "megahit";
$canumem            = NF;
$opt_db             = "/home/harbj019/results/metagenomics/squeezemeta";

**Comment by jtamames** [comment] 2020-08-03 10:02
Hello
Yes, maxbin can be a pain for big datasets. We will release asap a new version including custom selection of binning methods. This will be a major rearrangenemt of the pipeline, this is why we want to test it carefully. In the meantime, the user in this thread managed to run concoct to replace maxbin with concoct (well, at the end he managed to run and combine all three, metabat, maxbin and concoct). If you want to try that way I will be happy to help if you need it.
Best,
Javier

**Comment by fpusan** [comment] 2020-09-08 09:28
Closing due to lack of activity

**Closed by fpusan** 2020-09-08 09:28 UTC
Labels: Binning, Maxbin2

**Comment by Shellfishgene** [comment] 2021-02-10 16:19
I also tried this, however it seems samtools is now a different version, and the `sort` command does not work anymore. Line 53 in the concoct script above needs to include `-o`, and `.bam`.
```
$command="samtools sort $bamfile -o $sorted.bam -\@$numthreads > /dev/null 2>&1";
```

**Comment by jtamames** [comment] 2021-02-11 09:44
Thank you very much for the warning, I will change the script accordingly.
Best,
