### ISSUE TITLE
error at step 1.5

### ISSUE THREAD

**Issue by jjgonzalezplaza** [jtamames/SqueezeMeta#153] opened 2020-09-03 11:03 UTC
Hi Jaime,

I have been using SqueezeMeta to carry out an assembly of metagenomes. The assembly seems to work until Megahit, but in step 1.5 tends to crash. I have tried to restart a few times but it seems to take too much time. I saw a different alternative for using seqmerge, but it crashes as well (and quite fast).

Could you help me with it?

I'm running:

perl /home/termite/.conda/envs/SqueezeMeta/bin/01.merge_sequential.pl IGA_Tr2

  Starting assembly merge
Error running command:    /home/termite/.conda/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/kmerdist.pl IGA_Tr2 1 >> /media/termite/TRT_Server31/Iga/Tr/IGA_Tr2/syslog 2>&1 at /home/termite/.conda/envs/SqueezeMeta/bin/01.merge_sequential.pl line 56.

Thanks in advance.

**Comment by jtamames** [comment] 2020-09-03 12:02
Hello!
Could you please send us the `syslog` file that you will find in the project directory? I would like to have both, for the merge and seqmerge runs.
Best,
Javier

**Comment by jjgonzalezplaza** [comment] 2020-09-04 13:01
Hi,

These are the two syslog files that I have. I include my list file (the .txt was only to be able to upload here). Would it be a problem that I was trying to have all "orphans" for the merged assembly?
[Tr2_list.list.txt](https://github.com/jtamames/SqueezeMeta/files/5174914/Tr2_list.list.txt)
[Cf_list.list.txt](https://github.com/jtamames/SqueezeMeta/files/5174916/Cf_list.list.txt)


I could only find for each location/project (Tr or Cf) one syslog.
[syslogTr.txt](https://github.com/jtamames/SqueezeMeta/files/5174895/syslogTr.txt)
[syslogCf.txt](https://github.com/jtamames/SqueezeMeta/files/5174902/syslogCf.txt)

Thanks a lot.

**Comment by jtamames** [comment] 2020-09-08 10:38
Hello
The logs are a bit confusing, it seems that you started the project in merged mode but then tried to switch to seqmerge, this could cause problems. But anyway the potential issue is not that one, but a silly thing from our part: For merged and seqmerge modes, the input sequence filenames must end either with fastq, fasta, fq or fa (gzip is allowed, therefore fastq.gz, fasta.gz, fq.gz and fa.gz will work as well). I should have put a check in the code to look for this, and mentioned it in the manual. 
I cannot exclude the possibility that the issue is in some other place. The pipeline stops when either nucmer or kmer-db are called in the merge and seqmerge mode modes, respectively. I think this is because they cannot find their files because of the filename issue above, but it could be that they were not properly installed.
To check it, could you change your filenames removing the pe.1, pe.2 tails and run it again? Do it for a small dataset of two samples to quickly verify if it works.
Regarding your "orphans" files that only have one pair, it should not be a problem to mix them with the paired datasets, because the assembly is done independently for each dataset and then the resulting fasta are merged. It won't work, though, for the coassembly mode were all sets of pair1 and pair2 files are joined previous to the assembly.
Best,
Javier

**Comment by jjgonzalezplaza** [comment] 2020-09-08 14:24
OK. It could have been quite a beginner mistake from my side. I'm running it again with three biological replicates belonging to one sample type. Trying the merged mode.

**Comment by jjgonzalezplaza** [comment] 2020-09-10 09:42
This time it is still running without issues from step 1 to 1.5 (merging with minimus2). Previously it was always stopping in between and I had to restart. I will update as soon as it does any advance.

**Comment by jjgonzalezplaza** [comment] 2020-09-21 12:53
OK, it took 7 days to pass through step 1.5. It moved to step 2.

**Comment by jtamames** [comment] 2020-09-21 13:03
Glad to hear that! Now it will spend some time, especially in steps 4 (homology searching) , 6 (taxonomy annotation) , 10 (abundance mapping) and 15 (maxbin binning). Once you pass step 13, you can start looking at your results in table 13.orftable.

Best, 
Javier

**Comment by yjiakang** [comment] 2020-10-13 06:33
Hello, I have thirty-six paired-end samples, the step 1.5 now runs to merge 23. And this took a long time (~50 days). I run this with 36 threads and 100Gb RAM. Now each merge takes longer and longer time, is there any way for speeding thiss step? Thanks for help.
Best
jk yin

**Comment by jtamames** [comment] 2020-10-13 07:20
Hello
It makes sense that it is taking longer, as merged sets are getting bigger. Unfortunately this step is dependent of minimus2 that is slower than it should. According to what you say, we have to think in an alternative. I am very sorry for this
Best,

**Comment by fpusan** [comment] 2020-10-13 08:41
Hi!
What kind of results would you need in the end? If you are interested mostly in taxonomic/functional profiles, an alternative would be to run each sample independently (or in smaller groups) and then combine the results with SQMtools.
Let us know if that would be ok for you, and we can instruct you on how to get there as fast as possible.

**Comment by yjiakang** [comment] 2020-10-14 07:02
@fpusan Yes, it would be nice to instruct me to get the taxonomic and functional profiles. And I want to do statistical test between my treatment and control samples to get the different taxa and functions. Thanks.

**Comment by jtamames** [comment] 2020-10-15 17:08
For running the sequential analysis of the metagenomes using the assemblies that you already have, first you must create an individual sample file for each metagenome you have already assembled, like:

```
sample1        file1.fastq        pair1
sample1        file2.fastq        pair2
```

then you can create a shell script with the succesive SqueezeMeta commands using each of the sample files and the existing assembly, something like:

```
/path/to/SqueezeMeta/scripts/SqueezeMeta.pl -m sequential -s sample1.samples -f /path/to/seqfiles -extassembly /path/to/assembly1
/path/to/SqueezeMeta/scripts/SqueezeMeta.pl -m sequential -s sample2.samples -f /path/to/seqfiles -extassembly /path/to/assembly2
```
and so on, replacing` /path/to/assembly` with the location of your assemblies. Then save this file as `run.sh` or the name you want, give execution permissions to it, and run it. You will produce sequential analyses for all your samples.

Best,
Javier

**Comment by fpusan** [comment] 2020-10-16 08:19
@yjiakang let me know when you've finished running your samples in the sequential mode, and we'll work out how to combine the results.

**Comment by yjiakang** [comment] 2020-10-18 02:35
@fpusan Would this alternative produce similar results that were similar with your common pipeline? For example, can I get a result that I can find the statistically different functions and their corresponding contribution bins? By the way, the minimus has run to step 24, and it corrupted due to limited RAM, should I continue to run it by applying for more RAM?

**Comment by fpusan** [comment] 2020-10-26 14:11
Hi, and sorry for the late answer. In our experience, functional and taxonomic profiles will be mostly similar, particularly for the most abundant functions/taxa.
Regarding the minimus2 run, you will not need it if you are running everything using the sequential mode.

**Comment by yjiakang** [comment] 2020-11-02 01:22
> For running the sequential analysis of the metagenomes using the assemblies that you already have, first you must create an individual sample file for each metagenome you have already assembled, like:
> 
> ```
> sample1        file1.fastq        pair1
> sample1        file2.fastq        pair2
> ```
> 
> then you can create a shell script with the succesive SqueezeMeta commands using each of the sample files and the existing assembly, something like:
> 
> ```
> /path/to/SqueezeMeta/scripts/SqueezeMeta.pl -m sequential -s sample1.samples -f /path/to/seqfiles -extassembly /path/to/assembly1
> /path/to/SqueezeMeta/scripts/SqueezeMeta.pl -m sequential -s sample2.samples -f /path/to/seqfiles -extassembly /path/to/assembly2
> ```
> 
> and so on, replacing` /path/to/assembly` with the location of your assemblies. Then save this file as `run.sh` or the name you want, give execution permissions to it, and run it. You will produce sequential analyses for all your samples.
> 
> Best,
> Javier

I performed analysis as you suggested above, and everything run smoothly till step 10; Here is my script and the stdout and stderr files. I guess the reason is that my raw reads is fasta format.

[scirpts_stdout_stderr.zip](https://github.com/jtamames/SqueezeMeta/files/5472276/scirpts_stdout_stderr.zip)

**Comment by jtamames** [comment] 2020-11-03 16:52
Hello

No problem with the reads in fasta format, that should work
Could you send me the syslog file?
Also, could you check that you have sam files in the directory `/path/to/project/data/sam`? Check the size with `ls -l`

Best,
Javier

**Comment by yjiakang** [comment] 2020-11-04 01:24
Hi, here is the syslog file, and there is one file in the */data/sam directory.
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/5484970/syslog.zip)

```
(base) [jkyin@mn02 sam]$ pwd
/public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/data/sam
(base) [jkyin@mn02 sam]$ ll -h
total 48M
-rw-r--r-- 1 jkyin LFRuan 48M Nov  1 12:31 A57RS1T1.A57RS1T1.sam
```

**Comment by jtamames** [comment] 2020-11-04 10:34
Hello

That sam is very small indeed. It is likely that there was some problem with the bowtie alignment and it didn't align anything. To check it, run `wc /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/data/sam/A57RS1T1.A57RS1T1.sam`. If the number is similar to the number of contigs, that's it, you have no reads in the sam file.

Then, check that you have the files `/public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/temp/A57RS1T1.A57RS1T1.current_1` and` /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/temp/A57RS1T1.A57RS1T1.current_2`. 

If you don't, then run `cat /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/data/raw_fastq/A57RS1T1_1.fa > /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/temp/A57RS1T1.A57RS1T1.current_1; cat /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/data/raw_fastq/A57RS1T1_2.fa > /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/temp/A57RS1T1.A57RS1T1.current_2;`


Then, try to run the command manually: `/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/bowtie2/bowtie2 -x /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/data/A57RS1T1.bowtie  -1 /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/temp/A57RS1T1.A57RS1T1.current_1 -2 /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/temp/A57RS1T1.A57RS1T1.current_2 --quiet -p 12 -S /public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/A57RS1T1/data/sam/A57RS1T1.A57RS1T1.sam`

and please tell me the results

**Comment by jtamames** [comment] 2020-11-04 10:41
Oh wait... You were probably rigth and this is related to the fasta files.

Forget all of the above :) Instead do this:
Edit the file `SqueezeMeta/scripts/10.mapsamples.pl`

Then, in line 118, replace:

`if($ifile=~/fasta/) { $formatseq="fasta"; }`
by
`if($ifile=~/fasta|fa$/) { $formatseq="fasta"; }`

and rerun that 10 script. That will surely fix the error.
Best,
Javier

**Comment by yjiakang** [comment] 2020-11-09 00:44
Yes, thanks. It works.
Now all of the 36 samples have successfully completed. Could you help me to integrate the results and to perform some comparisons between my groups? Thanks in advance.

**Comment by fpusan** [comment] 2020-11-10 09:07
Hi,
In order to combine the results, it's better if you update to version 1.3.
If you already loaded any of the projects in SQMtools, please remove the `/path/to/project/results/tables` directory, as it will need to be re-created using the new version.
Then go into R and try the following
```
library(SQMtools)
samples = c('/path/to/project1', '/path/to/project2', ...) # This should be a vector with the path of the different SQM projects you just generated.
SQMobjs = lapply(samples, FUN=loadSQM) # This will contain one SQMobject for each of your samples
SQMcomb = do.call(combineSQMlite, SQMobjs) # This will contain a single SQMlite object with the integrated taxonomic and functional profiles
```

You can explore the `SQMcomb` object with the `plotTaxonomy` and `plotFunctions` functions in order to check that everything looks ok. Please check the [wiki] (https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results), there you will find a lot of examples on how to analyze your data, including how to perform comparisons between groups.
Best,
Fernando

**Comment by yjiakang** [comment] 2020-11-14 12:11
Many thanks! By the way, is it possible to integrate all the results into anvi'o or itol? Because I intend to present  which bin contributes which function intuitively. 
Best,
Jk Yin

**Comment by fpusan** [comment] 2020-11-16 09:44
Hi,
The approach you followed is good for functional / taxonomic profiles, but I don't think it's the best for binning.
In order to get the best results out of binning you should analyse all your samples in the same project, using the coassembly or seqmerge modes. The sequential mode performs binning (and everything else) individually for each sample, and I would not put the same level of trust on those binning results.

**Comment by jtamames** [comment] 2020-11-16 09:54
Hello
As Fernando said, you probably have a different set of bins for each sample, and it is not straightforward to identify which bins are the same in the different samples. I am testing the software [drep](https://github.com/MrOlm/drep) for that purpose. It attempts to identify common bins between different binning results. Maybe you can give it a try, but this is currently not supported by the SqueezeMeta pipeline.
Best,
Javier

**Comment by yjiakang** [comment] 2020-11-17 08:28
Yeah, thanks for quick reply and trying to help. Actually, I tried the `merged` mode before, error occured at step 1.5. Then according to your team's advice, I performed step 1.5 using 01.mergee_sequential.pl`, but it runs very slowly (36 samples, run ~50 days,  merged 23. Threads: 60).

**Comment by jtamames** [comment] 2020-11-17 08:42
Hello
Yeah, it is slow, but maybe not that slow. I just run a merge_sequential of 7 big samples with 16 CPUs, and the merge took 3 days. Did you check your disk I/O usage?

**Comment by yjiakang** [comment] 2020-11-17 09:18
> Hi,
> In order to combine the results, it's better if you update to version 1.3.
> If you already loaded any of the projects in SQMtools, please remove the `/path/to/project/results/tables` directory, as it will need to be re-created using the new version.
> Then go into R and try the following
> 
> ```
> library(SQMtools)
> samples = c('/path/to/project1', '/path/to/project2', ...) # This should be a vector with the path of the different SQM projects you just generated.
> SQMobjs = lapply(samples, FUN=loadSQM) # This will contain one SQM object for each of your samples
> SQMcomb = do.call(combineSQMlite, SQMobjs) # This will contain a single SQMlite object with the integrated taxonomic and functional profiles
> ```
> 
> You can explore the `SQMcomb` object with the `plotTaxonomy` and `plotFunctions` functions in order to check that everything looks ok. Please check the [wiki](https://github.com/jtamames/SqueezeMeta/wiki/Using-R-to-analyze-your-SQM-results), there you will find a lot of examples on how to analyze your data, including how to perform comparisons between groups.
> Best,
> Fernando

When I tried to loadSQM, I was stuck at the first step.
```
> test <- loadSQM("A57RS1T1")
Error in loadSQM("A57RS1T1") : 
  Directory "A57RS1T1" does not seem to contain a valid SqueezeMeta project

test <- loadSQMlite("A57RS1T1/")
Loading taxonomies
Error in loadSQMlite("A57RS1T1/") : 
  Directory "A57RS1T1/" does not seem to contain valid SqueezeMeta tables
```
The directory contents of  A57RS1T1 are as follows:
```

(base) yjk@DESKTOP-U8UULFU:/mnt/d/phd/tomato_micr/meta/SqueezeMeta/A57RS1T1$ tree -L 2
.
├── 19.A57RS1T1.contigsinbins
└── results
    ├── 01.A57RS1T1.fasta
    ├── 02.A57RS1T1.16S.txt
    ├── 02.A57RS1T1.rnas
    ├── 02.A57RS1T1.trnas
    ├── 02.A57RS1T1.trnas.fasta
    ├── 03.A57RS1T1.faa
    ├── 03.A57RS1T1.fna
    ├── 03.A57RS1T1.gff
    ├── 06.A57RS1T1.fun3.tax.noidfilter.wranks
    ├── 06.A57RS1T1.fun3.tax.wranks
    ├── 07.A57RS1T1.fun3.cog
    ├── 07.A57RS1T1.fun3.kegg
    ├── 07.A57RS1T1.fun3.pfam
    ├── 10.A57RS1T1.mappingstat
    ├── 11.A57RS1T1.mcount
    ├── 12.A57RS1T1.cog.funcover
    ├── 12.A57RS1T1.kegg.funcover
    ├── 13.A57RS1T1.orftable
    ├── 19.A57RS1T1.bintable
    ├── 20.A57RS1T1.contigtable
    ├── 21.A57RS1T1.kegg.pathways
    ├── 21.A57RS1T1.metacyc.pathways
    ├── 22.A57RS1T1.stats
    ├── DAS
    ├── maxbin
    └── metabat2
```
By the way, the top 10 merge is very fast, and the `merged_24.four_cultivars.fasta` is 14G.

**Comment by fpusan** [comment] 2020-11-17 09:20
Hi,
Indeed, this is not an original project directory, since you don't have all the required files. Did you move the files from somewhere else?

**Comment by yjiakang** [comment] 2020-11-17 09:32
No, I retained  all the original result files. Because I want to perform analysis on my own computer rather than the hpc in my university for convenience. From previous issues, I find that only intermediate/*contigsinbins  and results/ are needed for analysis. So I just downloaded those files mentioned above.
What's more, I tried in the hpc just now, error occurred as well.
```
> setwd("/public/home/jkyin/yjk/tomato_micro/sqm_one_by_one/script/")
> test <- loadSQM("A57RS1T1")
Generating tabular outputs for project in A57RS1T1
Traceback (most recent call last):
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 195, in <module>
    main(parse_args())
  File "/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/utils/sqm2tables.py", line 58, in main
    total_reads, total_bases = parse_mappingstat(perlVars['$mappingstat'])
KeyError: '$mappingstat'
Error in loadSQM("A57RS1T1") :
  An error occurred while running sqm2tables.py
> test <- loadSQMlite("A57RS1T1")
Loading taxonomies
Error in loadSQMlite("A57RS1T1") :
  Directory "A57RS1T1" does not seem to contain valid SqueezeMeta tables
```
Here are all the files in the project `A57RS1T1`
```
(base) [jkyin@mn02 A57RS1T1]$ tree -L 2
.
├── data
│   ├── 00.A57RS1T1.samples
│   ├── checkm_markers
│   ├── raw_fastq
│   └── sam
├── ext_tables
│   ├── 12.A57RS1T1.cog.stamp
│   └── 12.A57RS1T1.kegg.stamp
├── intermediate
│   ├── 01.A57RS1T1.lon
│   ├── 01.A57RS1T1.stats
│   ├── 02.A57RS1T1.maskedrna.fasta
│   ├── 04.A57RS1T1.eggnog.diamond
│   ├── 04.A57RS1T1.kegg.diamond
│   ├── 04.A57RS1T1.nr.diamond
│   ├── 05.A57RS1T1.pfam.hmm
│   ├── 09.A57RS1T1.contiglog
│   ├── 10.A57RS1T1.contigcov
│   ├── 10.A57RS1T1.mapcount
│   ├── 17.A57RS1T1.bintax
│   ├── 18.A57RS1T1.DASTool.checkM
│   ├── 19.A57RS1T1.bincov
│   └── 19.A57RS1T1.contigsinbins
├── methods.txt
├── parameters.pl
├── progress
├── results
│   ├── 01.A57RS1T1.fasta
│   ├── 02.A57RS1T1.16S.txt
│   ├── 02.A57RS1T1.rnas
│   ├── 02.A57RS1T1.trnas
│   ├── 02.A57RS1T1.trnas.fasta
│   ├── 03.A57RS1T1.faa
│   ├── 03.A57RS1T1.fna
│   ├── 03.A57RS1T1.gff
│   ├── 06.A57RS1T1.fun3.tax.noidfilter.wranks
│   ├── 06.A57RS1T1.fun3.tax.wranks
│   ├── 07.A57RS1T1.fun3.cog
│   ├── 07.A57RS1T1.fun3.kegg
│   ├── 07.A57RS1T1.fun3.pfam
│   ├── 10.A57RS1T1.mappingstat
│   ├── 11.A57RS1T1.mcount
│   ├── 12.A57RS1T1.cog.funcover
│   ├── 12.A57RS1T1.kegg.funcover
│   ├── 13.A57RS1T1.orftable
│   ├── 19.A57RS1T1.bintable
│   ├── 20.A57RS1T1.contigtable
│   ├── 21.A57RS1T1.kegg.pathways
│   ├── 21.A57RS1T1.metacyc.pathways
│   ├── 22.A57RS1T1.stats
│   ├── DAS
│   ├── maxbin
│   ├── metabat2
│   └── tables
├── SqueezeMeta_conf.pl
├── syslog
└── temp
```

**Comment by fpusan** [comment] 2020-11-17 09:34
You will need at least the `contigsinbins` file (but inside the `intermediate` directory, not in the base directory) and the `SqueezeMeta_conf.pl` file (in the base directory).

**Comment by yjiakang** [comment] 2020-11-17 14:09
As mentioned above, error occurred while running `sqm2tables.py` when running loadSQM function.  I have no idea what is wrong, hoping for your help.

**Comment by fpusan** [comment] 2020-11-17 14:14
Yes, but the first error is happening because you are missing the `SqueezeMeta_conf.pl` and the ` 19.A57RS1T1.contigsinbins` file is in not within the intermediate directory. It is fine if you want to copy part of the project to a different computer, but make sure to preserve the original directory structure. You can't expect things to work otherwise.

Regarding the error happening in your cluster, you are running the `loadSQMlite` function, which requires a tables directory, not a whole SqueezeMeta project directory. This is well documented, with examples, in the SQMtools manual. You can either run `loadSQM` over the whole project, or run `loadSQMlite` over the `results/tables` directory.

**Closed** 2021-01-11 11:41 UTC
Labels: Assembly, Configuration, merged mode, seqmerge mode
