### ISSUE TITLE
tRNA sequence missing in fasta files

### ISSUE THREAD

**Issue by mirimarine** [jtamames/SqueezeMeta#182] opened 2020-10-23 07:37 UTC
Hi,
After a successful SqueezeMeta run I wanted to import the project into R and stumbled across an error.
I used  sqm2tables.py and got the following error:

`Traceback (most recent call last):
File "/home/anaconda3/envs/SQM1.2/bin/sqm2tables.py", line 180, in <module>
main(parse_args())
File "/home/anaconda3/envs/SQM1.2/bin/sqm2tables.py", line 144, in main
write_orf_seqs(orfs['abundances'].keys(), perlVars['$aafile'], fna_blastx, perlVars['$rnafile'], perlVars['$trnafile'] + '.fasta', prefix + 'orf.sequences.tsv')
File "/home/anaconda3/envs/SQM1.2/SqueezeMeta/utils/../lib/utils.py", line 383, in write_orf_seqs
outfile.write('{}\t{}\n'.format(ORF, ORFseq[ORF]))
KeyError: 'megahit_61128_41033-41124'`

I then checked the results table of the sqm run. It seems that  'megahit_61128_41033-41124' is part of the following four tables:
02.msm89.trnas (megahit_61128_41033-41124       tRNA-Ser)
08.msm89.gff (megahit_61128   aragorn tRNA    41033   41124   -       +       .       ID=megahit_61128_41033-41124;Name=tRNA-Ser)
13.msm89.orftable (megahit_61128_41033-41124       megahit_61128   tRNA    Aragorn 92              0.00    tRNA-Ser                                                                        0.000   2.705   0.000   1.623   0.000   1.978      0.000   0.728   0       2       0       1       0       182     0       67      0)
20.msm89.contigtable (megahit_61128                   28.18   60176                   7.310   1747.600        35.500  89      3.810   966.100 26.000  52      3.120   1104.900        25.300  49      3.380   1141.800        27.100  58)

But I can't find any information on the tRNA or the contig in any of the other tables, e.g.:
02.msm89.rnas
02.msm89.fasta
03.msm89.fna
11.msm89.mcount

Please let me know if you need any additional information.

Cheers,
Miriam

**Comment by fpusan** [comment] 2020-10-23 08:17
Hi,
Thanks for the detailed report! What version of SqueezeMeta are you using? That bug (or at least _a_ bug causing the same behaviour) got corrected a while ago.
Can you send me your `sqm2tables.py` script so I can check the code?
Best,
Fernando

**Comment by mirimarine** [comment] 2020-10-23 08:38
Hi,
I'm using  SqueezeMeta version 1.2.
I installed it using conda. 

[sqm2tables.zip](https://github.com/jtamames/SqueezeMeta/files/5428260/sqm2tables.zip)

Cheers,
Miriam

**Comment by fpusan** [comment] 2020-10-23 08:58
The script seems to be ok.
Any chance you can share the whole project directory via google drive or something like that? I think that the `temp` and `data` subdirectories are not needed, that should make it a lot smaller.

**Comment by fpusan** [comment] 2020-10-29 09:41
Can reproduce

**Comment by fpusan** [comment] 2020-10-29 11:37
Apparently we've already fixed that in our development branch. Please try the following:

1) Download the development branch `conda create -n SqueezeMetaDev -c conda-forge -c bioconda -c fpusan squeezemeta-dev `
2) Edit the `SqueezeMeta_conf.pl` file inside your project's directory and make the following changes:
-- Change `$installpath`to the directory of your new SqueezeMeta installation
-- Add the following line `$mappingstat     = "$resultpath/10.$projectname.mappingstat";` below L66.
3) Within the `SqueezeMetaDev` conda environment, run `02.rnas.pl /path/to/your/project`.
4) Run `sqm2tables.py /path/to/your/project /path/to/your/project/results/tables --force-overwrite`.

Let me know if this works!

**Comment by mirimarine** [comment] 2020-10-29 14:52
Hi,
thanks for looking into this.
I followed your instructions and unfortunately got the following error for `02.rnas.pl`:
``` 
Running barrnap (Seeman 2014, Bioinformatics 30, 2068-9) for predicting RNAs:  Bacteria Archaea Eukaryote Mitochondrial
  Running RDP classifier (Wang et al 2007, Appl Environ Microbiol 73, 5261-7)
Error: Unable to access jarfile /home/mphilipp/anaconda3/envs/SqueezeMetaDev/SqueezeMeta/bin/classifier.jar
Error running command:    java -jar /home/mphilipp/anaconda3/envs/SqueezeMetaDev/SqueezeMeta/bin/classifier.jar classify /scratch/mphilipp/msm89/08_sqm/msm89_subreads_sqm/temp/16S.fasta -o /scratch/mphilipp/msm89/08_sqm/msm89_subreads_sqm/temp/16S.out -f filterbyconf at /home/mphilipp/anaconda3/envs/SqueezeMetaDev/bin/02.rnas.pl line 127.
```

**Comment by fpusan** [comment] 2020-10-29 14:54
My bad.
Run also `configure_nodb.pl /path/to/your/databases`

**Comment by mirimarine** [comment] 2020-10-29 15:58
Everything worked fine now and I got all the results tables for sqm_tools.
Thanks a lot for your help!
All the best,
Miriam

**Comment by fpusan** [comment] 2020-10-29 16:05
Glad to hear! Closing issue

**Closed by fpusan** 2020-10-29 16:05 UTC
Labels: RNA prediction, SQMtools
