### ISSUE TITLE
Coassembly mode crashing

### ISSUE THREAD

**Issue by analopezlopez** [jtamames/SqueezeMeta#509] opened 2022-06-25 11:43 UTC
Hi, 

I'm getting this error when trying to run the coassembly mode.

Run started Sat Jun 25 13:32:55 2022 in coassembly mode
Now creating directories
Reading configuration from /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/SqueezeMeta_conf.pl
Reading samples from /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/00.coassemblyflye_RUN6.samples
3 samples found: barcode03.run6 barcode02.run6 barcode01.run6

Now merging files
[0 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (flye)
  Running assembly with flye
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

Error running command:    /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/bin/Flye-2.9/bin/flye  -o /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/flye --plasmids --meta --genome-size 2.6g --threads 12 --nano-raw /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/raw_fastq/par1.fastq > /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/syslog 2>&1; mv /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/flye/assembly.fasta /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/flye/contigs.fasta at /domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.
Died at /home/analopez/.conda/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.

Could you give me a hint on what seems to be going wrong? Thanks!

**Comment by analopezlopez** [comment] 2022-06-25 12:03
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/8984646/syslog.zip)

**Comment by jtamames** [comment] 2022-06-27 12:14
Hello
I cannot open the zip file. Could you compress it with gzip instead?
Best,

**Comment by jtamames** [comment] 2022-06-27 16:50
Hello
The file is missing a lot of information, this must not be the real one.
Anyway, in the few lines that are in the file, I see the following:

[2022-06-25 13:32:57] WARNING: --plasmids mode is no longer available. Command line option will be removed in the future versions
[2022-06-25 13:32:57] ERROR: minimap2 is not installed
[2022-06-25 13:32:57] ERROR: Pipeline aborted

pointing to a likely installation error.
Did you try to run the failed command by itself? That could give you more information

`domus/h1/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/bin/Flye-2.9/bin/flye -o /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/flye --plasmids --meta --genome-size 2.6g --threads 12 --nano-raw /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/raw_fastq/par1.fastq`

**Comment by analopezlopez** [comment] 2022-06-28 12:21
Hi! 

This is what I get when I run the command:
(SqueezeMeta) [analopez@rackham2 SqueezeMeta]$ /home/analopez/.conda/envs/SqueezeMeta/SqueezeMeta/bin/Flye-2.9/bin/flye -o /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/flye --plasmids --meta --genome-size 2.6g --threads 12 --nano-raw /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/raw_fastq/par1.fastq
[2022-06-28 14:16:52] WARNING: --plasmids mode is no longer available. Command line option will be removed in the future versions
[2022-06-28 14:16:52] ERROR: minimap2 is not installed
[2022-06-28 14:16:52] ERROR: Pipeline aborted

I had to change the path into home/analopez/.conda for it to run, though. Otherwise it would complain about not finding the directory or file. I don't if that's relevant in any way...

Also, I deleted the Squeezemeta environment by mistake when I was trying upgrade to the new version a few months ago but I managed to install it again, although I haven't run a complete experiment since then. Could this be an issue?

**Comment by analopezlopez** [comment] 2022-07-01 07:38
Should I try to reinstall or modify any script manually? Thanks!

**Comment by analopezlopez** [comment] 2022-07-20 16:37
Hi! Sorry to bother you again. Did you have the chance to take a look at my previous message? Should I try to reinstall the software from scratch?

Thanks!

**Comment by fpusan** [comment] 2022-07-20 17:02
Sorry about that, the complaint about minimap is weird. Does it keep happening with a freshly installed environment?
What version of SqueezeMeta is this from?
As a patch you could also try to install minimap in your environment with `conda install -c bioconda minimap2`
Maybe that solves the issue, but it should not be happening in the first place. I will try to reproduce in the latest version of SQM.

**Comment by analopezlopez** [comment] 2022-07-20 17:34
Hi, thanks for your response!!!

I've just tried to reinstall minimap in my environment (it went OK) but then the pipeline stops at the same step displaying the same error:

[2022-07-20 19:22:51] WARNING: --plasmids mode is no longer available. Command line option will be removed in the future versions
[2022-07-20 19:22:51] ERROR: minimap2 is not installed
[2022-07-20 19:22:51] ERROR: Pipeline aborted
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
_____________

System information:
_____________

Tree for the project:
.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[4.0K Jul 20 19:22]  /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6
├── [4.0K Jul 20 19:22]  data
│   ├── [ 131 Jul 20 19:22]  00.coassemblyflye_RUN6.samples
│   ├── [4.0K Jul 20 19:22]  flye
│   │   └── [ 249 Jul 20 19:22]  flye.log
│   └── [4.0K Jul 20 19:22]  raw_fastq
│       ├── [3.6M Jul 20 19:22]  barcode01_merged.fastq
│       ├── [ 13M Jul 20 19:22]  barcode02_merged.fastq
│       ├── [ 18M Jul 20 19:22]  barcode03_merged.fastq
│       └── [ 35M Jul 20 19:22]  par1.fastq
├── [4.0K Jul 20 19:22]  ext_tables
├── [4.0K Jul 20 19:22]  intermediate
│   └── [4.0K Jul 20 19:22]  binners
├── [ 196 Jul 20 19:22]  methods.txt
├── [2.9K Jul 20 19:22]  parameters.pl
├── [  56 Jul 20 19:22]  progress
├── [4.0K Jul 20 19:22]  results
├── [8.1K Jul 20 19:22]  SqueezeMeta_conf.pl
├── [2.2K Jul 20 19:22]  syslog
└── [4.0K Jul 20 19:22]  temp

8 directories, 11 files

Run started Wed Jul 20 19:22:50 2022 in coassembly mode
Now creating directories
Reading configuration from /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/SqueezeMeta_conf.pl
Reading samples from /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/data/00.coassemblyflye_RUN6.samples
3 samples found: barcode03.run6 barcode02.run6 barcode01.run6

Now merging files
[1 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (flye)
  Running assembly with flye
Stopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally

I'm using SqueezeMeta v1.5.0. 

I was trying to avoid reinstalling the whole environment again but maybe it's for the best. Silly question, though: should I delete the old environment before installing the new one or does it automatically overwrites the old one?

Thanks!

**Comment by fpusan** [comment] 2022-07-20 17:53
It should overwrite the old one.
I just tried in my workstation and flye was working fine.
Anyways since I have access to uppmax I will try to also test it there.

**Comment by analopezlopez** [comment] 2022-07-20 18:41
Ok, so I installed a fresh environment and, since the databases are in a different directory, I configured it with /path/to/SqueezeMeta/utils/install_utils/configure_nodb.pl /path/to/db

Everything seemed to be working fine but when I run `test_install.pl` it says:
Checking that SqueezeMeta is properly configured... checking database in /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases
	SqueezeMeta_conf.pl says that databases are located in /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases but we can't find nr.db there, or it is corrupted

Does this mean I have to download the databases again?

**Comment by fpusan** [comment] 2022-07-20 19:02
Try with 

`configure_nodb.pl /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db`

**Comment by analopezlopez** [comment] 2022-07-20 19:36
It worked, thank you so much! 

I'm trying to run Flye now, I'll let you know.

**Comment by analopezlopez** [comment] 2022-07-20 20:07
It seems now it's stopping at step 2. 

[21:58:03] Can't find database: /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db/bac.hmm
Error running command:    /domus/h1/analopez/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/barrnap --quiet --threads 12 --kingdom bac --reject 0.1 /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/intermediate/02.coassemblyflye_RUN6.maskedrna.fasta --dbdir /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db > /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/coassembly_mode/coassemblyflye_RUN6/temp/bac.gff at /domus/h1/analopez/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/02.rnas.pl line 54.
Died at /home/analopez/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1381.

There's another database missing, apparently?

**Comment by fpusan** [comment] 2022-07-20 21:40
Your db may be corrupted then.
Can you do `ls /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db/` and paste it here?

**Comment by analopezlopez** [comment] 2022-07-21 07:17
Sure, here it is:

(base) [analopez@rackham3 AnaLopez]$ ls /crex/proj/snic2020-6-60/AnaLopez/squeezemeta/data_bases/db/
eggnog.dmnd  LCA_tax  nr.dmnd  nr.faa  nr.md5  Pfam-A.hmm

**Comment by fpusan** [comment] 2022-07-21 13:47
Ok, the directory is incomplete so it is better to remove it and run `download_databases.pl` again

**Comment by analopezlopez** [comment] 2022-07-22 07:34
I just wanted to let you know that I finally managed to run the coassembly mode. It must have been something related to the old environment because with the fresh installation and downloading again the databases, it finally worked. 

Thank you very much for the support! Much appreciated. 

Best, 
Ana

**Comment by fpusan** [comment] 2022-08-01 11:33
Glad to hear! Closing issue

**Closed by fpusan** 2022-08-01 11:33 UTC
