### ISSUE TITLE
Error with SqueezeMeta STEP 1

### ISSUE THREAD

**Issue by avinashDhar1993** [jtamames/SqueezeMeta#674] opened 2023-04-25 18:04 UTC
Hi All,
I got the following error while running SqueezeMeta - 
Stopping in STEP1 -> 01.merge_assemblies.pl. Program finished abnormally.
(Error in /home/avinash/SqueezeMeta/scripts/01.run_all_assemblies.pl, line number 233). I have attached the syslog file for your further reference). 
Thanks in advance for your help.
Link for the syslog file. [https://easyupload.io/d0s55u](url)

**Comment by fpusan** [comment] 2023-05-02 17:18
Your syslog indicates that mummer is segfaulting
`Command: LD_LIBRARY_PATH=/home/avinash/SqueezeMeta/bin/AMOS/../../lib/mummer  /home/avinash/SqueezeMeta/bin/AMOS/../mummer/nucmer --maxmatch --threads 12 -c 100 /mnt/e/1_clean_data/Aerobiome/temp/mergedassemblies.Aerobiome.99.ref.seq /mnt/e/1_clean_data/Aerobiome/temp/mergedassemblies.Aerobiome.99.qry.seq -p /mnt/e/1_clean_data/Aerobiome/temp/mergedassemblies.Aerobiome.99 exited with status: 139`
How much memory do you have available?

**Comment by fpusan** [comment] 2023-05-02 21:05
Can you try to reproduce the  issue in a ubuntu VM? WSL2 is working quite well nowadays, but one never knows. 
Alternatively try to download and recompile mummer in WSl2, then use that binary to replace the one we ship with SqueezeMeta

**Comment by jtamames** [comment] 2023-05-09 21:54
AVAILABLE (free) RAM memory: 0.00 Gb
That really means something... Is there something wrong with your system?

**Comment by fpusan** [comment] 2023-06-15 14:44
Hi again!
From your paths I see that you are using WSL2.
See the discussion in #695.
You should host your database and project in the Linux FS, not in the Windows one (in your case drive E:\). Even if that drive is available to you when within WSL2, IO performance may be very low.

**Comment by fpusan** [comment] 2023-07-11 16:03
Closing due to lack of activity, but see solution in #695

**Closed by fpusan** 2023-07-11 16:03 UTC
