### ISSUE TITLE
Error while running sqm_mapper.pl

### ISSUE THREAD

**Issue by chandnisidhu** [jtamames/SqueezeMeta#278] opened 2021-04-07 18:57 UTC
Hi,

I got the following error while running sqm_mapper.pl. Is it something to do with the script? 

`perl SqueezeMeta-master/utils/sqm_mapper.pl -r 03.SQM_2020_MT.fna -g 08.SQM_2020_MT.gff -s samples.txt -f reads/ -o SQM_results -t 30

SQM_mapper v1.3.0, Jun 2020 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

This is part of the SqueezeMeta distribution (https://github.com/jtamames/SqueezeMeta)
Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 10.3389 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

  Reading mapping file from samples.txt
  Samples found: 3
  Mapping with Bowtie2 (Langmead and Salzberg 2012, Nat Methods 9(4), 357-9)
  Creating reference in SQM_results/temp/sqm
  Working with sample 1: sample_1
  Getting raw reads
  Aligning to reference with bowtie
  Calculating contig coverage
  Counting with sqm_counter: Opening 30 threads
  5745310 reads counted
  11490619 reads counted
  17235928 reads counted
  22981237 reads counted
  28726546 reads counted
  34471855 reads counted
  40217164 reads counted
  45962473 reads counted
  51707782 reads counted
  57453091 reads counted
  63198400 reads counted
  68943709 reads counted
  74689018 reads counted
  80434327 reads counted
  86179636 reads counted
  91924945 reads counted
  97670254 reads counted
  103415563 reads counted
  109160872 reads counted
  114906181 reads counted
  120651490 reads counted
  126396799 reads counted
  132142108 reads counted
  137887417 reads counted
  143632726 reads counted
  149378035 reads counted
  155123344 reads counted
  160868653 reads counted
  166613962 reads counted
  172359271 reads counted
Illegal division by zero at /SqueezeMeta-master/utils/sqm_mapper.pl line 357, <infilegff> line 0.000000.
`

**Comment by jtamames** [comment] 2021-04-07 19:40
Ouch! I will take a look at this.

Best,
J

**Comment by chandnisidhu** [comment] 2021-04-07 19:48
``

**Comment by chandnisidhu** [comment] 2021-04-07 19:49
Okay!

**Comment by jtamames** [comment] 2021-04-08 10:39
Could you please upload the gff file you are using? (zip it first)

**Comment by chandnisidhu** [comment] 2021-04-08 11:38
[FGS.gff.gz](https://github.com/jtamames/SqueezeMeta/files/6278250/FGS.gff.gz)

Here is the file.

**Comment by jtamames** [comment] 2021-04-08 14:37
Thank you. The problem is probably that the "ID" field in the file also has the strand orientation. For instance, the first line is:

`contig_10000    FGS     CDS     1       537     .       +       0       ID=contig_10000_1_537_+;product=predicted protein`

But the ID should be in the format `contigname_initposition_endposition`, without the extra "_+". In that way, the line should read:

`contig_10000    FGS     CDS     1       537     .       +       0       ID=contig_10000_1_537;product=predicted protein`

Just remove all your `"_+" `and `"_-"`, and it should work.
Best,
Javier

**Comment by chandnisidhu** [comment] 2021-04-08 14:42
Okay. I will try this. Thank you for your quick response.

Best,

Chandni

**Comment by jtamames** [comment] 2021-04-08 14:45
I will specify this is the manual, since it is not explained there. Thanks to you for pointing this one!

**Comment by chandnisidhu** [comment] 2021-04-08 14:52
Actually this file is working well within the main SqueezeMeta pipeline. I mean with 10_mapsamples.pl. I didn't want to use Prodigal for gene predictions so I replaced gene prediction results from SQM with my files and restarted it. It is already running and successfully mapped 90% of my samples. I tried sqm_mapper.pl separately for few samples and got this error.

**Comment by jtamames** [comment] 2021-04-08 14:58
Ok, that`s why. Prodigal should not have put the final "_+" stuff and then it should have worked from the start. We did not test any other gene predictor. Knowing this behaviour I can tailor better the pattern matching to ignore the extra things.
Best,
J

**Comment by chandnisidhu** [comment] 2021-04-08 15:04
But why the same file (from other gene predictor) is working well with the main SQM pipeline?

Despite of having an extra "_+", it is not showing any error while mapping.

**Comment by jtamames** [comment] 2021-04-08 15:12
Yeah, that's weird... because both script 10 and sqm_mapper use essentially the same code for mapping and counting. Then perhaps the error is not that one? Let's see if sqm_mapper works with the new modified gff file.

**Comment by chandnisidhu** [comment] 2021-04-08 15:13
Yeah, I will update you soon.

Thank you again.

Chandni

**Comment by chandnisidhu** [comment] 2021-04-14 08:13
Hi,

It worked after removing extra "_+" from gff file.

Thank you

Chandni

**Comment by jtamames** [comment] 2021-04-14 08:34
Glad to hear that! Closing issue.

**Closed by jtamames** 2021-04-14 08:34 UTC
