### ISSUE TITLE
Stopping in STEP4

### ISSUE THREAD

**Issue by RIJP-SU** [jtamames/SqueezeMeta#707] opened 2023-07-12 06:57 UTC
Hi, I am new to SqueezeMeta. I just successfully passed test_install.pl and run with test files. But I got following error at STEP4, any solution would be aprreciate. My version of SqueezeMeta is 1.6.2post2.
Additinally, I found  Spades assembly is not working in this version. It seems version of spades is too old as the newest spades in my naitive envirionment worked fine.

Working with taxonomy database in /path/to/db/nr.dmnd
 taxaError running command:    /path/to/envs/SqueezeMeta/SqueezeMeta/bin/diamond blastp -q /path/to/test/Hadza/results/03.Hadza.faa -p 35 -d /path/to/db/nr.dmnd -e 0.001 --id 40 -f tab -b 126 -o /path/to/test/Hadza/intermediate/04.Hadza.nr.diamond > /path/to/test/Hadza/temp/diamond.nr.log 2>&1 at /path/to/envs/SqueezeMeta/SqueezeMeta/scripts/04.rundiamond.pl line 77.
Stopping in STEP4 -> 04.rundiamond.pl. Program finished abnormally

  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /path/to/test/Hadza/syslog file (zip it first)
Died at /path/to/envs/SqueezeMeta/bin/SqueezeMeta.pl line 941.

**Comment by jtamames** [comment] 2023-07-12 07:00
Hello
It is likely that the databases are not properly installed. Did you download them and run the test_install.pl script?
Best,
J

**Comment by fpusan** [comment] 2023-07-12 07:05
Can reproduce the error with spades.
Also can you share with us the `/path/to/test/Hadza/temp/diamond.nr.log` and `/path/to/test/Hadza/syslog` files?

**Comment by RIJP-SU** [comment] 2023-07-12 07:19
Thanks jtamaes for your quick response,
I have run the test_install.pl and got "All checks successful".

Thanks fpusan for your quick response,
I am attaching two log files.
[diamond.nr.log](https://github.com/jtamames/SqueezeMeta/files/12024930/diamond.nr.log)
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/12024935/syslog.zip)

**Comment by fpusan** [comment] 2023-07-12 07:24
It seems DIAMOND was killed a few moments after beginning.
Why did you set `-b` to `126`? This is a too high value which can potentially draw lots of memory (hence the process being killed).
Also is this running locally or on a computing cluster?

**Comment by RIJP-SU** [comment] 2023-07-12 07:28
Thanks fpusan,
I am running locally. No paticular reasons for setting -b to 126, just thought higher would be faster. What is proper number? Is default fine?

**Comment by fpusan** [comment] 2023-07-12 07:31
Yes, by default we will dynamically set `-b` based on your available memory, capping it to a reasonable value.
You can edit the `/path/to/test/Hadza/SqueezeMeta_conf.pl` file and modify the `$blocksize` variable so the line reads like
`$blocksize       = NF;`
Then restart the project.

**Comment by RIJP-SU** [comment] 2023-07-12 07:35
Thanks fpusan,
I'll try accordingly. Will share the result later.

**Comment by RIJP-SU** [comment] 2023-07-12 07:37
BTW, are you able to fix the things about Spades soon or later?

**Comment by fpusan** [comment] 2023-07-12 07:40
I'm testing the fix right now, SPAdes seems to be running ok, I will make the release once I check it finishes correctly

**Comment by RIJP-SU** [comment] 2023-07-12 07:43
Thanks fpusan, as I'm planning to process short reads, I would like to have Spades as an option!

**Comment by fpusan** [comment] 2023-07-12 07:48
Megahit (our default) is comparable to SPAdes for short reads processing. But yes, I will most likely release the fix in a few hours

**Comment by fpusan** [comment] 2023-07-12 16:14
The issue with SPAdes has been fixed in 2fbf69d and released in a new version of SqueezeMeta (v1.6.2post3)

**Closed by fpusan** 2023-07-12 16:14 UTC
