### ISSUE TITLE
01.merge_assemblies.pl error under merged mode

### ISSUE THREAD

**Issue by yjiakang** [jtamames/SqueezeMeta#109] opened 2020-06-11 08:00 UTC
Hello,
Here I have 36 metagenomic samples, each paired-end data of sample contains ~10Gb fasta file. so I try to run Squeezemeta with the merged mode. However, error occurred at the first step, in detail, at step 1.5.
I run as follows:
```SqueezeMeta.pl -m merged -p four_cultivars -s sample.txt -f ../raw/ -t 60 --nopfam --euk -b 20```

The error is:
```
Error running command:    /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/AMOS/minimus2 /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/mergedassemblies.four_cultivars.99 -D OVERLAP=100 -D MINID=95 -D THREADS=60 >> /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/syslog 2>&1 at /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.merge_assemblies.pl line 71.
Died at /public/home/jkyin/miniconda3/envs/SqueezeMeta/bin/restart.pl line 145.
```
Can you help me? Thanks a lot.

**Comment by jtamames** [comment] 2020-06-11 10:21
Hello!
Could you send me the syslog file, please?
Best,
Javier

**Comment by yjiakang** [comment] 2020-06-11 10:43
Thanks for replying so quickly.
Here is it:
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/4764261/syslog.zip)

**Comment by fpusan** [comment] 2020-06-11 11:18
Hi!
What is your OS/distro?

**Comment by jtamames** [comment] 2020-06-11 11:19
Hi
It seems that nucmer in minimus2 crashed for some reason... Could you please run the following:
ls -ltr /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp

and paste the result?
Also, which SO are you using?

Thanks!

**Comment by yjiakang** [comment] 2020-06-12 00:39
Hello
```
(base) [jkyin@mn02 ~]$ ls -ltr /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp
total 208368392
-rw-r--r-- 1 jkyin LFRuan 10128672086 May 23 14:41 par1.
-rw-r--r-- 1 jkyin LFRuan 10128672127 May 23 14:42 par2.
-rw-r--r-- 1 jkyin LFRuan 40970965214 Jun  5 17:40 mergedassemblies.four_cultivars.fasta
-rw-r--r-- 1 jkyin LFRuan 29891634545 Jun 11 05:22 mergedassemblies.four_cultivars.99.fasta
-rw-r--r-- 1 jkyin LFRuan  3404958588 Jun 11 05:24 mergedassemblies.four_cultivars.99.fasta.clstr
-rw-r--r-- 1 jkyin LFRuan 62248470108 Jun 11 06:38 mergedassemblies.four_cultivars.99.afg
-rw-r--r-- 1 jkyin LFRuan 28297652790 Jun 11 08:00 mergedassemblies.four_cultivars.99.ref.seq
-rw-r--r-- 1 jkyin LFRuan 28297652790 Jun 11 08:55 mergedassemblies.four_cultivars.99.qry.seq
drwxr-xr-x 2 jkyin LFRuan        8192 Jun 11 08:55 mergedassemblies.four_cultivars.99.bnk
-rw-r--r-- 1 jkyin LFRuan           0 Jun 11 08:55 mergedassemblies.four_cultivars.99.delta
-rw-r--r-- 1 jkyin LFRuan        6863 Jun 11 09:49 mergedassemblies.four_cultivars.99.runAmos.log
```
```
(base) [jkyin@mn02 ~]$ ls -ltr /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/intermediate
total 41666578
-rw-r--r-- 1 jkyin LFRuan 1188543396 May 14 02:58 01.four_cultivars.A57RS1T1.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 14 02:58 01.four_cultivars.A57RS1T1.stats
-rw-r--r-- 1 jkyin LFRuan   43305809 May 14 02:59 01.four_cultivars.A57RS1T1.lon
-rw-r--r-- 1 jkyin LFRuan  980587177 May 14 10:58 01.four_cultivars.A57RS1T2.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 14 10:58 01.four_cultivars.A57RS1T2.stats
-rw-r--r-- 1 jkyin LFRuan   39286789 May 14 10:58 01.four_cultivars.A57RS1T2.lon
-rw-r--r-- 1 jkyin LFRuan 1281045524 May 14 19:55 01.four_cultivars.A57RS1T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 14 19:56 01.four_cultivars.A57RS1T2C.stats
-rw-r--r-- 1 jkyin LFRuan   49571622 May 14 19:56 01.four_cultivars.A57RS1T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1416688666 May 15 03:06 01.four_cultivars.A57RS2T1.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 15 03:06 01.four_cultivars.A57RS2T1.stats
-rw-r--r-- 1 jkyin LFRuan   55156073 May 15 03:06 01.four_cultivars.A57RS2T1.lon
-rw-r--r-- 1 jkyin LFRuan 1234924454 May 15 09:37 01.four_cultivars.A57RS2T2.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 15 09:38 01.four_cultivars.A57RS2T2.stats
-rw-r--r-- 1 jkyin LFRuan   49407501 May 15 09:38 01.four_cultivars.A57RS2T2.lon
-rw-r--r-- 1 jkyin LFRuan 1243679664 May 15 16:09 01.four_cultivars.A57RS2T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 15 16:09 01.four_cultivars.A57RS2T2C.stats
-rw-r--r-- 1 jkyin LFRuan   49028224 May 15 16:09 01.four_cultivars.A57RS2T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1337182819 May 16 02:42 01.four_cultivars.A57RS3T1.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 16 02:43 01.four_cultivars.A57RS3T1.stats
-rw-r--r-- 1 jkyin LFRuan   52449387 May 16 02:43 01.four_cultivars.A57RS3T1.lon
-rw-r--r-- 1 jkyin LFRuan  950225909 May 16 08:28 01.four_cultivars.A57RS3T2.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 16 08:29 01.four_cultivars.A57RS3T2.stats
-rw-r--r-- 1 jkyin LFRuan   39066749 May 16 08:29 01.four_cultivars.A57RS3T2.lon
-rw-r--r-- 1 jkyin LFRuan 1190538653 May 16 14:55 01.four_cultivars.A57RS3T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 16 14:55 01.four_cultivars.A57RS3T2C.stats
-rw-r--r-- 1 jkyin LFRuan   49512953 May 16 14:55 01.four_cultivars.A57RS3T2C.lon
-rw-r--r-- 1 jkyin LFRuan  978341635 May 16 20:10 01.four_cultivars.HF12RS1T1.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 16 20:11 01.four_cultivars.HF12RS1T1.stats
-rw-r--r-- 1 jkyin LFRuan   37015083 May 16 20:11 01.four_cultivars.HF12RS1T1.lon
-rw-r--r-- 1 jkyin LFRuan 1094637604 May 17 02:30 01.four_cultivars.HF12RS1T2.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 17 02:30 01.four_cultivars.HF12RS1T2.stats
-rw-r--r-- 1 jkyin LFRuan   44964551 May 17 02:30 01.four_cultivars.HF12RS1T2.lon
-rw-r--r-- 1 jkyin LFRuan 1101404015 May 17 08:36 01.four_cultivars.HF12RS1T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 17 08:36 01.four_cultivars.HF12RS1T2C.stats
-rw-r--r-- 1 jkyin LFRuan   46049661 May 17 08:37 01.four_cultivars.HF12RS1T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1316749420 May 17 17:31 01.four_cultivars.HF12RS2T1.fasta
-rw-r--r-- 1 jkyin LFRuan        314 May 17 17:31 01.four_cultivars.HF12RS2T1.stats
-rw-r--r-- 1 jkyin LFRuan   56713302 May 17 17:31 01.four_cultivars.HF12RS2T1.lon
-rw-r--r-- 1 jkyin LFRuan  949376703 May 18 00:26 01.four_cultivars.HF12RS2T2.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 18 00:27 01.four_cultivars.HF12RS2T2.stats
-rw-r--r-- 1 jkyin LFRuan   40279411 May 18 00:27 01.four_cultivars.HF12RS2T2.lon
-rw-r--r-- 1 jkyin LFRuan 1161999745 May 18 06:48 01.four_cultivars.HF12RS2T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        319 May 18 06:48 01.four_cultivars.HF12RS2T2C.stats
-rw-r--r-- 1 jkyin LFRuan   49703551 May 18 06:48 01.four_cultivars.HF12RS2T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1287547842 May 18 13:37 01.four_cultivars.HF12RS3T1.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 18 13:37 01.four_cultivars.HF12RS3T1.stats
-rw-r--r-- 1 jkyin LFRuan   51368310 May 18 13:37 01.four_cultivars.HF12RS3T1.lon
-rw-r--r-- 1 jkyin LFRuan  947834964 May 18 19:10 01.four_cultivars.HF12RS3T2.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 18 19:10 01.four_cultivars.HF12RS3T2.stats
-rw-r--r-- 1 jkyin LFRuan   40815983 May 18 19:10 01.four_cultivars.HF12RS3T2.lon
-rw-r--r-- 1 jkyin LFRuan  881672026 May 18 23:34 01.four_cultivars.HF12RS3T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        318 May 18 23:34 01.four_cultivars.HF12RS3T2C.stats
-rw-r--r-- 1 jkyin LFRuan   37389046 May 18 23:34 01.four_cultivars.HF12RS3T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1157385560 May 19 06:08 01.four_cultivars.HG64RS1T1.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 19 06:09 01.four_cultivars.HG64RS1T1.stats
-rw-r--r-- 1 jkyin LFRuan   46893867 May 19 06:09 01.four_cultivars.HG64RS1T1.lon
-rw-r--r-- 1 jkyin LFRuan 1122371797 May 19 12:50 01.four_cultivars.HG64RS1T2.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 19 12:51 01.four_cultivars.HG64RS1T2.stats
-rw-r--r-- 1 jkyin LFRuan   46535165 May 19 12:51 01.four_cultivars.HG64RS1T2.lon
-rw-r--r-- 1 jkyin LFRuan 1220372951 May 19 19:37 01.four_cultivars.HG64RS1T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        314 May 19 19:38 01.four_cultivars.HG64RS1T2C.stats
-rw-r--r-- 1 jkyin LFRuan   55052732 May 19 19:38 01.four_cultivars.HG64RS1T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1127637825 May 20 01:14 01.four_cultivars.HG64RS2T1.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 20 01:14 01.four_cultivars.HG64RS2T1.stats
-rw-r--r-- 1 jkyin LFRuan   46780711 May 20 01:14 01.four_cultivars.HG64RS2T1.lon
-rw-r--r-- 1 jkyin LFRuan 1253243299 May 20 07:35 01.four_cultivars.HG64RS2T2.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 20 07:36 01.four_cultivars.HG64RS2T2.stats
-rw-r--r-- 1 jkyin LFRuan   49644948 May 20 07:36 01.four_cultivars.HG64RS2T2.lon
-rw-r--r-- 1 jkyin LFRuan 1029012452 May 20 13:13 01.four_cultivars.HG64RS2T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 20 13:13 01.four_cultivars.HG64RS2T2C.stats
-rw-r--r-- 1 jkyin LFRuan   43377813 May 20 13:14 01.four_cultivars.HG64RS2T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1340624486 May 20 20:50 01.four_cultivars.HG64RS3T1.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 20 20:51 01.four_cultivars.HG64RS3T1.stats
-rw-r--r-- 1 jkyin LFRuan   49924141 May 20 20:51 01.four_cultivars.HG64RS3T1.lon
-rw-r--r-- 1 jkyin LFRuan 1024477161 May 21 03:28 01.four_cultivars.HG64RS3T2.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 21 03:28 01.four_cultivars.HG64RS3T2.stats
-rw-r--r-- 1 jkyin LFRuan   42734741 May 21 03:28 01.four_cultivars.HG64RS3T2.lon
-rw-r--r-- 1 jkyin LFRuan 1189531143 May 21 10:30 01.four_cultivars.HG64RS3T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 21 10:30 01.four_cultivars.HG64RS3T2C.stats
-rw-r--r-- 1 jkyin LFRuan   50390940 May 21 10:30 01.four_cultivars.HG64RS3T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1237699226 May 21 17:52 01.four_cultivars.HG70RS1T1.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 21 17:52 01.four_cultivars.HG70RS1T1.stats
-rw-r--r-- 1 jkyin LFRuan   52784447 May 21 17:52 01.four_cultivars.HG70RS1T1.lon
-rw-r--r-- 1 jkyin LFRuan  894120253 May 21 23:12 01.four_cultivars.HG70RS1T2.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 21 23:12 01.four_cultivars.HG70RS1T2.stats
-rw-r--r-- 1 jkyin LFRuan   37040196 May 21 23:12 01.four_cultivars.HG70RS1T2.lon
-rw-r--r-- 1 jkyin LFRuan 1519768589 May 22 08:05 01.four_cultivars.HG70RS1T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        317 May 22 08:06 01.four_cultivars.HG70RS1T2C.stats
-rw-r--r-- 1 jkyin LFRuan   68230493 May 22 08:06 01.four_cultivars.HG70RS1T2C.lon
-rw-r--r-- 1 jkyin LFRuan  901619064 May 22 13:51 01.four_cultivars.HG70RS2T1.fasta
-rw-r--r-- 1 jkyin LFRuan        315 May 22 13:51 01.four_cultivars.HG70RS2T1.stats
-rw-r--r-- 1 jkyin LFRuan   39225195 May 22 13:52 01.four_cultivars.HG70RS2T1.lon
-rw-r--r-- 1 jkyin LFRuan 1154347844 May 22 20:32 01.four_cultivars.HG70RS2T2.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 22 20:32 01.four_cultivars.HG70RS2T2.stats
-rw-r--r-- 1 jkyin LFRuan   48009444 May 22 20:32 01.four_cultivars.HG70RS2T2.lon
-rw-r--r-- 1 jkyin LFRuan  966091938 May 23 02:20 01.four_cultivars.HG70RS2T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 23 02:20 01.four_cultivars.HG70RS2T2C.stats
-rw-r--r-- 1 jkyin LFRuan   40557813 May 23 02:20 01.four_cultivars.HG70RS2T2C.lon
-rw-r--r-- 1 jkyin LFRuan 1038227898 May 23 08:22 01.four_cultivars.HG70RS3T1.fasta
-rw-r--r-- 1 jkyin LFRuan        313 May 23 08:22 01.four_cultivars.HG70RS3T1.stats
-rw-r--r-- 1 jkyin LFRuan   46263662 May 23 08:23 01.four_cultivars.HG70RS3T1.lon
-rw-r--r-- 1 jkyin LFRuan  951419402 May 23 14:39 01.four_cultivars.HG70RS3T2.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 23 14:40 01.four_cultivars.HG70RS3T2.stats
-rw-r--r-- 1 jkyin LFRuan   39289263 May 23 14:40 01.four_cultivars.HG70RS3T2.lon
-rw-r--r-- 1 jkyin LFRuan 1300034110 May 23 23:02 01.four_cultivars.HG70RS3T2C.fasta
-rw-r--r-- 1 jkyin LFRuan        316 May 23 23:03 01.four_cultivars.HG70RS3T2C.stats
-rw-r--r-- 1 jkyin LFRuan   56818938 May 23 23:03 01.four_cultivars.HG70RS3T2C.lon
```


My OS:
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core)
Release:        7.5.1804
Codename:       Core
```

**Comment by jtamames** [comment] 2020-06-12 13:56
Hello
Thanks for the information. Individual assemblies were done correctly, and then, in the merging proccess, minimus2 crashed when calculation overlaps. Could you please send me also the 
`/public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/mergedassemblies.four_cultivars.99.runAmos.log` 
file? Sorry, I should have asked you for it already.
I am thinking that probably minimus2 cannot manage so much data. Let´s try to run it in seqmerge mode. In this way, assembly will be merged in pairs and the load will be reduced. Could you run:

`perl /public/home/jkyin/miniconda3/envs/SqueezeMeta/bin/01.merge_sequential.pl four_cultivars`

This will take a long time since it will do n-1 merging steps, being n the number of samples (36 in your case). If you see that the first merges succeed, let me know, since it means that minimus2 is working correctly.

**Comment by yjiakang** [comment] 2020-06-14 00:20
Yes, it works. 
```
(base) [jkyin@mn02 ~]$ bpeek
<< output from stdout >>
  Starting assembly merge
  MERGE 1, 01.four_cultivars.A57RS2T2C.fasta and 01.four_cultivars.A57RS1T2C.fasta (dist 0.33) -> merged_1.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
  MERGE 2, 01.four_cultivars.A57RS2T1.fasta and merged_1.four_cultivars.fasta (dist 0.31) -> merged_2.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
```
Thanks, I will wait for its completion. By the way, after this, I intend to run the remaining steps like this ```restart.pl four_cultivars -step 2```. Is it OK?

**Comment by jtamames** [comment] 2020-06-14 07:10
So the problem is with minimus2 managing so much data. That happened to us before, that's why we developed the seqmerge mode. Happy to know that it works for you.
Yes, when it finishes, just restart in step 2. 

Best,
Javier

**Comment by jtamames** [comment] 2020-06-18 16:28
Hello! How is that working? Still running?

**Comment by yjiakang** [comment] 2020-06-19 08:29
Hello! 
Something was wrong, I attached the stdout, stderr, and syslog calling for your help. Thanks in advance.

[01.merge_sequential.pl.out.zip](https://github.com/jtamames/SqueezeMeta/files/4803381/01.merge_sequential.pl.out.zip)
[01.merge_sequential.pl.err.err.zip](https://github.com/jtamames/SqueezeMeta/files/4803382/01.merge_sequential.pl.err.err.zip)
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/4803383/syslog.zip)

**Comment by jtamames** [comment] 2020-06-19 09:29
Damn... kmer-db crashed for an unknown reason. It is weird because it was working fine, indeed it worked for the first five merges and then crashed in sixth.
Could you run this manually?
`LD_LIBRARY_PATH=/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/kmer-db build -t 60 /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/samples.four_cultivars.txt /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/kmerdb.four_cultivars.txt`

And paste the result?

**Comment by yjiakang** [comment] 2020-06-19 12:10
```
(base) [jkyin@mn02 ~]$ LD_LIBRARY_PATH=/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib
(base) [jkyin@mn02 ~]$ /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/kmer-db build -t 60
Kmer-db version 1.7.2 (15.01.2020)
S. Deorowicz, A. Gudys, M. Dlugosz, M. Kokot, and A. Danek (c) 2018

USAGE

kmer-db <mode> [options] <positional arguments>

Modes:
  build - building a database from genomes, k-mers, or minhashed k-mers,
  all2all - counting common k-mers - all samples in the database,
  new2all - counting common k-mers - set of new samples versus database,
  one2all - counting common k-mers - single sample versus database,
  distance - calculating similarities/distances.
  minhash - storing minhashed k-mers,
Common options:
  -t <threads> - number of threads (default: number of available cores),
The meaning of other options and positional arguments depends on the selected mode.

Building a database:
  kmer-db build [-k <kmer-length>] [-f <fraction>] [-multisample-fasta] <sample_list> <database>
  kmer-db build -from-kmers [-f <fraction>] <sample_list> <database>
  kmer-db build -from-minhash <sample_list> <database>
    sample_list (input) - file containing list of samples in one of the following formats:
                          fasta genomes or reads (default), KMC k-mers (-from-kmers), or minhashed k-mers (-from-minhash),
    database (output) - file with generated k-mer database,
    -k <kmer_length> - length of k-mers (default: 18),
    -f <fraction> - fraction of all k-mers to be accepted by the minhash filter (default: 1),
    -multisample-fasta - each sequence in a genome FASTA file is treated as a separate sample.

Counting common k-mers for all the samples in the database:
  kmer-db all2all [-buffer <size_mb>] <database> <common_table>
    database (input) - k-mer database file.
    common_table (output) - comma-separated table with number of common k-mers.
    -buffer <size_mb> - size of cache buffer in megabytes, applies to all2all mode
                      (use L3 size for Intel CPUs and L2 for AMD to maximize performance; default: 8).

Counting common kmers between set of new samples and all the samples in the database:
  kmer-db new2all [-multisample-fasta | -from-kmers | -from-minhash] <database> <sample_list> <common_table>
    database (input) - k-mer database file.
    sample_list (input) - file containing list of query samples in one of the supported formats (see build mode).
    common_table (output) - comma-separated table with number of common k-mers.

Counting common kmers between single sample and all the samples in the database:
  kmer-db one2all [-multisample-fasta | -from-kmers | -from-minhash] <database> <sample> <common_table>
    database (input) - k-mer database file.
    sample (input) - query sample in one of the supported formats (see build mode).
    common_table (output) - comma-separated table with number of common k-mers.

Calculating similarities/distances on the basis of common k-mers:
  kmer-db distance [<measures>] [-phylip-out] <common_table>
    common_table (input) - comma-separated table with number of common k-mers.
    -phylip-out - store output distance matrix in a Phylip format
    measures - names of the similarity/distance measures to be calculated, one or more of the following
               jaccard (default), min, max, cosine, mash.
This mode generates a file with similarity/distance table for each selected measure.
Name of the output file is produced by adding to the input file an extension with a measure name.

Storing minhashed k-mers:
  kmer-db minhash [-k <kmer-length>] [-multisample-fasta] <fraction> <sample_list>
  kmer-db minhash -from-kmers <fraction> <sample_list>
    fraction (input) - fraction of all k-mers to be accepted by the minhash filter.
    sample_list (input) - file containing list of query samples in one of the supported formats (see build mode).
For each sample from the list, a binary file with *.minhash* extension containing filtered k-mers is created.
```
And I do not understand the last commands though I run them:
```
(base) [jkyin@mn02 ~]$ /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/samples.four_cultivars.txt
-bash: /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/samples.four_cultivars.txt: Permission denied
(base) [jkyin@mn02 ~]$ /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/kmerdb.four_cultivars.txt
-bash: /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/kmerdb.four_cultivars.txt: Permission denied
```

**Comment by jtamames** [comment] 2020-06-19 12:43
Ups sorry, all the code above is just a single command, not five different lines of code. Please put all lines together and run it again

**Comment by yjiakang** [comment] 2020-06-20 00:55
This is the output:
```
LD_LIBRARY_PATH=/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/kmer-db build -t 30 /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/samples.four_cultivars.txt /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/kmerdb.four_cultivars.txt


------------------------------------------------------------

Exited with exit code 139.

Resource usage summary:

    CPU time :                                   14972.41 sec.
    Max Memory :                                 215471 MB
    Average Memory :                             115376.84 MB
    Total Requested Memory :                     10000.00 MB
    Delta Memory :                               -205471.00 MB
    Max Swap :                                   1 MB
    Max Processes :                              8
    Max Threads :                                833
    Run time :                                   691 sec.
    Turnaround time :                            3373 sec.

The output (if any) follows:

Kmer-db version 1.7.2 (15.01.2020)
S. Deorowicz, A. Gudys, M. Dlugosz, M. Kokot, and A. Danek (c) 2018

Database building mode (from fasta genomes)
Analysis started at Sat Jun 20 00:02:15 2020

Processing samples...
^M10/31...

PS:

Read file <01.debug.pl.err> for stderr output of this job.
```

**Comment by jtamames** [comment] 2020-06-22 13:55
Hello
Can you please paste the `/public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/samples.four_cultivars.txt` file?

**Comment by yjiakang** [comment] 2020-06-22 13:58
[samples.four_cultivars.txt](https://github.com/jtamames/SqueezeMeta/files/4813603/samples.four_cultivars.txt)

**Comment by jtamames** [comment] 2020-06-22 14:17
Sorry, please do it with ls -l, so that I can see the file sizes

**Comment by jtamames** [comment] 2020-06-22 14:21
and the result of `ls -l /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/intermediate/merged_5.four_cultivars*`?

**Comment by yjiakang** [comment] 2020-06-22 14:29
Hello
```
-rw-r--r-- 1 jkyin LFRuan 1.9G Jun 16 19:02 merged_1.four_cultivars.fasta
-rw-r--r-- 1 jkyin LFRuan 2.7G Jun 17 09:06 merged_2.four_cultivars.fasta
-rw-r--r-- 1 jkyin LFRuan 1.9G Jun 17 17:12 merged_3.four_cultivars.fasta
-rw-r--r-- 1 jkyin LFRuan 2.8G Jun 18 04:06 merged_4.four_cultivars.fasta
-rw-r--r-- 1 jkyin LFRuan 4.9G Jun 19 09:16 merged_5.four_cultivars.fasta
```

**Comment by jtamames** [comment] 2020-06-22 14:48
No idea so far, but I will keep looking at this. I wonder if it is a memory issue. Did you try to increase the available memory, if you can? Also, did you see that file `01.debug.pl.err` that is mentioned when running the command above?

**Comment by yjiakang** [comment] 2020-06-23 04:44
Yes, I ran the commond mentioned above on a hpc node (192 cores, 2T RAM). However, I am not sure if there any one ran out the memory during the process.
 ```
LD_LIBRARY_PATH=/public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/kmer-db build -t 30 /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/samples.four_cultivars.txt /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/temp/kmerdb.four_cultivars.txt
```
And I have no idea about the info in file [01.debug.pl.err.zip](https://github.com/jtamames/SqueezeMeta/files/4817186/01.debug.pl.err.zip)

**Comment by jtamames** [comment] 2020-06-23 08:22
Thanks for the file. Something weird happened before it crashes:

`/public/home/jkyin/.lsbatch/1592580943.12707148.shell: line 8: cd: yjk/: No such file or directory`
`/public/home/jkyin/.lsbatch/1592580943.12707148.shell: line 9: 674982 Segmentation fault      (core dumped)`

It attempts a directory change and fails. Could you check if that `/public/home/jkyin/.lsbatch/1592580943.12707148.shell` file is still there and paste it here?

**Comment by yjiakang** [comment] 2020-06-23 08:43
I tried to send you ```/public/home/jkyin/.lsbatch/1592580943.12707148.shell``` on the last comments , but it didn't exist.

**Comment by jtamames** [comment] 2020-06-23 08:50
Yeah, it was probably erased after the crash. I am unsure if the kmer-db crash is due to something system-related or to a failure of the software itself. 
Let´s try to restart the project again:

`perl /public/home/jkyin/miniconda3/envs/SqueezeMeta/bin/01.merge_sequential.pl four_cultivars`

This will skip the first merges that you already have. Let´s see if it crashes again in the same point.
Let me know what happens
Best,

**Comment by yjiakang** [comment] 2020-06-28 02:12
Hello, ```perl /public/home/jkyin/miniconda3/envs/SqueezeMeta/bin/01.merge_sequential.pl four_cultivars``` stopped at MERGE 6 and threw the same error as previous:
```
The output (if any) follows:

  Starting assembly merge
  MERGE 1, 01.four_cultivars.A57RS2T2C.fasta and 01.four_cultivars.A57RS1T2C.fasta (dist 0.33) -> merged_1.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
  MERGE 2, 01.four_cultivars.A57RS2T1.fasta and merged_1.four_cultivars.fasta (dist 0.31) -> merged_2.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
  MERGE 3, 01.four_cultivars.A57RS3T2C.fasta and 01.four_cultivars.HG70RS3T2C.fasta (dist 0.30) -> merged_3.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
  MERGE 4, merged_3.four_cultivars.fasta and 01.four_cultivars.HG70RS1T2C.fasta (dist 0.31) -> merged_4.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
  MERGE 5, merged_4.four_cultivars.fasta and merged_2.four_cultivars.fasta (dist 0.30) -> merged_5.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
  MERGE 6, 01.four_cultivars.HF12RS3T2C.fasta and 01.four_cultivars.HF12RS1T2C.fasta (dist 0.29) -> merged_6.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
```
Error output:
```
Error running command:    /public/home/jkyin/miniconda3/envs/SqueezeMeta/SqueezeMeta/lib/SqueezeMeta/kmerdist.pl four_cultivars 7 >> /public/home/jkyin/yjk/tomato_micro/squeezemeta/four_cultivars/syslog 2>&1 at /public/home/jkyin/miniconda3/envs/SqueezeMeta/bin/01.merge_sequential.pl line 56.
```

**Comment by jtamames** [comment] 2020-06-29 12:37
Hello again
I think this is likely a memory related error. We were able to reproduce something similar to your issue, and in  our case the problem was linked to memory exhaustion. I will try to reprogram the way in which kmer-db is being used, as to reduce memory usage as much as possible. I will let you know in the coming days.

Best,
Javier

**Comment by jtamames** [comment] 2020-07-06 13:11
Hello
I have redone 01.merge_sequential.pl but it is still crashing with big datasets.
But, we are trying decreasing the kmer size in kmer-db, and so far it is working with just 16 Gb RAM. Decreasing k-mer size implies less k-mers, and therefore reduces memory usage.
If you want to try, edit the script kmerdist.pl in the `lib/SqueezeMeta` directory. There, change line 61:

`$command="$kmerdb_soft build -t $numthreads $samples $kmerdb > /dev/null 2>&1";`

by

`$command="$kmerdb_soft build -t $numthreads $samples $kmerdb -k 12 > /dev/null 2>&1";`

That will make kmer-db to user kmer size 12, instead the original 18. Since we just want to calculate an approximate similarity measure between metagenomes, it will suffice for our purposes.

If you try it, please tell me if it works for you.

Best,
Javier

**Comment by yjiakang** [comment] 2020-07-11 08:47
Hi Javier
Thanks for your useful suggestion, I tried and it is running smoothly to MERGE 7.
Once this is done, I will tell you.
Best,
jk yin

**Comment by yjiakang** [comment] 2020-07-20 01:26
Hi Javier,
I added -k 12 as you suggested, but it crushed at MERGE 10. And everytime I run this merge task, it runs from the begining rather than resume. This waste many computational resources. Would it be kind for you to help me? 
Here is the end of the stdout file:
```
  MERGE 10, merged_9.four_cultivars.fasta and 01.four_cultivars.HG64RS3T2.fasta (dist 1.00) -> merged_10.four_cultivars.fasta
  Running cd-hit-est
  Transforming to afg format
  Merging with minimus2
```
Best,
jk yin

**Comment by yjiakang** [comment] 2020-07-21 01:39
Hi Javier,
May be I know what is wrong, I should apply for enough memory for  this task in LSF system, and have a try again. Once I have any progress, I will tell you asap. Sorry for disturbance.
Best,
jk yin

**Comment by fpusan** [comment] 2020-08-31 08:11
Closing due to lack of activity. Feel free to reopen if you need further assistance.

**Closed by fpusan** 2020-08-31 08:11 UTC
Labels: Assembly, merged mode, seqmerge mode
