### ISSUE TITLE
install error squeezemeta-1.1.0-pl526r36_0 requires perl-dbd-mysql

### ISSUE THREAD

**Issue by luozhy88** [jtamames/SqueezeMeta#550] opened 2022-09-25 08:56 UTC
<img width="876" alt="image" src="https://user-images.githubusercontent.com/94740863/192136091-f30a1a08-0e41-48e1-969f-87b417be9dc1.png">

**Comment by fpusan** [comment] 2022-09-25 10:49
Duplicate of #551

**Closed** 2022-09-25 10:48 UTC

**Comment by luozhy88** [comment] 2022-09-26 15:03
great ! solved  it !
