### ISSUE TITLE
RDP error (file not found)

### ISSUE THREAD

**Issue by MalbertR** [jtamames/SqueezeMeta#199] opened 2020-11-23 12:16 UTC
Below you can see the error output. 

```
Running RDP classifier (Wang et al 2007, Appl Environ Microbiol 73, 5261-7)
Can't open /hpc/dla_mm/SqueezeMetaDB/db/LCA_tax/parents.txt
Stopping in STEP2 -> 02.rnas.pl. Program finished abnormally
```

This file (and the directory "LCA_tax") is missing in the database directory. I have to add that I went for the `make_database.pl` option when building the database. 

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5582856/syslog.txt)

**Comment by fpusan** [comment] 2020-11-23 12:20
Hi,
It seems that there was a problem when making the databases, but without having the log for that command (the syslog you sent covers only that particular run of SqueezeMeta, but not the database creation script) it is difficult to tell what could have happened.
Can you use `download_databases.pl` instead? While you are at it, you can update to version 1.3 if you weren't using it already.

**Comment by fpusan** [comment] 2020-11-23 12:27
Also make sure that you have enough free disk space without downloading the databases

**Comment by MalbertR** [comment] 2020-11-23 12:32
> Hi,
> It seems that there was a problem when making the databases, but without having the log for that command (the syslog you sent covers only that particular run of SqueezeMeta, but not the database creation script) it is difficult to tell what could have happened.
> Can you use `download_databases.pl` instead? While you are at it, you can update to version 1.3 if you weren't using it already.

Yes, this indeed what I also would think was the problem. So, I was indeed planning to run `download_databases.pl` in a bit and see if that makes any difference. 

About the disk space, I did check before running the script and so was pretty sure there was enough space for the database. It also finished just fine it seemed, without any error/warning messages. 
Where can I find the log file for the database creation?

**Comment by MalbertR** [comment] 2020-11-23 12:33
Thanks for the quick replies, by the way :)

**Comment by fpusan** [comment] 2020-11-23 12:37
We don't log database creation (guess we should), so unless you redirected stdout/stderr to a file it is lost.
Let me know how `download_database.pl` goes for you. From version 1.3 onwards we double check the md5 sums of the different tarballs we download, so if the script does not complain the database will likely be ok (unless lack of disk space made the unpacking step to fail).

**Comment by fpusan** [comment] 2020-11-23 17:08
Just a heads up, there is a planned internet outage in our institution tomorrow at 6:30-10:00 GMT, which will affect the downloads.

**Comment by MalbertR** [comment] 2020-11-24 08:47
I tried `download_database.pl`, which went fine. However, running `test_install.pl` afterwards gave me the following message:

```
Checking that SqueezeMeta is properly configured
	SqueezeMeta_conf.pl says that databases are located in /hpc/dla_mm/SqueezeMetaDB but we can't find nr.db there

All checks successful
```

I saw that other also had this same issue and that the recommendation was to try the `make_database.pl` instead?

**Comment by fpusan** [comment] 2020-11-24 08:50
Weird. Were are the databases located? I think it should say `/hpc/dla_mm/SqueezeMetaDB/db`. Can you find the `nr.db` file manually?

**Comment by MalbertR** [comment] 2020-11-24 08:55
So, in that directory there are 2 other directories, namely: `test` and `db`. 

Contents of `db`:

```
arc.all.faa     bac.all.faa       bac.scg.lookup  euk.hmm      img          mito.hmm    ReadMe                    taxon_marker_sets.tsv
arc.hmm         bacar_marker.hmm  DB_BUILD_DATE   genome_tree  keggdb.dmnd  nr.dmnd     selected_marker_sets.tsv  test_data
arc.scg.faa     bac.hmm           distributions   hmms         LCA_tax      pfam        silva.nr_v132.align
arc.scg.lookup  bac.scg.faa       eggnog.dmnd     hmms_ssu     marker.hmm   Pfam-A.hmm  silva.nr_v132.tax
```

**Comment by fpusan** [comment] 2020-11-24 09:02
Try
`configure_nodb /hpc/dla_mm/SqueezeMetaDB/db`
And then run `test_install.pl` again. It should not complain now.
Anyways I will try to reproduce the issue when we get our internet back.

**Comment by MalbertR** [comment] 2020-11-24 09:56
> Try
> `configure_nodb /hpc/dla_mm/SqueezeMetaDB/db`
> And then run `test_install.pl` again. It should not complain now.
> Anyways I will try to reproduce the issue when we get our internet back.

Thank you!
This did indeed solve the issue! Maybe you can add this to the README, since there it seems like the `configure_nodb.pl` script should only be executed if the database was already build before installing the pipeline.

**Comment by fpusan** [comment] 2020-11-24 09:58
Oh, so was that what happened? You ran configure_nodb on the wrong path after installing the databases?
If so, I will amend the ReadMe to make it clearer

**Comment by MalbertR** [comment] 2020-11-24 09:59
> Oh, so was that what happened? You ran configure_nodb on the wrong path after installing the databases?
> If so, I will amend the ReadMe to make it clearer

**Comment by MalbertR** [comment] 2020-11-24 10:05
> Oh, so was that what happened? You ran configure_nodb on the wrong path after installing the databases?
> If so, I will amend the ReadMe to make it clearer

No, so I did not know it was necessary to run configure_nodb.pl after downloading the database, since it was stated in the README that it should be executed when already having built the database somewhere else? So, this next sentence in the README  caused the confusion for me:

```
If the SqueezeMeta databases are already built in another location in the system, a different copy of SqueezeMeta can be configured to use them with

/path/to/SqueezeMeta/utils/install_utils/configure_nodb.pl /path/to/db
```

If it was really required, I would have expected something more like this in the README: "After downloading is complete, the next step would be to configure the database by running: `/path/to/SqueezeMeta/utils/install_utils/configure_nodb.pl /path/to/db`"
However, this might just be me being new to perl pipelines and perl in general. 

By the way, I'm sorry, I closed the issue by accident there.

**Comment by fpusan** [comment] 2020-11-24 10:08
It is NOT necessary to run `configure_nodb.pl` after `download_databases.pl`. It should have taken care of everything for you.
Actually, your issue looked like you ran `configure_nodb.pl` pointing to the wrong directory.
So what did you do exactly?

**Comment by fpusan** [comment] 2020-11-24 10:13
Anyways it seems that you understood the ReadMe correctly (you don't have to run `configure_nodb.pl` if you have ran make_databases or download_databases).
So the problem must be elsewhere...

**Comment by fpusan** [comment] 2020-11-24 12:29
Could not reproduce the issue using the latest version. Running `download_databases.pl` by itself produced the expected result, and `test_install.pl` finished successfully

**Comment by MalbertR** [comment] 2020-11-27 14:24
> Could not reproduce the issue using the latest version. Running `download_databases.pl` by itself produced the expected result, and `test_install.pl` finished successfully

Ok, that's weird then. However, it's all working fine fr me now, after first running `download_databases.pl` and then `configure_nodb.pl`. So, I will leave that here just in case others run into a similar issue, running those two scripts in that order, solved it for me on my system. Thanks a lot for your help @fpusan!

**Comment by fpusan** [comment] 2020-11-27 15:10
Thanks for reporting! Closing issue

**Closed by fpusan** 2020-11-27 15:10 UTC

**Comment by bresyd** [comment] 2022-02-01 08:22
Hi,

I think I am facing a similar issue as reported here.
I downloaded the latest database using `make_databases_alt.pl` (`make_databases.pl` did not work for me last week), and from the log (which I don't have anymore) it looked like everything downloaded fine. Also, running `test_install.pl` does not report any issues:
```
Checking that SqueezeMeta is properly configured... checking database in /scratch/databases/squeezemeta/db_20220130/db
        nr.db OK
        CheckM manifest OK
        LCA_tax DB OK

All checks successful
```
However, when I do a SQM run on the test dataset, I get an error because there is obviously a file missing:
```
SqueezeMeta.pl -m coassembly -p Hadza -s test.samples -f raw --D --euk --binners maxbin,metabat2,concoct -t 30 | tee Hadza_terminal_output.txt
...
Can't open /scratch/databases/squeezemeta/db_20220130/db/LCA_tax/parents.txt
Stopping in STEP2 -> 02.rnas.pl. Program finished abnormally
Died at /home/btschits/miniconda3/envs/SqueezeMeta_1.5.0/bin/SqueezeMeta.pl line 1381.
```
looking into the directory, there really is no parents.txt file
```
l db/LCA_tax
./  ../  parents.db  taxid.db  taxid.md5

```

I guess something went wrong during the download that I did not notice. I was wondering, do you think I need to repeat the whole download? Or can I just use the missing file from my previous installation of the database?

Thanks a lot

**Comment by fpusan** [comment] 2022-02-01 08:33
I'd try to repeat the whole thing.
`download_databases.pl` should hopefully work now.

**Comment by bresyd** [comment] 2022-02-01 08:59
ok, cool, I will download the db again and see if it works.

thanks again

**Comment by bresyd** [comment] 2022-02-03 09:44
`download_databases.pl` did the job now; all db files are there.
Thanks again

**Comment by fpusan** [comment] 2022-02-03 09:48
Glad to hear it works again
