### ISSUE TITLE
Error when loading data for SQMtools

### ISSUE THREAD

**Issue by RIJP-SU** [jtamames/SqueezeMeta#895] opened 2024-10-09 03:17 UTC
I have run SqueezeMeta (v1.7.0a6) by adding option -extbins.
The process of SqueezeMeta was normally finished but when I try loading data by SQM tools I got following error.

Loading total reads
Loading orfs
    table...
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In loadSQM("/path/to/project/") :
  Your project was created with SqueezeMeta v1.7.0a6, while this is SQMtools v1.6.3. You can ignore this message if things are working fine for you, but if you experience any issue consider using the right version of SQMtools for this project
2: non-unique value when setting 'row.names': ‘analysis_870_3-113’  

The other project analyzed by same version of SquuezeMeta was normally loaded. And contig  'analysis_870_3-113' is not duplicated as long as checking some result files. 

I don't know why this happen. If there are any suggestion or solution, I would be grateful.

Thanks in advance!

**Comment by fpusan** [comment] 2024-10-11 07:11
Note that 1.7 is our dev branch and may still contain bugs. This said, I don't think this is because of that.
Looks like a duplicate of #893.
Did you restart the run at any point?

**Comment by RIJP-SU** [comment] 2024-10-13 03:23
Thanks fpusan, 
I have checked the files throughly and found there is indeed a duplicate in xxx. orf.marker.genes.tsv.
The duplicate rows are completely same inforamation. When I deleted one of the duplicate, the files are successfully loaded by SQM tools.
As I leave this project for a while, I dont't remember well but I think I did not restart the run for this project.

**Comment by fpusan** [comment] 2024-11-01 10:43
Closing, as I have fixed this in the dev version

**Closed by fpusan** 2024-11-01 10:43 UTC
