### ISSUE TITLE
Error on step 3: 03.run_prodigal.pl line 40

### ISSUE THREAD

**Issue by timyerg** [jtamames/SqueezeMeta#357] opened 2021-09-06 11:22 UTC
Hello! 
I am trying to run SqueezeMeta on the server. Installation and downloading db steps finished successfully (all checks are ok).
Binaries are working when called from the repository bin directory.
 
Getting an error on step 3, didn't find any information about it among open and closed issues.
Here is a syslog:
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/7115553/syslog.zip)

Errors from server outputs:
```
-p destination: Broken pipe
Error running command:    /beegfs/work/graaf20/SqueezeMeta/SqueezeMeta/bin/prodigal -q -m -p meta -i /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/intermediate/02.RSP_SqueezeMeta_pooled.maskedrna.fasta -a /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/results/03.RSP_SqueezeMeta_pooled.faa -d /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/results/03.RSP_SqueezeMeta_pooled.fna -f gff -o /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/temp/02.RSP_SqueezeMeta_pooled.cds.gff.temp at /beegfs/work/graaf20/SqueezeMeta/SqueezeMeta/scripts/03.run_prodigal.pl line 40.
Died at ../SqueezeMeta/SqueezeMeta/scripts/SqueezeMeta.pl line 1367.
```

One more:

```
[1m
SqueezeMeta v1.4.0, May 2021 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

[0mRun started Mon Sep  6 12:52:43 2021 in coassembly mode
Now creating directories
Reading configuration from /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/SqueezeMeta_conf.pl
Reading samples from /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/data/00.RSP_SqueezeMeta_pooled.samples
2 samples found: sample80 sample1

Now merging files
[34m[1 minutes, 17 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
[0m  External assembly provided: Metaspades_pooled/RSP/scaffolds.fasta. Overriding assembly
  Renaming contigs
  Counting length of contigs
  Contigs stored in /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/results/01.RSP_SqueezeMeta_pooled.fasta
  Number of contigs: 3747282
[34m[2 minutes, 20 seconds]: STEP2 -> RNA PREDICTION: 02.rnas.pl
[0m  Running barrnap (Seeman 2014, Bioinformatics 30, 2068-9) for predicting RNAs:  Bacteria Archaea Eukaryote Mitochondrial
  Running RDP classifier (Wang et al 2007, Appl Environ Microbiol 73, 5261-7)
  Running Aragorn (Laslett & Canback 2004, Nucleic Acids Res 31, 11-16) for tRNA/tmRNA prediction
[34m[19 minutes, 49 seconds]: STEP3 -> ORF PREDICTION: 03.run_prodigal.pl
[0m  Running prodigal (Hyatt et al 2010, BMC Bioinformatics 11: 119) for predicting ORFs
[31mStopping in STEP3 -> 03.run_prodigal.pl. Program finished abnormally
[0m[31m
  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/syslog file (zip it first)
[0m
```

**Comment by jtamames** [comment] 2021-09-06 11:59
Hello!
Weird, Prodigal didn produce any issues so far. What are your sequences, metagenomic DNA?
Could you copy the first lines of the 02.RSP_SqueezeMeta_pooled.maskedrna.fasta in the intermediate directory?
Best,
J

**Comment by timyerg** [comment] 2021-09-06 12:16
Wow, thanks for the fast answer!
So I am very lucky to get this error.
Here it is:
```
>megahit_1
CATCCATAATCTGTTATTATCGCTAATTAAACAATTAAAAAAACTATCATTTCACAACCTCCCAATGCCCGCTTTTGGCAGAGCCTATACGTTTAAGTATGCCCATGGACTTCAATTTGTTGACATGATTCTGTACCGAAGTAACAGAAATGCCAGTTTTTTCCGCTAATGTTTCTCTGCTGATATAATTATCCAAGTATATCAATTTCAATATTTTAACGGCAGTTTCAGACAACCCTTTAGACAACTCATCAGACAACCTTTTAGACAACCCTTTAGGCAACCCATCGGTCAACCCATCAGGCAACCCTTTAGACAACTCATCTGCTGTTGTCACCGTCTTGGTTGAAGGCACAGGCAACACCAATTCCACTACATCCACATCAATCCTGTTCTTCAGTTCCGGCTTCTCCCATCCAGCTTGTTTCCAAGCCTCTAAGATAAGCGGGAAGCCCGAACCAAGGTTTTCACCATAGCCCACC...
```
 Additional information:
I provided external assemblies (scaffolds.fasta from metaspades output). Can it be a reason and should I try with contigs.fasta?

Best,
Timur

**Comment by timyerg** [comment] 2021-09-06 12:30
Update:
Forgot to add:
When it is still running on step 2 and before the error, I am getting this line in the log:
`-p destination: Broken pipe`

**Comment by jtamames** [comment] 2021-09-06 12:37
Hello
It shouldn´t be a problem to use the scaffold.fasta as external assembly. Just to discard things, could you run it gain using the contigs.fasta file as external assembly?

**Comment by timyerg** [comment] 2021-09-06 12:47
The same error again with contigs.fasta as external assembly

**Comment by jtamames** [comment] 2021-09-06 12:52
Ok, try running:
`/beegfs/work/graaf20/SqueezeMeta/SqueezeMeta/bin/prodigal  -m -p meta -i /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/intermediate/02.RSP_SqueezeMeta_pooled.maskedrna.fasta -f gff -o /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/temp/02.RSP_SqueezeMeta_pooled.cds.gff.temp `
What output do you have?

**Comment by timyerg** [comment] 2021-09-06 13:29
That's strange.
When I runing your command directly from the jupyter:
`!/beegfs/work/graaf20/SqueezeMeta/SqueezeMeta/bin/prodigal -m -p meta -i /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/intermediate/02.RSP_SqueezeMeta_pooled.maskedrna.fasta -f gff -o /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/temp/02.RSP_SqueezeMeta_pooled.cds.gff.temp`

It gives me an output like:
```
-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Metagenomic, Phase:  Training
Initializing training files...done!
-------------------------------------
Request:  Metagenomic, Phase:  Gene Finding
Finding genes in sequence #1 (72557 bp)...done!
Finding genes in sequence #2 (35349 bp)...done!
Finding genes in sequence #3 (31685 bp)...done!
Finding genes in sequence #4 (30667 bp)...done!
Finding genes in sequence #5 (28821 bp)...done!
Finding genes in sequence #6 (25776 bp)...done!
Finding genes in sequence #7 (23203 bp)...done!
Finding genes in sequence #8 (22956 bp)...done!
Finding genes in sequence #9 (22219 bp)...done!
Finding genes in sequence #10 (21832 bp)...done!
Finding genes in sequence #11 (20909 bp)...done!
Finding genes in sequence #12 (20579 bp)...done!
Finding genes in sequence #13 (20303 bp)...done!
Finding genes in sequence #14 (19237 bp)...done!
Finding genes in sequence #15 (19043 bp)...done!
Finding genes in sequence #16 (18384 bp)...done!
Finding genes in sequence #17 (18240 bp)...done!
Finding genes in sequence #18 (17848 bp)...done!
Finding genes in sequence #19 (17817 bp)...done!
Finding genes in sequence #20 (17542 bp)...done!
Finding genes in sequence #21 (17007 bp)...done!
Finding genes in sequence #22 (16962 bp)...done!
Finding genes in sequence #23 (16677 bp)...done!
Finding genes in sequence #24 (16420 bp)...done!
```

And writes into `02.RSP_SqueezeMeta_pooled.cds.gff.temp`:
```
##gff-version  3
# Sequence Data: seqnum=1;seqlen=72557;seqhdr="megahit_1"
# Model Data: version=Prodigal.v2.6.3;run_type=Metagenomic;model="8|Bacteroides_fragilis_NCTC_9343|B|43.2|11|0";gc_cont=43.20;transl_table=11;uses_sd=0
megahit_1	Prodigal_v2.6.3	CDS	47	1591	161.1	-	0	ID=1_1;partial=00;start_type=ATG;rbs_motif=AACAA;rbs_spacer=11bp;gc_cont=0.461;conf=100.00;score=160.45;cscore=145.34;sscore=15.12;rscore=6.36;uscore=5.29;tscore=4.12;
megahit_1	Prodigal_v2.6.3	CDS	1610	1747	3.0	+	0	ID=1_2;partial=00;start_type=ATG;rbs_motif=TAAA;rbs_spacer=15bp;gc_cont=0.435;conf=66.53;score=2.99;cscore=-2.23;sscore=5.22;rscore=2.92;uscore=0.57;tscore=2.23;
megahit_1	Prodigal_v2.6.3	CDS	1888	2181	34.0	-	0	ID=1_3;partial=00;start_type=ATG;rbs_motif=TAA;rbs_spacer=11bp;gc_cont=0.384;conf=99.97;score=35.15;cscore=23.10;sscore=12.05;rscore=8.35;uscore=-1.57;tscore=4.12;
megahit_1	Prodigal_v2.6.3	CDS	2193	2945	62.0	-	0	ID=1_4;partial=00;start_type=ATG;rbs_motif=TAAAAA;rbs_spacer=9bp;gc_cont=0.390;conf=100.00;score=62.72;cscore=40.21;sscore=22.52;rscore=12.15;uscore=5.55;tscore=4.12;
megahit_1	Prodigal_v2.6.3	CDS	3000	3230	14.7	-	0	ID=1_5;partial=00;start_type=ATG;rbs_motif=AAAAA;rbs_spacer=7bp;gc_cont=0.502;conf=96.71;score=14.71;cscore=2.25;sscore=12.46;rscore=5.70;uscore=3.00;tscore=3.76;
megahit_1	Prodigal_v2.6.3	CDS	3308	4834	103.1	-	0	
```

But when I launch the same command through the queue on the server (qsub), it gives me an error:
`/var/spool/torque/mom_priv/jobs/9965912.SC: line 9: 22465 Segmentation fault      (core dumped) /beegfs/work/graaf20/SqueezeMeta/SqueezeMeta/bin/prodigal -m -p meta -i /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/intermediate/02.RSP_SqueezeMeta_pooled.maskedrna.fasta -f gff -o /beegfs/work/graaf20/Rusitec_meta/RSP_SqueezeMeta_pooled/temp/02.RSP_SqueezeMeta_pooled.cds.gff.temp`

**Comment by jtamames** [comment] 2021-09-06 13:34
Ok, so the first result is the expected one, prodigal is working correctly and your contig file is ok. So the problem is in the server side. How did you install SqueezeMeta in the server? Did you check that the installation was correct (running the test_install script)?

**Comment by timyerg** [comment] 2021-09-06 13:40
I got errors trying to install from conda, so I created a new environment and installed all dependencies manually:
```
!conda install -y -c bioconda numpy
!conda install -y -c bioconda scipy
!conda install -y -c bioconda cython
!conda install -y -c bioconda future
!conda install -y -c bioconda pandas
!conda install -y -c bioconda matplotlib
!conda install -y -c bioconda dendropy
!conda install -y -c bioconda pysam
!conda install -y -c bioconda perl=5.26
!conda install -y -c bioconda perl-tie-ixhash
!conda install -y -c bioconda perl-dbd-mysql
!conda install -y -c bioconda perl-dbd-sqlite
!conda install -y -c bioconda perl-lwp-simple
!conda install -y -c bioconda perl-xml-libxml
!conda install -y -c bioconda perl-xml-parser
!conda install -y -c bioconda openjdk
!conda install -y -c bioconda ruby=2.5
!conda install -y -c bioconda r=3.6
!conda install -y -c bioconda r-ggplot2
!conda install -y -c bioconda r-reshape2
!conda install -y -c bioconda r-doMC
!conda install -y -c bioconda tree
!conda install -y -c bioconda r-data.table
!conda install -y -c bioconda bioconductor-pathview
!conda install -y -c r r-stringi
!conda install -y -c anaconda expat-devel-cos6-x86_64
!conda install -y -c conda-forge expat
!cpan Linux::MemInfo
!conda config --add channels conda-forge
!conda config --set channel_priority strict
!conda install -y expat
!cpan YAML
!cpan XML::Parser
```
Cloned the rep:
`!git clone https://github.com/jtamames/SqueezeMeta.git`
Installed packages:
```
!R CMD INSTALL SqueezeMeta/bin/DAS_Tool/package/DASTool_1.1.1.tar.gz
!R CMD INSTALL SqueezeMeta/lib/SQMtools
```
 and tested installation with test_install:
```
Checking the OS
	linux OK

Checking that tree is installed
	tree --help OK

Checking that ruby is installed
	ruby -h OK

Checking that java is installed
	java -h OK

Checking that all the required perl libraries are available in this environment
	perl -e 'use Term::ANSIColor' OK
	perl -e 'use DBI' OK
	perl -e 'use DBD::SQLite::Constants' OK
	perl -e 'use Time::Seconds' OK
	perl -e 'use Tie::IxHash' OK
	perl -e 'use Linux::MemInfo' OK
	perl -e 'use Getopt::Long' OK
	perl -e 'use File::Basename' OK
	perl -e 'use DBD::SQLite' OK
	perl -e 'use Data::Dumper' OK
	perl -e 'use Cwd' OK
	perl -e 'use XML::LibXML' OK
	perl -e 'use XML::Parser' OK
	perl -e 'use Term::ANSIColor' OK

Checking that all the required python libraries are available in this environment
	python3 -h OK
	python3 -c 'import numpy' OK
	python3 -c 'import scipy' OK
	python3 -c 'import matplotlib' OK
	python3 -c 'import dendropy' OK
	python3 -c 'import pysam' OK
	python3 -c 'import pandas' OK
	python3 -c 'import cython' OK
	python3 -c 'import future' OK

Checking that all the required R libraries are available in this environment
	R -h OK
	R -e 'library(doMC)' OK
	R -e 'library(ggplot2)' OK
	R -e 'library(data.table)' OK
	R -e 'library(reshape2)' OK
	R -e 'library(pathview)' OK
	R -e 'library(DASTool)' OK
	R -e 'library(SQMtools)' OK

Checking that SqueezeMeta is properly configured... checking database in /beegfs/work/graaf20/Databases/SqueezeMeta/db
	nr.db OK
	CheckM manifest OK
	LCA_tax DB OK

All checks successful

```

**Comment by fpusan** [comment] 2021-09-06 14:21
Does the error also happen when you request an interactive session in your cluster and run prodigal there?

**Comment by timyerg** [comment] 2021-09-06 15:05
Still getting the same errors with interactive job.

Recompiled prodigal still no success =(

**Comment by fpusan** [comment] 2021-09-06 15:41
It fails even with prodigal compiled in the same environment?
Then it's hard to tell. The fact that it works outside the cluster makes me think that this is a problem unrelated to SqueezeMeta. You might want to discuss that with your cluster admins, maybe they can help.
For now maybe you can try running step 3 outside the cluster, copying the results and then trying to restart from step 4 back in the cluster...

**Comment by timyerg** [comment] 2021-09-07 09:34
Since I am providing custom assemblies, actually, prodigal is the first step that is run with precompiled binaries provided by SqueezeMeta.
I launched test data analysis as descibed in the tutorial and got similar errors:
```
[1m
SqueezeMeta v1.4.0, May 2021 - (c) J. Tamames, F. Puente-Sánchez CNB-CSIC, Madrid, SPAIN

Please cite: Tamames & Puente-Sanchez, Frontiers in Microbiology 9, 3349 (2019). doi: https://doi.org/10.3389/fmicb.2018.03349

[0mRun started Tue Sep  7 10:55:04 2021 in coassembly mode
Now creating directories
Reading configuration from /beegfs/work/graaf20/Rusitec_meta/Hadza/SqueezeMeta_conf.pl
Reading samples from /beegfs/work/graaf20/Rusitec_meta/Hadza/data/00.Hadza.samples
2 samples found: SRR1927149 SRR1929485

Now merging files
[34m[16 seconds]: STEP1 -> RUNNING CO-ASSEMBLY: 01.run_assembly.pl (megahit)
[0m  Running assembly with megahit
[31mStopping in STEP1 -> 01.run_assembly.pl. Program finished abnormally
[0m[31m
  If you don't know what went wrong or want further advice, please look for similar issues in https://github.com/jtamames/SqueezeMeta/issues
  Feel free to open a new issue if you don't find the answer there. Please add a brief description of the problem and upload the /beegfs/work/graaf20/Rusitec_meta/Hadza/syslog file (zip it first)
[0m
```
```
Error running command:    /home/ho/ho_genetics/ho_graaf20/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /beegfs/work/graaf20/Rusitec_meta/Hadza/data/raw_fastq/par1.fastq.gz -2 /beegfs/work/graaf20/Rusitec_meta/Hadza/data/raw_fastq/par2.fastq.gz -t 12 -o /beegfs/work/graaf20/Rusitec_meta/Hadza/data/megahit >> /beegfs/work/graaf20/Rusitec_meta/Hadza/syslog 2>&1 at /home/ho/ho_genetics/ho_graaf20/miniconda3/envs/SqueezeMeta/SqueezeMeta/scripts/01.run_assembly.pl line 119.
Died at /home/ho/ho_genetics/ho_graaf20/miniconda3/envs/SqueezeMeta/bin/SqueezeMeta.pl line 1367.
```
[syslog.zip](https://github.com/jtamames/SqueezeMeta/files/7120445/syslog.zip)

Completely reinstalled SqueezeMeta - still same errors.

When runing on the server without submiting (directly from jupyter):
```
/home/ho/ho_genetics/ho_graaf20/miniconda3/envs/SqueezeMeta/SqueezeMeta/bin/megahit/megahit  -1 /beegfs/work/graaf20/Rusitec_meta/Hadza/data/raw_fastq/par1.fastq.gz -2 /beegfs/work/graaf20/Rusitec_meta/Hadza/data/raw_fastq/par2.fastq.gz -t !1 -o /beegfs/work/graaf20/Rusitec_meta/Hadza/data/megahit1 >> /beegfs/work/graaf20/Rusitec_meta/Hadza/syslog 2>&1
 megahit is working.
```

When submiting the same command as a job, job dies without any logs.
In the working directory, each time core.XXXX files appears after failures.

Looks that I can not run any command that involves binaries from SqueezeMeta bin, meanwhile all of the are working when accessed without submitting a job (I am activating SqueezeMeta in submited jobs).

Thats strange...

**Comment by fpusan** [comment] 2021-09-07 10:48
The core.XXXX files are core dumps which makes me subset that you had another segfault...
This is really weird. I don't think we've seen this problem before (we use the pre-built binaries from the authors in both cases, so they should be working).
What linux version (and kernel) do you have in your cluster?
In any case you should contact your cluster administrators, maybe they know what could be going on...

**Comment by timyerg** [comment] 2021-09-07 11:06
Yeah, I will refer to admins with this issue
Here are the details:
Operating System: RHEL 7
Queuing System: MOAB / Torque
Linux version 3.10.0-1160.31.1.el7.x86_64  (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )

Thank you all for your help, will update you if somehow the issue will be resolved

**Comment by fpusan** [comment] 2021-09-07 11:07
Yeah, please let me know!
RHEL 7 should be similar to CentOS 7, and I've tested SQM there...
Still, let's see what the admins have to say...

**Comment by fpusan** [comment] 2021-11-11 15:43
Hope that you managed to make it work recompiling when needed. Closing the issue, feel free to reopen if you have further problems

**Closed by fpusan** 2021-11-11 15:43 UTC

**Comment by timyerg** [comment] 2022-02-28 14:36
Hi!
Just wanted to update you and whoever will be reading it about this issue that I had a while ago.
I am running a new dataset and updated SqueezeMeta. Encountered the same issue, but this time even manual installation did not work for me on server. After some investigation I discovered that the problem was in the wrong version of Python - conda used system Python instead of Python in the envirinment. This issue is described [here](https://github.com/conda/conda/issues/9392#issue-514911258).
The solution was to add this lines to .bashrc file:
```
echo 'conda deactivate' >> ~/.bashrc 
echo 'conda activate' >> ~/.bashrc 
source ~/.bashrc
```

at the end of

**Comment by fpusan** [comment] 2022-02-28 14:38
Thanks for reporting this!
