### ISSUE TITLE
Error while running sqm2tables.py

### ISSUE THREAD

**Issue by chandnisidhu** [jtamames/SqueezeMeta#298] opened 2021-05-14 21:25 UTC
Hi,

I am getting the following error while running sqm2tables.py.

File "/Softwares/SqueezeMeta-master/utils/sqm2tables.py", line 214, in <module> main(parse_args()) File "/Softwares/SqueezeMeta-master/utils/sqm2tables.py", line 70, in main args.trusted_functions, args.ignore_unclassified, customMethods, data_dir) File "/Softwares/SqueezeMeta-master/utils/../lib/utils.py", line 227, in parse_orf_table orfs['tpm'] = tpm(orfs) File "/Softwares/SqueezeMeta-master/utils/../lib/utils.py", line 153, in tpm fun_avgLengths['Unmapped'] = sum(funDict['lengths'].values()) / sum(funDict['copies'].values()) # Just use the avg length of all functions for this. ZeroDivisionError: division by zero

Thank you in advance!

Chandni

**Comment by fpusan** [comment] 2021-05-17 08:38
Hi!
Any chance you can share your SqueezeMeta project with me via google drive, wetransfer, etc?
I would need the SqueezeMeta_conf.pl file, the results folder and the intermediate folder
Best,
Fernando

**Comment by chandnisidhu** [comment] 2021-05-17 09:06
Hi,

I am re-running the whole project with the updated version of SQM. It will most probably be finished by tomorrow. Previously, I mixed scripts from two versions which might have caused this issue, let me finish with this and I will update you tomorrow.

Best,
Chandni

**Comment by chandnisidhu** [comment] 2021-05-17 09:07
Hi,

I am re-running the whole project with an updated version of SQM. It will most probably be finished by tomorrow. Previously, I mixed scripts from two different versions which might have caused this issue, let me finish with this and I will update you tomorrow.

Best,
Chandni

**Comment by fpusan** [comment] 2021-05-17 14:13
Ok, let me know!

**Comment by chandnisidhu** [comment] 2021-05-17 15:12
Hello,

It didn't work. I got the same error as mentioned above. I am sharing the files you've asked for. 

The other thing I want to mention here is that I used external bins here. I also mentioned "--nomaxbin" in the script and it did proceed with that anyhow. I have replaced bins in DAS directory with my external bins and restart the pipeline from step 17. You can also find syslog in the same folder. The name of contigs in the external bins were consistent with the contig names in the assembly. 

Best,
Chandni

**Comment by fpusan** [comment] 2021-05-18 09:40
Hi,
The "Length NT" column in the `csidhu_SQM/results/13.SQM_2020_MAGs.orftable` is completely empty, so `sqm2tables.py` crashes when trying to calculate the coverage of the functions. This is thus not an issue with `sqm2tables.py`. I'd say that it's related to the shenanigans with the custom gene calling software that you and @jtamames  discussed in #280 .
Best,
Fernando

**Comment by fpusan** [comment] 2021-05-18 09:44
```
(SqueezeMeta) fer@kadath:~/data/csidhu_SQM/results$ head -n1 *faa
>contig_9401_A_MB111_1-267
(SqueezeMeta) fer@kadath:~/data/csidhu_SQM/results$ head -n1 *fna
>contig_9401_A_MB111_1_267
```
I'd say that you also have to correct the contig names in the `03.*.fna` file, same way you did for the `03.*.faa` file. Then repeat step 13 and check whether the `Length NT` column of file `13.SQM_2020_MAGs.orftable`  contains data.

**Comment by chandnisidhu** [comment] 2021-05-18 09:49
Hello,

I figured it out yesterday and I did repeat step 13 but it didn't work. However, sqm2tables.py worked perfectly well with my other project.

**Comment by fpusan** [comment] 2021-05-18 09:50
What didn't work exactly, and what was the new error message you got?

**Comment by chandnisidhu** [comment] 2021-05-18 09:50
The same one. 

`File "/Softwares/SqueezeMeta-master/utils/sqm2tables.py", line 214, in main(parse_args()) File "/Softwares/SqueezeMeta-master/utils/sqm2tables.py", line 70, in main args.trusted_functions, args.ignore_unclassified, customMethods, data_dir) File "/Softwares/SqueezeMeta-master/utils/../lib/utils.py", line 227, in parse_orf_table orfs['tpm'] = tpm(orfs) File "/Softwares/SqueezeMeta-master/utils/../lib/utils.py", line 153, in tpm fun_avgLengths['Unmapped'] = sum(funDict['lengths'].values()) / sum(funDict['copies'].values()) # Just use the avg length of all functions for this. ZeroDivisionError: division by zero`

**Comment by chandnisidhu** [comment] 2021-05-18 09:51
Everything worked fine except last sqm2tables.py step.

**Comment by jtamames** [comment] 2021-05-18 09:57
> Hello,
> 
> I figured it out yesterday and I did repeat step 13 but it didn't work. However, sqm2tables.py worked perfectly well with my other project.

But did you check the 13*orftable file created this way? Could you check if the field "Length NT" is empty in that table?

**Comment by chandnisidhu** [comment] 2021-05-18 09:59
Yes it is empty.

**Comment by jtamames** [comment] 2021-05-18 10:04
Ok, that's why. But you were also running it with the --D flag, right? If so, the change must be done in `08.*.fna` instead, which if used for including the new ORFs derived from the blastx search in 08.

**Comment by chandnisidhu** [comment] 2021-05-18 10:07
No, here I am not running it with blastx.

**Comment by fpusan** [comment] 2021-05-18 10:17
Can you share your samples file with us?

**Comment by jtamames** [comment] 2021-05-18 10:17
Then the problem is in the 03.\*.fna file. Could you check again that the names in the 03.\*.fna file match the names in the 13.\*.orftable file, and that you recreated the 13.\*.orftable file correctly?

**Comment by chandnisidhu** [comment] 2021-05-18 10:22
Okay..I found the error I guess..

faa: >contig_9401_A_MB111_1-267
fna: >contig_9401_A_MB_111_1-267

extra "-" . I will correct and re-run step 13.
Thank you so much. I will let you know soon.

**Comment by chandnisidhu** [comment] 2021-05-18 11:29
Hello,

It worked :)

Thanks a lot.

Chandni

**Comment by fpusan** [comment] 2021-05-18 12:07
Glad to hear. Closing issue

**Closed by fpusan** 2021-05-18 12:07 UTC
