### ISSUE TITLE
mappingstat file didn't list the total number of reads

### ISSUE THREAD

**Issue by EricRaes** [jtamames/SqueezeMeta#125] opened 2020-07-09 00:58 UTC
Hi guys! 

Hope you are having a good week.

I hope you would be bale to shed some light on my question below.

I am just detailing my workflow:

1. I have illumina shotgun data paired 150bp.
2. I removed the Illumina adapters from the R1 and R2 reads using the Trimmomatic software (with the TruSeq3-PE-2.fa:2:30:10:2:keepBothReads setting;2.
3. I then tried to merge R1 and R2 reads from each sample with ‘bbmerge’ 
4. The unmerged reads were then QC’ed with Trimmomatic software with the following settings: leading:3, trailing:3, slidingwindow:10:15, minlen:50bp
5. I then concatenated merged and unmerged sequences into one file and
6. ran sqm_reads on this concatenated file ( so no R1 or R2 files anymore; just one big file).

I run each sample in batch mode, slurm output file looked ok; exept the error: "rm: cannot remove 'rc.txt': No such file or directory"
[slurm-Sample A.txt](https://github.com/jtamames/SqueezeMeta/files/4893880/slurm-Sample.A.txt)

All the files (e.g., out.alreads, out.allreads.funcog, out.allreads.funkegg,..) are in my output folder but the mappingstat file didn't list the total number of reads
[Sample A.out.mappingstat.txt](https://github.com/jtamames/SqueezeMeta/files/4893889/Sample.A.out.mappingstat.txt)

When I try to get tables with sqmreads2tables.py I get the below error:  File/home/rae02e/.conda/envs/SqueezeMeta/SqueezeMeta/utils/sqmreads2tables.py", line 58, in main
    samples[sample] += int(total_reads)
ValueError: invalid literal for int() with base 10: ''

Any ideas why the mappingstat file didn't list the total number of reads? I assume that would be the problem in making the tables?

The sqm_reads worked fine when I used QC'ed R1 and R2 reads but not when I concatenated then into one file with merged and unmerged reads.

Many thanks in advance!!

**Comment by jtamames** [comment] 2020-07-09 11:14
Hello Eric

Thanks for reporting this one. I have already found the bug and will fix it today after checking that the patch is working properly.

Best,
Javier

**Comment by jtamames** [comment] 2020-07-09 11:28
Hopefully fixed in 013765eb4c9deeb524a51ec5504d377c06bf1f2f

Run your `sqm_reads.pl` again using the same project name, and adding `--nodiamond` to skip the Diamond runs that you already did.

Hope it works, please tell me otherwise.
Best,
Javier

**Comment by EricRaes** [comment] 2020-07-11 01:09
Hi Javier,

Unfortunately not working on my end. 

I renamed my old conda environment Squeezemeta, and did a new conda create -n SqueezeMeta -c bioconda -c fpusan squeezemeta install.

I reran the sqm_reads.pl with --nodiamond and try to combine tables but the mappingstat file remains empty for the total reads which results in the below error:

Creating tables for project Sample_A:

Traceback (most recent call last):
  File "/home/rae02e/.conda/envs/SqueezeMeta/SqueezeMeta/utils/sqmreads2tables.py", line 220, in <module>
    main(parse_args())
  File "/home/rae02e/.conda/envs/SqueezeMeta/SqueezeMeta/utils/sqmreads2tables.py", line 69, in main
    samples[sample] += int(total_reads)
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/home/rae02e/.conda/envs/SqueezeMeta/SqueezeMeta/utils/combine-sqm-tables.py", line 312, in <module>
    main(parse_args())

Many thanks in advance for your help!
Cheers,
Eric

**Comment by fpusan** [comment] 2020-07-11 07:39
Hi Eric,

Bugfixes do not reach conda until we release a new version.

Try downloading the patched script from https://github.com/jtamames/SqueezeMeta/blob/develop/utils/sqm_reads.pl
and using it to replace `/home/rae02e/.conda/envs/SqueezeMeta/SqueezeMeta/utils/sqm_reads.pl`.

Best,

Fernando

**Comment by EricRaes** [comment] 2020-07-11 07:48
ah ok! Will download and replace. Thanks again for your swift reply!
Have a good weekend!

**Comment by EricRaes** [comment] 2020-07-11 08:31
Hey Javier,

Sorry for bugging, this might be a trivial question but:

I went into the /home/rae02e/.conda/envs/SqueezeMeta/SqueezeMeta/utils/ folder and did:

module load aria2
aria2c https://github.com/jtamames/SqueezeMeta/blob/013765eb4c9deeb524a51ec5504d377c06bf1f2f/utils/sqm_reads.pl

which looks ok:

07/11 18:16:42 [NOTICE] Downloading 1 item(s)
07/11 18:16:43 [NOTICE] Download complete: /home/rae02e/.conda/envs/SqueezeMeta_new_missing_scripts/SqueezeMeta/utils/sqm_reads.pl

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
72322e|OK  |   490KiB/s|/home/rae02e/.conda/envs/SqueezeMeta_new_missing_scripts/SqueezeMeta/utils/sqm_reads.pl

Status Legend:
(OK):download completed.

made the file executable with chmod a+x sqm_reads.pl

and then redid the sqm_reads run but got the error:
/home/rae02e/.conda/envs/SqueezeMeta/bin/sqm_reads.pl: line 6: syntax error near unexpected token `newline'
/home/rae02e/.conda/envs/SqueezeMeta/bin/sqm_reads.pl: line 6: `<!DOCTYPE html>'

I also didn't understand why it went looking in the /bin folder rather than the /utils one 

Apologies if this might be easy and I am not getting it :-) thanks in advance for your help!!

**Comment by fpusan** [comment] 2020-07-11 08:45
There are symlinks to all the SQM scripts inside the bin directory within the conda environment.

Regarding the actual error message, it looks like you are using bash instead of perl for running it.

Try invoking it with `perl /home/rae02e/.conda/envs/SqueezeMeta/bin/sqm_reads.pl <YOUR ARGUMENTS>` and see if the error disappears. No idea why it's happening though...

**Comment by EricRaes** [comment] 2020-07-13 05:44
Thanks Fernando!! perl indeed did teh job and mappingstat file lists the total number of reads :-)

# Sample	File	                      Total Reads	Reads with hits to nr
62718_B1	62718_SQ_cat.fq	397495352	29128386

**Comment by fpusan** [comment] 2020-07-13 08:11
Glad to hear. Closing issue, will keep an eye open for any other problems regarding interpreter selection...

**Closed by fpusan** 2020-07-13 08:11 UTC
Labels: SQM_reads, sqm2tables

**Comment by jtamames** [comment] 2020-07-13 08:18
Eric, looks like you have a very few number of reads with hits (7% aprox). Any idea on why that is happening? It is unusual for an Illumina run.

Best,
Javier

**Comment by EricRaes** [comment] 2020-07-14 02:36
Hi Javier,

Many thanks for your follow up.

When I use R1 and R2 reads (not merged) and run sqm_reads I get around ~50% of the reads mapped to nr. (see mappingsstat file: 
[62718_SQ_cat_mappingstat_with_R1_and_R2.txt](https://github.com/jtamames/SqueezeMeta/files/4916156/62718_SQ_cat_mappingstat_with_R1_and_R2.txt).

When I merge R1 and R2  (fastqc check on this merged file) shows that there are 99373841 sequences (which sum up to the R1 and R2 from the above mappingstat file)
![image](https://user-images.githubusercontent.com/12810854/87373600-5009ab80-c5cd-11ea-9b92-49308aec774d.png)

When I merge R1 and R2 reads, and just use one merged.fq file for the sqm_reads analysis the number of total sequences in the mappingstat file doesn't equal the input sequences (e.g., those listed in the fastqc screenshot)
[62718_merged_R1_R2_mappingstat.txt](https://github.com/jtamames/SqueezeMeta/files/4916197/62718_merged_R1_R2_mappingstat.txt)

Would you have any ideas why the number of sequences isn't equal ?

Many, many thanks!

Best regards,
Eric









 but the read in the mappingstat file are not the same in the sample file.

E.g., my

**Comment by jtamames** [comment] 2020-07-15 15:16
Hello Eric
We were taking a look and we don't understand what is going on. In the merged file, you have double number of reads than in the single files, that makes me think that you concatenated the two files instead. If it was a merge, I would expect the same number of merged reads than in each of the single ones. Also the read sizes in the merged file are rather variable. this is also unexpected (did you trim the files previously?)
And then, no idea why the number of reads in the merged file is way higher (397M when it should be 99M). But this number being roughly 4 times the number of expected sequences, makes me think something weird is going on with your fastq format. All issues should have been solved in the recent commit https://github.com/jtamames/SqueezeMeta/commit/013765eb4c9deeb524a51ec5504d377c06bf1f2f that I think you already have. Could you please:
-Paste the first few lines of the allreads file in the main results directory
-Change the extension of your file to fastq and run it again
Thanks!

Best,
Javier

**Comment by EricRaes** [comment] 2020-07-16 03:22
Hi Javier,

Thanks for your follow up!

Apologies I meant concatenate instead of merge.

When I use a dummy example as suggested (please see attached test.txt file - I couldn't attached the .fastq format; [test.txt](https://github.com/jtamames/SqueezeMeta/files/4929097/test.txt)) and run the pipeline everything works fine. The mappingstat file gives 25 sequences and 18 annotated.

However, when I did a _'cat test.fastq copy.test.fastq > test_cat.fq'_ ([test_cat.txt](https://github.com/jtamames/SqueezeMeta/files/4929101/test_cat.txt)) which should result in 50 sequences in the mappingstat file the results are again inflated by a factor 4 and the mappingstat file lists 200 sequences in stead of 50.

Could you please let me know how the number of sequences are calculated? The Diamond .m8 file only lists the sequences which could be mapped, not the total.

Again, many thanks in advance!
Best regards,
Eric

ps. mappingstat test.fastq 
[test.out.mappingstat.txt](https://github.com/jtamames/SqueezeMeta/files/4929113/test.out.mappingstat.txt)

pps. mappingstat from two concatenated test files 
[test_cat.out.mappingstat.txt](https://github.com/jtamames/SqueezeMeta/files/4929116/test_cat.out.mappingstat.txt)

**Comment by jtamames** [comment] 2020-07-16 11:27
Hello Eric
The problem is the extension. It deals ok with fastq files, but fails with fq files. I supposedly fixed the issue in the last commit, did you update your sqm_reads.pl? If not, please do so. If you did, please tell me because then obviously my fix didn't work
Best,
Javier

**Comment by EricRaes** [comment] 2020-07-17 05:43
Ok, thanks Javier! 

Yes, I updated the sqm_reads.pl and used your patch 013765e. This fixed and added the number of total sequences which wasn't there before, but you still end up with total reads which are 4x as high. Have a good weekend!

**Comment by jtamames** [comment] 2020-07-17 18:49
Hopefully fixed in https://github.com/jtamames/SqueezeMeta/commit/8786c54eb55ce88dbcd4739dabf2d7d14fa054b6
Very silly thing indeed. Could you try it now, Eric?

Thanks!

**Comment by EricRaes** [comment] 2020-07-20 07:57
Hi guys,

Hope you had a good weekend! 

Works fine now :-)
