### ISSUE TITLE
Error on STEP 16

### ISSUE THREAD

**Issue by alopcat** [jtamames/SqueezeMeta#51] opened 2019-11-26 14:42 UTC
Good evening. I'm running a test with the data provided but having some issues with step 16.

I'm using the restart.pl script
`module load cesga/2018 gcccore/6.4.0 gcc/6.4.0 perl/5.28.1 jdk/8u181 ruby/2.6.3  $LUSTRE/Adri/Squeeze2/SqueezeMeta/scripts/restart.pl testing48`

but keep getting this error 
`[0 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
Execution halted
Can't open /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_DASTool_bins directory`

I had already installed the R packages needed (ggplot2, data.table, doMC and DASTool) but testing48_DASTool_bins won't appear in the directory. 
The DASTool.log shows the following
`predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22`

Thank you very much for your time.

**Comment by jtamames** [comment] 2019-11-26 15:27
Hi Adrian
Could you please do ls -ltr of the directory results/DAS and copy the result?
Also, could you please run pullseq in the SqueezeMeta/bin directory and tell us the result?
Best,
Javier

**Comment by alopcat** [comment] 2019-11-26 15:48
Thank you very much for your reply.

The ls -ltr showed the following:
[otiniasm@c6601 DAS]$ ls -ltr
total 109108
-rw-r--r-- 1 otiniasm otras    106346 Nov 26 16:33 metabat2.table
-rw-r--r-- 1 otiniasm otras   1165064 Nov 26 16:33 maxbin.table
-rw-r--r-- 1 otiniasm otras 101034414 Nov 26 16:37 testing48_proteins.faa
-rw-r--r-- 1 otiniasm otras       114 Nov 26 16:37 testing48_DASTool.log
-rw-r--r-- 1 otiniasm otras    191602 Nov 26 16:37 testing48_proteins.faa.bacteria.scg
-rw-r--r-- 1 otiniasm otras     60194 Nov 26 16:38 testing48_proteins.faa.archaea.scg
-rw-r--r-- 1 otiniasm otras   9151677 Nov 26 16:38 testing48.seqlength

I run one of the files provided through pullseq and got the following
[otiniasm@c6601 bin]$ ./pullseq -i /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/raw/SRR1927149_1.fastq.gz -t
Total output: 14834811
Total excluded: 0
[otiniasm@c6601 bin]$

**Comment by fpusan** [comment] 2019-11-26 15:57
Just to keep discarding possibilities, see #29, in which there were two versions of R coexisting in the cluster. The `R` and `Rscript` commands actually pointed to two different installations, thus the libraries installed using `R` were not available when DAStool launched subprocesses via `Rscript`.

Does which R and which Rscript point to the same installation?

What happens if you create a short script

```
.libPaths()
library(doMC)
```
and run it with `Rscript test.R`?

Does it find the package?
Does it show the same paths as running .libPaths() from the interactive R console?

**Comment by alopcat** [comment] 2019-11-26 16:31
It seems like R and Rscript are in the same directory:
[otiniasm@fs6804 Adri]$ which R
/opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/R/3.6.0/bin/R
[otiniasm@fs6804 Adri]$ which Rscript
/opt/cesga/easybuild-cesga/software/Compiler/gcc/6.4.0/R/3.6.0/bin/Rscript

Running the file gives this result.
[otiniasm@c6601 test]$ Rscript test.R
[1] "/mnt/netapp2/Home_FT2/home/otras/ini/asm/R/x86_64-pc-linux-gnu-library/3.6"              
[2] "/mnt/netapp1/Optcesga_FT2_RHEL7/easybuild-cesga/software/Compiler/gcc/6.4.0/R/3.6.0/lib64/R/library"
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel

Running it from the console shows the following:

[1] "/mnt/netapp2/Home_FT2/home/otras/ini/asm/R/x86_64-pc-linux-gnu-library/3.6"              
[2] "/mnt/netapp1/Optcesga_FT2_RHEL7/easybuild-cesga/software/Compiler/gcc/6.4.0/R/3.6.0/lib64/R/library"

Thank you.

**Comment by fpusan** [comment] 2019-11-26 16:59
Can you try running the script 16 directly?

`$LUSTRE/Adri/Squeeze2/SqueezeMeta/scripts/16.dastool.pl testing48`

What's the output?

Also can you check if a line with `print "$das_command\n";` is present near the end of your version of the script?

**Comment by alopcat** [comment] 2019-11-27 08:37
Could this be the line you mentioned?
`print "Running DAS Tool for $methods\n";
 print "$das_command\n";
my $ecode = system $das_command;
if($ecode!=0) { die "Error running command:    $das_command"; }
`

Also, I tried running the script directly and got the following error:
`Creating tables of contigs in bins... done
Running DAS Tool for maxbin,metabat2
LD_LIBRARY_PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../lib PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin:$PATH /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table -l maxbin,metabat2 -c /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 --db_directory /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db
Running DAS Tool using 12 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg': No such file or directory
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg': No such file or directory
rm: cannot remove '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.all.b6': No such file or directory
single copy gene prediction using diamond failed. Aborting
Error running command:    LD_LIBRARY_PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../lib PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin:$PATH /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table -l maxbin,metabat2 -c /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 --db_directory /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db at /mnt/lustre/scratch//home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/16.dastool.pl line 66.
`

**Comment by fpusan** [comment] 2019-11-27 11:48
Hopefully fixed in fd03533
Let me know if it works. This commit also adds some extra logging, so we'll have more info if things keep failing.

**Comment by alopcat** [comment] 2019-11-27 12:38
Seems that the error is being persistent. I changed what is suggested in the commit but got the following: 
`[0 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/result    s/DAS/testing48_proteins.faa.scg': No such file or directory
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/result    s/DAS/testing48_proteins.faa.scg': No such file or directory
Error running command:    LD_LIBRARY_PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/script    s/../lib PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin:$PATH /mnt/lustre/s    cratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /mnt/lustre/scratch/home/    otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/hom    e/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table -l maxbin,metabat2     -c /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48    .fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /mnt/lustre/scratch/home/otras/ini/    asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 --db_directory /mnt/lustre/scratch/h    ome/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db at /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/    SqueezeMeta/scripts/../scripts/16.dastool.pl line 66.
ERROR in STEP16-> 16.dastool.pl
Can't open /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/    testing48_DASTool_bins directory
`

**Comment by fpusan** [comment] 2019-11-27 13:32
You should now have an extra logfile in 

`/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_DASTool_scg.log`

What are the contents?

**Comment by alopcat** [comment] 2019-11-27 14:32
I have attached it as it is quite long.
[testing48_DASTool_scg.log](https://github.com/jtamames/SqueezeMeta/files/3897244/testing48_DASTool_scg.log)

**Comment by fpusan** [comment] 2019-11-27 15:16
From the log it seems that the subprocess that identifies the Single Copy Genes (scg_blank_diamond.rb) finished successfully for bacteria and archaea.

However the parent process (DAS_Tool) is not finding the files in the right place when trying to change their names (lines 383 and 386). Those files should have been produced by scg_blank_diamond.rb (which seemed to run ok).

I can not reproduce the error with the data I'm using. Can you remove the folder at `/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/` and run `$LUSTRE/Adri/Squeeze2/SqueezeMeta/scripts/16.dastool.pl testing48` again?

**Comment by alopcat** [comment] 2019-11-27 16:39
It keeps happening the same
`Creating tables of contigs in bins... done
Running DAS Tool for maxbin,metabat2
LD_LIBRARY_PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../lib PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin:$PATH /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table -l maxbin,metabat2 -c /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 --db_directory /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db
Running DAS Tool using 12 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg': No such file or directory
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg': No such file or directory
rm: cannot remove '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.all.b6': No such file or directory
single copy gene prediction using diamond failed. Aborting
Error running command:    LD_LIBRARY_PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../lib PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin:$PATH /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table -l maxbin,metabat2 -c /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 --db_directory /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db at /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/16.dastool.pl line 66.
`
And the log seems very similar
[testing48_DASTool_scg.log](https://github.com/jtamames/SqueezeMeta/files/3897874/testing48_DASTool_scg.log)

**Comment by fpusan** [comment] 2019-11-27 17:16
Yes, this bug seems quite persistent...

Please substitute the `.../SqueezeMeta/bin/DAS_Tool/DAS_Tool` and the `.../SqueezeMeta/bin/DAS_Tool/src/scg_blank_diamond.rb` scripts for the ones attached.

This should give us extra logging info, in particular which command is being used to call `scg_blank_diamond.rb`, and where is that script writing its results.

When you run script 16, there should be a line in the screen reading `Launching subprocess:  <command>`. Please let me know the content of that line, and also send the new `testing48_DASTool_scg.log `, which should now contain extra information.

**Comment by alopcat** [comment] 2019-11-28 12:17
The subprocess failing seems to be this one `Launching subprocess:    ruby /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/bin/DAS_Tool\/src/scg_blank_diamond\.rb diamond /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db\/bac.all.faa /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db\/bac.scg.faa /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db\/bac.scg.lookup 12`

Here I attach the log file

[testing48_DASTool_scg.log](https://github.com/jtamames/SqueezeMeta/files/3901585/testing48_DASTool_scg.log)

Thank you very much

**Comment by fpusan** [comment] 2019-11-28 12:25
What is the content (ls -ltr) of the DAS directory now?

**Comment by alopcat** [comment] 2019-11-28 14:32
It's the following 
[otiniasm@fs6804 DAS]$ ls -ltr
total 109468
-rw-r--r-- 1 otiniasm otras    106346 Nov 28 10:05 metabat2.table
-rw-r--r-- 1 otiniasm otras   1165064 Nov 28 10:05 maxbin.table
-rw-r--r-- 1 otiniasm otras 101034393 Nov 28 10:06 testing48_proteins.faa
-rw-r--r-- 1 otiniasm otras       114 Nov 28 10:06 testing48_DASTool.log
-rw-r--r-- 1 otiniasm otras    191602 Nov 28 10:06 testing48_proteins.faa.bacteria.scg
-rw-r--r-- 1 otiniasm otras     60230 Nov 28 10:07 testing48_proteins.faa.archaea.scg
-rw-r--r-- 1 otiniasm otras    365235 Nov 28 10:07 testing48_DASTool_scg.log
-rw-r--r-- 1 otiniasm otras   9151677 Nov 28 10:07 testing48.seqlength
[otiniasm@fs6804 DAS]$

**Comment by fpusan** [comment] 2019-11-28 16:30
This is rather obscure. Could you also send me the testing48_DASTool.log?

**Comment by fpusan** [comment] 2019-11-28 17:29
Since the `testing48.seqlength` file was created, it seems that the error is not in ruby script, but further down the DAS_Tool pipeline.

Please test with this version of `.../SqueezeMeta/bin/DAS_Tool/DAS_Tool`, and let me know what it prints.
[DAS_Tool.zip](https://github.com/jtamames/SqueezeMeta/files/3902677/DAS_Tool.zip)

**Comment by alopcat** [comment] 2019-11-29 07:55
I run the script 16 again and got this: 
`Creating tables of contigs in bins... done
Running DAS Tool for maxbin,metabat2
LD_LIBRARY_PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../lib PATH=/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin:$PATH /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/scripts/../bin/DAS_Tool/DAS_Tool -i /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table -l maxbin,metabat2 -c /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 12 -o /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 --db_directory /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db
Running DAS Tool using 12 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 0.9.22
Launching subprocess:    ruby /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/bin/DAS_Tool\/src/scg_blank_diamond\.rb diamond /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db\/bac.all.faa /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db\/bac.scg.faa /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/db\/bac.scg.lookup 12
Launching subprocess:      Rscript /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table maxbin,metabat2 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.bacteria.scg /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.archaea.scg /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 0.25 12 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48.seqlength TRUE TRUE false 0.6 0.5
Execution halted


`
The log is now longer and ends with a
`successfully finished
` 
at line 7243.
[testing48_DASTool_scg.log](https://github.com/jtamames/SqueezeMeta/files/3904234/testing48_DASTool_scg.log)

**Comment by alopcat** [comment] 2019-11-29 08:03
But deleting the results/DAS folder and running the Restart script ends with a [0 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
Execution halted
Can't open /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_DASTool_bins directory

**Comment by fpusan** [comment] 2019-11-29 08:05
The `Execution halted` message appears after trying to run the Rscript subprocess.

Do you get any specific error message when you run it directly?

` Rscript /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/maxbin.table,/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/metabat2.table maxbin,metabat2 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/01.testing48.fasta /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.bacteria.scg /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.archaea.scg /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48 0.25 12 /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test /mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48.seqlength TRUE TRUE false 0.6 0.5`

**Comment by alopcat** [comment] 2019-11-29 08:17
No, I'm only getting the `Execution halted` one

**Comment by fpusan** [comment] 2019-11-29 08:43
At least we now know where the problem is. Try the same comand, but replacing the last `false` with a `TRUE`. That should run the R script in debug mode. Do you get some more output?

**Comment by alopcat** [comment] 2019-11-29 09:02
I'm only having the execution halted message again. 
I have seen that the version I have of the DASTool package for R is the 1.1.2 but in your ReadMe file you propose the 1.1.1., could that be a problem?

**Comment by fpusan** [comment] 2019-11-29 09:05
Didn't you install the version that we redistribute with SqueezeMeta?

**Comment by alopcat** [comment] 2019-11-29 09:20
I had installed the 1.1.2 version directly from the Das_Tool repository. I have installed the one distributed with SqueezeMeta but I'm having the same error as before.

**Comment by fpusan** [comment] 2019-11-29 09:29
Please test using this version of the `/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/bin/DAS_Tool\/src/DAS_Tool.R` with extra logging. You should get some progress messages before the `Execution halted` message.

[DAS_Tool.R.gz](https://github.com/jtamames/SqueezeMeta/files/3904541/DAS_Tool.R.gz)

**Comment by alopcat** [comment] 2019-11-29 10:35
I just did it and got the following output

[Output.gz](https://github.com/jtamames/SqueezeMeta/files/3904792/Output.gz)

**Comment by fpusan** [comment] 2019-11-29 10:43
From the output you just sent me, it seems that the `DAS_Tool.R` ran ok this time, and that you got the bin folder created. Is that true?

**Comment by alopcat** [comment] 2019-11-29 10:56
Yes, it worked. Step 17 has just run correctly and it is on STEP 18 right now. Thank you very much for your help and sorry for any inconvenience.

**Comment by fpusan** [comment] 2019-11-29 10:57
Any idea of what was the problem, then?

**Comment by alopcat** [comment] 2019-11-29 11:08
Not at all, I just changed the 1.1.2 version of the DASTool package for the 1.1.1 provided by your git but the error kept appearing. 
It does not seem to be working correctly as STEP threw another error and checking the Step 16 output I got the following 
`mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg': No such file or directory
mv: cannot stat '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg': No such file or directory
rm: cannot remove '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove '/mnt/lustre/scratch/home/otras/ini/asm/Adri/Squeeze2/SqueezeMeta/databases/test/testing48/results/DAS/testing48_proteins.faa.all.b6': No such file or directory
`

**Comment by fpusan** [comment] 2019-11-29 11:22
We have not observed this kind of inconsistent behaviour before. We have checked that the different subprocesses (and at one point the whole STEP) can finish correctly, but most of the times you report the same error.

Might this due to some kind of disk quota in your cluster that you are very close to filling? That might explain the fact that scripts that apparently work well sometimes fail to create output files.

**Comment by jtamames** [comment] 2019-11-29 11:23
But then is it working? You said it is in step 18...

**Comment by alopcat** [comment] 2019-11-29 11:33
At one point the whole step 16 seemed to run correctly. The bin directory was generated but then in Step 18 it could not be located. It seems to be a problem on how I am running it in the cluster at this point. I am going to use another node to give the process more memory to run and will tell you the result as soon as possible.

**Comment by alopcat** [comment] 2019-12-02 08:26
It has run correctly by now. I did nothing besides what we discussed here: changing [6e3a5ac](https://github.com/jtamames/SqueezeMeta/commit/6e3a5ace43eaf7ec2d6a35365c2bcfceccf6afce) and reinstalling DASTool in its 1.1.1 version.
Thank you very much for your help.

**Comment by fpusan** [comment] 2019-12-02 10:16
Glad to hear that! Closing issue

**Closed by fpusan** 2019-12-02 10:16 UTC
