### ISSUE TITLE
Assistance 

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#387] opened 2021-11-15 15:06 UTC
Good day 

Just a follow up, after updating my squeezemeta it did run the program to completion, however now I have a missing file. I am missing step 17 the bin table. 

This is end of the syslog file 

[3 days, 8 hours, 46 minutes, 25 seconds]: STEP15 -> 15.bin_metabat2.pl
Creating abundance file in /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/metabat2/contigs.depth.txt
Running metabat2 : /apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/bin/metabat2 -t 24 -i /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/temp/bincontigs.fasta -a /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/metabat2/contigs.depth.txt -o /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/metabat2/metabat2 --saveTNF saved_1500.tnf --saveDistance saved_1500.dist

[3 days, 9 hours, 2 minutes, 19 seconds]: STEP16 -> 16.dastool.pl
Creating abundance file in /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/maxbin.table
Creating abundance file in /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/metabat2.table
Running DAS Tool for maxbin,metabat2: LD_LIBRARY_PATH=/apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/lib PATH=/apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/bin:$PATH /apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/maxbin.table,/nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/metabat2.table -l maxbin,metabat2 -c /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/01.Kinosha_sand_samples_coassembly_4.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 24 -o /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/Kinosha_sand_samples_coassembly_4 --db_directory /nlustre/data/SqueezeMeta/db --debug

[3 days, 9 hours, 13 minutes, 9 seconds]: STEP20 -> 20.getcontigs.pl
  Reading taxa for contigs information from /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/intermediate/09.Kinosha_sand_samples_coassembly_4.contiglog
  Reading GC & length from /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/01.Kinosha_sand_samples_coassembly_4.fasta
  Reading number of genes from /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/03.Kinosha_sand_samples_coassembly_4.faa
  Reading coverages from /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/intermediate/10.Kinosha_sand_samples_coassembly_4.contigcov
  Reading bins from /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/intermediate/19.Kinosha_sand_samples_coassembly_4.contigsinbins
  Creating contig table in /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/20.Kinosha_sand_samples_coassembly_4.contigtable

[3 days, 9 hours, 23 minutes, 22 seconds]: STEP22 -> 22.stats.pl

Deleting temporary files in /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/temp

[3 days, 9 hours, 28 minutes, 40 seconds]: FINISHED -> Have fun!

This is the file I need most. Is it possible to get just that file from what I have run. 

Thank you in advance 

Kinosha

**Comment by kinosham** [comment] 2021-11-15 15:16
I also looked at my data log and I see it just didnt create bins and I am not sure why 

[0m[34m[3 days, 9 hours, 2 minutes, 19 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
[0m[31mWARNING: File /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/Kinosha_sand_samples_coassembly_4_DASTool_bins/ is empty!. DAStool did not generate results
[0m[31mSkipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
[0m[31mSkipping CHECKM: DAS_Tool did not predict bins.
[0m[31mSkipping BIN TABLE CREATION: (You already know: DAS_Tool did not predict bins.)

**Comment by jtamames** [comment] 2021-11-16 15:58
Hello
You should have maxbin and metabat2 directories in /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results. Is that correct? What can you see in these directories? Are there any .fasta or .fa files?
Best,
J

**Comment by kinosham** [comment] 2021-11-16 16:19
Hi

Yes i do have files in there. Fasta files.

Regards

Kinosha

**Comment by kinosham** [comment] 2021-11-16 16:20
Fasta files in one and fa. In the other

**Comment by jtamames** [comment] 2021-11-16 16:23
So the problem is in DASTool. What do you see if you run DASTool by hand, using this:

LD_LIBRARY_PATH=/apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/lib PATH=/apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/bin:$PATH /apps/anaconda3-2021.05/envs/SqueezeMeta/SqueezeMeta/bin/DAS_Tool/DAS_Tool -i /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/maxbin.table,/nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/metabat2.table -l maxbin,metabat2 -c /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/01.Kinosha_sand_samples_coassembly_4.fasta --write_bins 1 --score_threshold 0.25 --search_engine diamond -t 24 -o /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/Kinosha_sand_samples_coassembly_4 --db_directory /nlustre/data/SqueezeMeta/db --debug

**Comment by kinosham** [comment] 2021-11-18 11:43
Thank you, I am just waiting for it to run. Will let you know

Regards

Kinosha

**Comment by kinosham** [comment] 2021-11-22 10:32
Hi there

I have run what you asked me to . This was my output file

Interactive session for user: kinosha
Node: alf.bi.up.ac.za
*** Your session parameters ***
Queue: bigmem
Walltime: 2592000 seconds
CPU's allocated: 24

Running DAS Tool using 24 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 2.0.8
evaluating bin-sets
starting bin selection from 338 bins
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
bin selection complete: 111 bins above score threshold selected.
extracting bins to
/nlustre/users/kinosha/Kinosha_sand_samples_coassembly_4/results/DAS/Kinosha_sand_samples_coassembly_4_DASTool_bins

So it seemed to have worked. What should I do now to get that table in STEP
17 ?

Thank you in advance

Kinosha

**Comment by jtamames** [comment] 2021-11-22 10:38
Ok! So now you can run `restart.pl Kinosha_sand_samples_coassembly_4 -step 17`

Best,
J

**Comment by kinosham** [comment] 2021-11-22 10:44
Thank you I will try it and let you know

Kinosha

**Comment by kinosham** [comment] 2021-11-24 08:18
Thank you so much for your help. The restart worked and I have my table.

Thank you

Kinosha

**Comment by jtamames** [comment] 2021-11-24 09:13
Great to hear! Closing issue, feel free to reopen

**Closed by jtamames** 2021-11-24 09:13 UTC
