### ISSUE TITLE
When choosing --nocog and --nokegg step 12 should skip and not kill the pipeline

### ISSUE THREAD

**Issue by biobrad** [jtamames/SqueezeMeta#124] opened 2020-06-25 22:46 UTC
Hi Javier,

Thank you so much for such an awesome, well supported metagenomics pipeline. Such a breeze to work with, really really appreciate it.

This is more of a note than an 'issue'. I am doing a sequential run and choose --nocog and --nokegg.
Just a heads up that this kills the pipeline at step 12. 
I understand why and will just restart the pipeline at the next step, but if --nocog & --nokegg are selected, step 12 should maybe look for this and skip? 
Arguments:
SqueezeMeta.pl -m sequential -s samples1 -f fastqs -t 24 -canumem 60 -b 12 --nocog --nokegg

Here is the stdout:
[16 hours, 43 minutes, 0 seconds]: STEP12 -> COUNTING FUNCTION ABUNDANCES: 12.funcover.pl
  Calculating coverage for functions
  Reading coverage in /home/harbj019/results/metagenomics/squeezemeta/cret/intermediate/10.cret.mapcount
  Reading rpkm in /home/harbj019/results/metagenomics/squeezemeta/cret/intermediate/10.cret.mapcount
wc: /home/harbj019/results/metagenomics/squeezemeta/cret/results/12.cret.cog.funcover: No such file or directory
wc: /home/harbj019/results/metagenomics/squeezemeta/cret/results/12.cret.kegg.funcover: No such file or directory
Stopping in STEP12 -> 12.funcover.pl. Files /home/harbj019/results/metagenomics/squeezemeta/cret/results/12.cret.cog.funcover and/or /home/harbj019/results/metagenomics/squeezemeta/cret/results/12.cret.kegg.funcover are empty!
Died at /home/harbj019/anaconda3/envs/squeezemeta/bin/SqueezeMeta.pl line 880.

Thank you again and please let me know if you need the syslog or any other files to help squish this bug.

Cheers
Brad

**Comment by biobrad** [comment] 2020-06-26 03:29
Just a heads up, it dies at 21 as well. 
Stopping in STEP21 -> 21.minpath.pl. File /home/harbj019/results/metagenomics/squeezemeta/cret/results/21.cret.kegg.pathways is empty!
Died at /home/harbj019/anaconda3/envs/squeezemeta/bin/restart.pl line 526.

**Comment by jtamames** [comment] 2020-06-26 09:34
Hello!
Thanks for your kind words, and for using our tool.
Yes of course, that is the intended behaviour, to skip step 12 if no functional annotations were available. But I guess you didn't select --nopfam, rigth? That is why the pipeline is going into step 12... even if nothing is done with pfam there. Obviously a mistake on my side. I will fix this now, could you please confirm that you didn't select --nopfam (or better, copy your `SqueezeMeta_conf.pl` file here)?

Best,
Javier

**Comment by jtamames** [comment] 2020-06-26 09:37
Ok, I just noticed that you already copied your command line above, so no need to see the SqueezeMeta_conf.pl file

**Comment by jtamames** [comment] 2020-06-26 09:47
To fix the mapcount issue, just change line 865 in `SqueezeMeta.pl` and line 3376 in` restart.pl`, both reading:

`if((!$nocog) || (!$nokegg) || (!$nopfam)) {`

replace it by:

`if((!$nocog) || (!$nokegg) || ($opt_db)) {`

I already updated the repo with this change.

**Comment by biobrad** [comment] 2020-06-26 10:05
Thanks Javier - I really appreciate you being so supportive of the 
software!

------ Original Message ------

**Comment by jtamames** [comment] 2020-06-26 10:20
And for fixing the issue with 21.minpath.pl, replace lines 1069 in SqueezeMeta.pl and 515 in restart.pl, reading

`if(!$DAS_Tool_empty){`

by

`if((!$DAS_Tool_empty) && (!$nokegg)) {`

If you try it, I would appreciate if you can tell me if it works for you.
Best,

**Comment by biobrad** [comment] 2020-06-26 10:52
Awesome! Thanks again mate.

------ Original Message ------

**Comment by jtamames** [comment] 2020-06-30 08:17
Closing now, feel free to reopen

**Closed by jtamames** 2020-06-30 08:17 UTC
Labels: functional annotation
