### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by kinosham** [jtamames/SqueezeMeta#381] opened 2021-11-06 06:38 UTC
Good day 

Could I please get some help I have tried running my data 3 times now and it keeps halting my execution at the same place and I dont know why. 

This is the error code I get 

destination: Broken pipe
Input and filter stats:
	Input sequences: 2,346,626
	Input bases: 1,706,117,465
	Input mean length: 727.05
	Good sequences: 2,346,626 (100.00%)
	Good bases: 1,706,117,465
	Good mean length: 727.05
	Bad sequences: 0 (0.00%)
	Sequences filtered by specified parameters:
	none
-p destination: Broken pipe
Execution halted
Error running command:    export PATH="/apps/SqueezeMeta/scripts/../bin/pplacer":$PATH; /apps/SqueezeMeta/scripts/../bin/checkm taxon_set domain Bacteria /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_2/data/checkm_markers/Bacteria.ms > /dev/null 2>&1 at /apps/SqueezeMeta/scripts/../scripts/18.checkM_batch.pl line 136.
Stopping in STEP18 -> 18.checkM_batch.pl

Also is there a way to try run it from where it stopped. ? 

Regards and thank you in advance 

Kinosha

**Comment by kinosham** [comment] 2021-11-06 06:40
This is the script for 18.checkM

#-- Part of SqueezeMeta distribution. 01/05/2018 Original version, (c) Javier Tamames, CNB-CSIC
#-- Runs checkM for evaluating bins
#
#-- FPS (30-V-2018). Override $PATH for external dependencies of checkm.

use strict;
use Cwd;
use lib ".";

$|=1;

my $pwd=cwd();
my $project=$ARGV[0];
$project=~s/\/$//; 
if(-s "$project/SqueezeMeta_conf.pl" <= 1) { die "Can't find SqueezeMeta_conf.pl in $project. Is the project path ok?"; }
do "$project/SqueezeMeta_conf.pl";
do "$project/parameters.pl";

#-- Configuration variables from conf file

our($installpath,$datapath,$taxlist,%bindirs,%dasdir,$checkm_soft,$alllog,$resultpath,$tempdir,$minsize18,$numthreads,$interdir);

my $markerdir="$datapath/checkm_markers";
my $checktemp="$tempdir/checkm_batch";
my $tempc="$tempdir/checkm_prov.txt";
my %branks=('k','domain','p','phylum','c','class','o','order','f','family','g','genus','s','species');

if(-d $markerdir) {} else { system "mkdir $markerdir"; }
if(-d $checktemp) {} else { system "mkdir $checktemp"; print "Creating $checktemp\n";  }

my(%tax,%bins,%consensus,%alltaxa);

#-- Read NCBI's taxonomy 

open(infile1,$taxlist) || die "Can't find taxonomy list $taxlist\n";
print "Reading $taxlist\n";
while(<infile1>) {
	chomp;
	next if !$_;
	my @t=split(/\t/,$_);
	$tax{$t[1]}=$t[2];
	}
close infile1;

	#-- Read bin directories

foreach my $binmethod(sort keys %dasdir) {
	my $bindir=$dasdir{$binmethod};
	print "Looking for $binmethod bins in $bindir\n";
	
	#-- Read contigs in bins
	
	open(infile2,$alllog) || die "Can't open $alllog\n";
	while(<infile2>) {
		chomp;
		next if !$_;
		my @t=split(/\t/,$_);
		$tax{$t[0]}=$t[1];
		}
	close infile2;

	#-- Read all bins

opendir(indir,$bindir) || die "Can't open $bindir directory\n";
my @files=grep(/tax$/,readdir indir);
my $numbins=$#files+1;
print "$numbins bins found\n\n";
closedir indir;


my($checkmfile,$currentbin);
$checkmfile="$interdir/18.$project.$binmethod.checkM";	#-- From checkm_batch.pl, checkm results for all bins
if(-e $checkmfile) { system("rm $checkmfile"); }

	#-- Working for each bin

foreach my $m(@files) { 
	$currentbin++;
	#if($exclude{$m}) { print "**Excluding $m\n"; next; }
	my $binname=$m;
	my $binname=~s/\.tax//g;
	my $thisfile="$bindir/$m";
	$bins{$thisfile}=$binname;
	print "Bin $currentbin/$numbins: $m\n";
 
	#-- Reading the consensus taxa for the bin
 
	open(infile3,$thisfile) || die "Can't open $thisfile\n";
	while(<infile3>) { 
		chomp;
		if($_=~/Consensus/) {
			my($cons,$size,$chim,$chimlev)=split(/\t/,$_);
			$cons=~s/Consensus\: //;
			$size=~s/Total size\: //g;
			if($size<$minsize18) { print " Skipping bin because of low size ($size<$minsize18)\n"; next; }
			$consensus{$thisfile}=$cons;
			my @k=split(/\;/,$cons);
		
			#-- We store the full taxonomy for the bin because not all taxa have checkm markers
		
			foreach my $ftax(reverse @k) { 
				my($ntax,$rank);
				if($ftax!~/\_/) { $ntax=$ftax; } else { ($rank,$ntax)=split(/\_/,$ftax); }
				$ntax=~s/unclassified //gi;
				$ntax=~s/ \<.*\>//gi; 
				if($tax{$ntax} && ($rank ne "n") && ($rank ne "s")) { 
				push( @{ $alltaxa{$thisfile} },"$branks{$rank}\_$ntax");
				#   print "$m\t$ntax\t$tax{$ntax}\n";
				}
			}
		}
	}
	close infile3;

	my $inloop=1;

	#-- We will find the deepest taxa with checkm markers
	while($inloop) {  
		my $taxf=shift(@{ $alltaxa{$thisfile}  }); 
		if(!$taxf) { last; $inloop=0; }
		my($rank,$tax)=split(/\_/,$taxf);
		$tax=~s/ \<.*//g;
                $tax=~s/\s+/\_/g;
		# my $rank=$equival{$grank};
		if($rank eq "superkingdom") { $rank="domain"; }
		print " Using profile for $rank rank : $tax\n";   
		my $marker="$markerdir/$tax.ms"; 
	
		#-- Use already existing tax profile or create it
	
		if(-e $marker) {} else { 
			my $command="export PATH=\"$installpath/bin/pplacer\":\$PATH; $checkm_soft taxon_set $rank $tax $marker > /dev/null 2>&1"; #Override $PATH for external dependencies of checkm. (FPS).
                        my $ecode = system $command;
			if($ecode!=0) { die "Error running command:    $command"; }
			}
	
		#-- If it was not possible to create the profile, go for the upper rank
		
		if(-e $marker) {} else { next; }
	
		my $fastafile=$thisfile;
		$fastafile=~s/\.tax//;
		$fastafile=~s/.*\///;
		# print ">>> $checkm_soft analyze -t $numthreads -x $fastafile $marker $bindir $checktemp > /dev/null\n";
		# system("$checkm_soft analyze -t $numthreads -x $bins{$thisfile} $marker $bindir $checktemp > /dev/null");
		my $command = "export PATH=\"$installpath/bin\":\"$installpath/bin/hmmer\":\$PATH; $checkm_soft analyze -t $numthreads -x $fastafile $marker $bindir $checktemp > /dev/null 2>&1";
		my $ecode = system $command;
		if($ecode!=0) { die "Error running command:    $command"; }

		my $command = "export PATH=\"$installpath/bin\":\"$installpath/bin/hmmer\":\$PATH; $checkm_soft qa -t $numthreads $marker $checktemp -f $tempc > /dev/null 2>&1"; #Override $PATH for external dependencies of checkm. (FPS).
		my $ecode = system $command;
		if($ecode!=0) { die "Error running command:    $command"; }
	#	system("rm -r $checktemp");
		$inloop=0;
		if(-e $checkmfile) { system("cat $checkmfile $tempc > $checkmfile.prov; mv $checkmfile.prov $checkmfile"); }
		else { system("mv $tempc $checkmfile"); }
		}
 	} 
print "\nStoring results for $binmethod in $checkmfile\n";

}

Regards 

Kinosha

**Comment by fpusan** [comment] 2021-11-06 09:19
Hi!
What happens if you run
` export PATH="/apps/SqueezeMeta/scripts/../bin/pplacer":$PATH; /apps/SqueezeMeta/scripts/../bin/checkm taxon_set domain Bacteria /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_2/data/checkm_markers/Bacteria.ms`
?

**Comment by kinosham** [comment] 2021-11-06 09:44
Hi
It doesnt run or do anything.
Regards 
Kinosha 
On Sat, 6 Nov 2021, 11:19 Fernando Puente-Sánchez, ***@***.***> wrote:




Hi!
What happens if you run
 export PATH="/apps/SqueezeMeta/scripts/../bin/pplacer":$PATH; /apps/SqueezeMeta/scripts/../bin/checkm taxon_set domain Bacteria /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_2/data/checkm_markers/Bacteria.ms
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kinosham** [comment] 2021-11-08 07:19
It doesnt run it just stops any other suggestions
Regards

Kinosha

**Comment by fpusan** [comment] 2021-11-08 08:00
Don't you get any error message?
What is your OS? Are you running it on a cluster?
Can you share the `/nlustre/users/kinosha/Kinosha_sand_samples_coassembly_2/syslog` file with us?

**Comment by kinosham** [comment] 2021-11-08 14:52
Hi 
I dont get error messages. I am running it on a server we use at our university. This is the system log file 
apps/SqueezeMeta/scripts/SqueezeMeta.pl 
Run started Tue Nov  2 20:22:17 2021 in coassembly mode
Command: /apps/SqueezeMeta/scripts/SqueezeMeta.pl -m coassembly -p Kinosha_sand_samples_coassembly_2 -s /nlustre/users/kinosha/sand_sequences/all_samples -f /nlustre/users/kinosha/sand_sequences -t 24
Project: Kinosha_sand_samples_coassembly_2
Map file: /nlustre/users/kinosha/sand_sequences/all_samples
Fastq directory: /nlustre/users/kinosha/sand_sequences
Options: threads=24; contiglen=200; assembler=megahit; mapper=bowtie; evalue=; miniden=; COGS; KEGG; PFAM;

[0 seconds]: STEP0 -> SqueezeMeta.pl
[2 minutes, 19 seconds]: STEP1 -> 01.run_assembly.pl (megahit)
[7 hours, 57 minutes, 36 seconds]: STEP2 -> 02.run_barrnap.pl
[8 hours, 4 minutes, 2 seconds]: STEP3 -> 03.run_prodigal.pl
[10 hours, 7 minutes, 15 seconds]: STEP4 -> 04.rundiamond.pl
[18 hours, 12 minutes, 51 seconds]: STEP5 -> 05.run_hmmer.pl
[1 days, 19 hours, 47 minutes, 19 seconds]: STEP6 -> 06.lca.pl
[2 days, 11 hours, 22 minutes, 25 seconds]: STEP7 -> 07.fun3assign.pl
[2 days, 11 hours, 25 minutes, 41 seconds]: STEP9 -> 09.summarycontigs3.pl
[2 days, 11 hours, 28 minutes, 6 seconds]: STEP10 -> 10.mapsamples.pl
[2 days, 13 hours, 33 minutes, 30 seconds]: STEP11 -> 11.mcount.pl
[2 days, 13 hours, 34 minutes, 37 seconds]: STEP12 -> 12.funcover.pl
[2 days, 13 hours, 38 minutes, 14 seconds]: STEP13 -> 13.mergeannot2.pl
[2 days, 13 hours, 52 minutes, 33 seconds]: STEP14 -> 14.bin_maxbin.pl
[2 days, 19 hours, 37 minutes, 9 seconds]: STEP15 -> 15.bin_metabat2.pl
[2 days, 20 hours, 4 minutes, 18 seconds]: STEP16 -> 16.dastool.pl
[2 days, 20 hours, 19 minutes, 59 seconds]: STEP17 -> 17.addtax2.pl
[2 days, 20 hours, 29 minutes, 3 seconds]: STEP18 -> 18.checkM_batch.pl
Regards and thank you 
Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 10:00:26 AM GMT+2, Fernando Puente-Sánchez ***@***.***> wrote:  
 
 


Don't you get any error message?
What is your OS? Are you running it on a cluster?
Can you share the /nlustre/users/kinosha/Kinosha_sand_samples_coassembly_2/syslog file with us?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fpusan** [comment] 2021-11-08 14:56
What version are you using? the syslog file should contain more info than that unless you are in an old version of SqueezeMeta

**Comment by kinosham** [comment] 2021-11-08 15:21
I have run this version with a different data set and it has worked with no problems. But this data set is just stopping at the same place everytime. 
Regards 
Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 04:57:07 PM GMT+2, Fernando Puente-Sánchez ***@***.***> wrote:  
 
 


What version are you using? the syslog file should contain more info than that unless you are in an old version of SqueezeMeta

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fpusan** [comment] 2021-11-08 15:23
Ok, so the problem is specific to this dataset. But what version of SqueezeMeta are you using for this?

**Comment by kinosham** [comment] 2021-11-08 15:27
But I am not sure why it runs almost completely and then just stops. Sorry how can I check what version this is, the server we use has the programs preinstalled by management. Students don't have access to it installing programs. Should I request that they do an update? 
Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 05:23:24 PM GMT+2, Fernando Puente-Sánchez ***@***.***> wrote:  
 
 


Ok, so the problem is specific to this dataset. But what version of SqueezeMeta are you using for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kinosham** [comment] 2021-11-08 15:28
It seems like last modifications made to the files were in 2019
Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 05:27:21 PM GMT+2, Kinosha Moodley ***@***.***> wrote:  
 
 But I am not sure why it runs almost completely and then just stops. Sorry how can I check what version this is, the server we use has the programs preinstalled by management. Students don't have access to it installing programs. Should I request that they do an update? 
Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 05:23:24 PM GMT+2, Fernando Puente-Sánchez ***@***.***> wrote:  
 
 


Ok, so the problem is specific to this dataset. But what version of SqueezeMeta are you using for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fpusan** [comment] 2021-11-08 15:29
Ouch, that looks like an early version. Can you look for the version number in the `SqueezeMeta.pl` script?

**Comment by kinosham** [comment] 2021-11-08 15:33
I see this...  version="1.0.0betaWould it be that? 

Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 05:29:57 PM GMT+2, Fernando Puente-Sánchez ***@***.***> wrote:  
 
 


Ouch, that looks like an early version. Can you look for the version number in the SqueezeMeta.pl script?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fpusan** [comment] 2021-11-08 15:40
Yes, it's that. Indeed that version is two and a half years old.
Over that time we have not only added new features, but also solved lots of bugs and edge cases.
The fact that the software was working fine for other datasets and fails here suggests that your bins are one of those corner cases. It is likely that we have found that issue before, and solved it at some point, so the latest version might work out of the box with your dataset. Even if it doesn't, it will log much more information about the error, which hopefully would help us fix it.
I'd recommend that you ask your cluster admins for the latest version. You will also need to re-download the databases.

**Comment by kinosham** [comment] 2021-11-08 15:45
Thank you so much for taking the time to help me, I will contact admin for help with the update. I will let you know when I re-run it if it works. 
Regards 
Kinosha Moodley
PhD Student
Division of Microbiology
Department of Biochemistry, Genetics and Microbiology
Lab 9-40
Natural and Agricultural Sciences Building
Lunnon Street
University of Pretoria
Pretoria
0001
South Africa 
 

    On Monday, November 8, 2021, 05:40:58 PM GMT+2, Fernando Puente-Sánchez ***@***.***> wrote:  
 
 


Yes, it's that. Indeed that version is two and a half years old.
Over that time we have not only added new features, but also solved lots of bugs and edge cases.
The fact that the software was working fine for other datasets and fails here suggests that your bins are one of those corner cases. It is likely that we have found that issue before, and solved it at some point, so the latest version might work out of the box with your dataset. Even if it doesn't, it will log much more information about the error, which hopefully would help us fix it.
I'd recommend that you ask your cluster admins for the latest version. You will also need to re-download the databases.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fpusan** [comment] 2021-11-08 15:46
Sure, good luck!
I will close this, feel free to open a new issue if you still have problems when using the latest version,

**Closed by fpusan** 2021-11-08 15:46 UTC
