### ISSUE TITLE
Rscript execution error: No such file or directory during DAS_TOOL MERGING step

### ISSUE THREAD

**Issue by razz1618** [jtamames/SqueezeMeta#169] opened 2020-10-09 01:49 UTC
Hi,
I am working on metagenomic sequence. Everything goes well without any error till merging bins. I get following error:
[13 hours, 2 minutes, 32 seconds]: STEP14 -> MAXBIN BINNING: 14.bin_maxbin.pl
[13 hours, 5 minutes, 28 seconds]: STEP15 -> METABAT BINNING: 15.bin_metabat2.pl
[13 hours, 5 minutes, 41 seconds]: STEP16 -> DAS_TOOL MERGING: 16.dastool.pl
**Rscript execution error: No such file or directory**
Can't open /home/mcs/gene/shail/metagenomics/metagenomics/squeezemeta_analysis/original_bottle/results/DAS/original_bottle_DASTool_bins directory, no DAStool results
WARNING: File /home/mcs/gene/shail/metagenomics/metagenomics/squeezemeta_analysis/original_bottle/results/DAS/original_bottle_DASTool_bins/ is empty!. DAStool did not generate results
Skipping BIN TAX ASSIGNMENT: DAS_Tool did not predict bins.
Died at /home/mcs/miniconda3/envs/squeezemeta/bin/SqueezeMeta.pl line 999.

I guess the error is related to Rscript. When I tried to run an example R file (Rscript helloworld.R) within squeezemeta environment I get the same error saying **Rscript execution error: No such file or directory**

As I am working on a lab server there are a few instances of R installed in different conda environments (which should not make a difference as squeezemeta is in a separate environment). I have attached the log files.

[syslog.txt](https://github.com/jtamames/SqueezeMeta/files/5352095/syslog.txt)
[original_bottle_DASTool_scg.log](https://github.com/jtamames/SqueezeMeta/files/5352096/original_bottle_DASTool_scg.log)
[original_bottle_DASTool.log](https://github.com/jtamames/SqueezeMeta/files/5352097/original_bottle_DASTool.log)

(I did not try the test files as I was unable to download them :server failed)

**Comment by fpusan** [comment] 2020-10-09 07:56
> (I did not try the test files as I was unable to download them :server failed)

This is worrying, we've been having issues with our servers lately. What was the actual error that you got?

Regarding the other issue, it seems like that Rscript is indeed looking for the wrong R executable.

What's the output of `which R` and `which Rscript` when run within the squeezemeta conda environment?

**Comment by razz1618** [comment] 2020-10-09 11:55
Regarding the server failure. I get "500 Internal Server **Error"** for the test file, but the database file didn't have any issue. 
It might be an issue with user authentication as for test file the link is **http://wwwuser.cnb.csic.es/~squeezem/test.tar.gz**
while for database file it is **http://silvani.cnb.csic.es/SqueezeMeta/SqueezeMetaDB.tar**. Secondly, I am working from China, so the Chinese censorship might be also the cause (strangely, the database file gets downloaded though).

Regarding the Rscript
Both which R and which Rscript shows following output with squeezemeta env. activated
**~/miniconda3/envs/squeezemeta/bin/Rscript

**Comment by fpusan** [comment] 2020-10-09 12:07
Yeah, we've had troubles with people accessing from China before. I see that silvani (the database server) works, I think we'll move the other data there too.

It's so weird that `which R` is pointing to Rscript instead of R.

Here's my output (also in conda).
```
which R
~/miniconda3/envs/SqueezeMeta/bin/R

which Rscript
~/miniconda3/envs/SqueezeMeta/bin/Rscript
```

Is the R executable present in your `~/miniconda3/envs/SqueezeMeta/bin/` directory?

**Comment by razz1618** [comment] 2020-10-09 12:16
Yes. R and Rscript are both present in the ~/miniconda3/envs/SqueezeMeta/bin/ directory

**Comment by fpusan** [comment] 2020-10-09 14:29
Ok, that makes more sense to me. Anyways, I can't reproduce the issue on a newly created conda environment (Rscript runs my own hello world script just fine).

Let's see where yours is pointing at... can you run `Rscript -e 'print("Hello world!")' --verbose` and tell me what the output is?

**Comment by razz1618** [comment] 2020-10-09 23:32
HI, this is the output-
(squeezemeta) [mcs@mcs1 ~]$ Rscript -e 'print("Hello world!")' --verbose
running
  '/home/mcs/miniconda3/envs/SqueezeMeta/lib/R/bin/R --slave --no-restore -e print("Hello world!")'

**Rscript execution error: No such file or directory**


When I check the directory "/home/mcs/miniconda3/envs/SqueezeMeta/lib/R/bin/R", both R and Rscript executable files are present

**Comment by razz1618** [comment] 2020-10-10 00:48
So, I recreated a new squeezemeta conda environment (checked the "hello world" command) and restarted from step 16. Now it seems to be working fine.

**Comment by razz1618** [comment] 2020-10-10 02:31
Is it possible to do multiple separate co-assemblies within a single run, for e.g.    

![capture-20201010-102755](https://user-images.githubusercontent.com/59241611/95643699-57185b00-0ae3-11eb-9b4a-df60dee0ddbf.png).

Secondly, is it possible to include third-party classifiers? results like from kraken or kaiju into squeezemeta project?

**Comment by jtamames** [comment] 2020-10-10 07:06
Hello!
You would have to do two different runs for the two different coassemblies.
Regarding other classifiers, here is not a direct way to do it. In my opinion, I would use kraken or kaiju if I want a preliminary result rigth away. In any other circumstance I would use the SqueezeMeta annotation, which will be moe precise. Regarding this, see our paper in [https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-019-6289-6](url)
Best,
Javier

**Comment by razz1618** [comment] 2020-10-10 12:58
Hi, 
Thanks for the link.The pipeline was successfully executed. I will run sqm_reads.pl and compare the results with this (contig based) . thanks.

**Comment by fpusan** [comment] 2020-10-10 13:17
Glad to hear it worked! Closing issue

**Closed by fpusan** 2020-10-10 13:17 UTC
